### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mpaquet** [Mangopay/mangopay2-php-sdk#103]
Hello,

I think it would be nice to support proxy usage :)

**Comment by dovit** [comment]
It would be nice indeed ; could you give a date when this support will be available ?

**Comment by hobailey** [comment]
Hello to you both - this is something we're currently looking into and I'll let you know when I have more info (in the next couple of weeks I hope).

**Comment by hobailey** [comment]
Hey, thanks @dovit very much for your PR #115 - just to check, @mpaquet does this respond to your needs too?

**Comment by mpaquet** [comment]
I'd say it's a nice beginning.
Ine my case it will do the work, but I think other people may have deeper needs with this feature (advanced configuration, error handling...).

**Comment by hobailey** [comment]
OK, thanks for the feedback. Let's go with this go now at least and review later with those who need a deeper integration.
