### ISSUE TITLE
Request: Support filtering by multiple types in \MangoPay\FilterTransactions

### ISSUE THREAD

**Issue by leihog** [Mangopay/mangopay2-php-sdk#104]
I would like to only get transactions that are either PAYINs or PAYOUTs. Now I have to do two requests to your API and then merge the results. This slows things down needlessly.
Allowing a comma separated list would solve it: `$filter->Type = 'PAYIN,PAYOUT'; `

**Comment by hobailey** [comment]
Hi @leihog, thanks for the feedback. We'll soon be releasing a dedicated reporting feature which will allow you to easily do this :-)
