### ISSUE TITLE
what is and where to get this vendor/autoload.php 

### ISSUE THREAD

**Issue by pakistanihaider** [Mangopay/mangopay2-php-sdk#105]
Please someone explain,i downloaded this sdk and i went to try demos and tests. but it failed as there is no autoload.php.. even thou i provided the autoloader.php from the mangopay directory but then i got 

> Class 'Psr\Log\NullLogger' not found in D:\wamp\www\mangoDemo\MangoPay\MangoPayApi.php on line 178

what to do??  a little more explanation would have been better about autoload.php file..??

**Comment by hobailey** [comment]
Please read the readme :-) Especially "Installation without Composer".

**Comment by pakistanihaider** [comment]
@hobailey 
Thankyou for response. i tried both with composer and without composer.
still i was getting error the error which i showed above.

**Comment by hobailey** [comment]
@pakistanihaider sorry for the delay getting back to you, but there is definitly no problem when using Composer correctly. 
If you're having troubles, I suggest you use the prepackaged version that is available as a zip from the downloads page - https://github.com/Mangopay/mangopay2-php-sdk/releases (also mentioned in the readme ;-) )

**Comment by rajuprasad21** [comment]
hello @pakistanihaider  how did you solve the problem ?

**Comment by huggy06** [comment]
Hello

We are using codeigniter and we got same problem. We need full version with dependencies (no composer) but  https://github.com/Mangopay/mangopay2-php-sdk/releases does not provide any zip version with entire package.

Thanks for your reply
