### ISSUE TITLE
[tag] 4.2.2

### ISSUE THREAD

**Issue by yacinebenfaid** [Mangopay/mangopay2-php-sdk#106]
Hi, 
could you please create a new tag (4.2.2), I actually need those commits (https://github.com/Mangopay/mangopay2-php-sdk/commit/5d67fb96b180a2864be598ef62419466d1b8bb08 , https://github.com/Mangopay/mangopay2-php-sdk/commit/ec4e3d2c0958b7973f133697c589051d7369c42f)

Thank you :)

**Comment by hobailey** [comment]
Hi @yacinebenfaid, this functionality is not yet activate for everyone as we're rolling it out gradually - have you already discussed with our support team and therefore have it activated for your account?

**Comment by yacinebenfaid** [comment]
Yes of course, they told us the field `statementDescriptor` should be activated this week (more precisely the 16/05).

**Comment by hobailey** [comment]
OK, I've just released it then :-)
