### ISSUE TITLE
Bank wire request failed

### ISSUE THREAD

**Issue by vivekpnv** [Mangopay/mangopay2-php-sdk#107]
Hi, we are getting an error trying to make a bank-wire request. please see the attached document below. Error is showing on line 149( in Mangopay/Libraries/ApiBase.php). However if we modify line 55 from ''payins_bankwire-web_create' => array( '/payins/bankwire/direct/', RequestType::POST ),
' to ''payins_bankwire-direct_create' => array( '/payins/bankwire/direct/', RequestType::POST ),
' the issue seems to go away(Successful request). Please confirm if i continue work with change i made or take a look at this issue and suggest me a solution.
API Request Sent:
MangoPay\PayIn Object
(
    [CreditedWalletId] => 12650540
    [PaymentType] => BANKWIRE
    [PaymentDetails] => MangoPay\PayInPaymentDetailsBankWire Object
        (
            [DeclaredDebitedFunds] => 2000
            [DeclaredFees] => 100
            [BankAccount] => MangoPay\BankAccount Object
                (
                    [UserId] => 12631015
                    [Type] => IBAN
                    [OwnerName] => mika hakkinen
                    [OwnerAddress] => Test address, Macclesfield, CF38 2SX, GB
                    [Details] => 
                    [Id] => 12650540
                    [Tag] => 
                    [CreationDate] => 
                    [IBAN] => GB29NWBK60161331926819
                    [BIC] => MIDLGB22
                )

            [WireReference] => test
        )

    [ExecutionType] => DIRECT
    [ExecutionDetails] => MangoPay\PayInExecutionDetailsWeb Object
        (
            [RedirectURL] => 
            [ReturnURL] =>
            [TemplateURL] => 
            [TemplateURLOptions] => 
            [Culture] => EN
            [SecureMode] => DEFAULT
        )

    [AuthorId] => 12631015
    [CreditedUserId] => 12631015
    [DebitedFunds] => 2000
    [CreditedFunds] => 2000
    [Fees] => 100
    [Status] => 
    [ResultCode] => 
    [ResultMessage] => 
    [ExecutionDate] => 
    [Type] => PAY_IN
    [Nature] => REGULAR
    [DebitedWalletId] => 
    [Id] => 
    [Tag] => 
    [CreationDate] => 
)
![mangopay-api-request-error-2016-05-21_09 32 25](https://cloud.githubusercontent.com/assets/12844309/15469376/859cc0d0-2107-11e6-987f-6c3685f1536f.png)

**Comment by hobailey** [comment]
Hi @vivekpnv - are you using the latest version of the SDK? Because https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/Libraries/ApiBase.php#L55 shows 
```
'payins_bankwire-direct_create' => array( '/payins/bankwire/direct/', RequestType::POST ),
```
therefore no change should be required (and with the latest version of the SDK, I do not have the problem you are describing).
