### ISSUE TITLE
call mangopay api with Guzzle

### ISSUE THREAD

**Issue by karousn** [Mangopay/mangopay2-php-sdk#112]
I use guzzle to do a "Pre-authorization" action after generate a data and accessKey by this bundle ( https://github.com/TeknooSoftware/mango-pay-bundle ).
the format of my call

`$cardRegistrationSession = new \Teknoo\MangoPayBundle\Entity\CardRegistrationSession\CardRegistrationSession();

$result = $this->get('teknoo.mangopaybundle.service.card_registration')->prepare($this->getUser(), $cardRegistrationSession);
$client = new Client();
$response = $client->request('POST', $result->getCardRegistrationURL(), ['json' => [
            'data' => $result->getData(),
            'accessKeyRef' => $result->getAccessKeyRef(),
            'returnURL' => $result->getReturnUrl(),
            'cardNumber' => '3569990000000165',
            'cardExpirationDate' => '0117',
            'cardCvx' => '120'
        ]]);`

always , i get this message error : errorCode=09101
the same when use Curl : `curl -X POST https://homologation-webpayment.payline.com/webpayment/getToken -d '{"data":"kQPPb_p6QpYPvI1-YUyRdIzhjugJJglryfZui15pKc4w-TqjudjkAwi2ypldnCdUS4wCy-yiraxeE65tmxOe8A","accessKeyRef":"1X0m87dmM2LiwFgxPLBJ","returnURL":"http:\/\/myapp.dev\/app_dev.php\/card-registration\/return\/574c126fe6fae","cardNumber":"3569990000000165","cardExpirationDate":"0117","cardCvx":"120"}'` but it working fine with navigator using form.

**Comment by hobailey** [comment]
Hi @karousn, you absolutely must not use this function like this (POSTing the card info to the `Ca rdRegistrationURL` via cURL because that means that the card info has passed via your server which it **must not** unless your company/server are PCI compliant.
You must POST the information directly from a web form from the user's browser - as you say you have already tried.

**Comment by cedvdb** [comment]
Those are some wild assumptions.

In our case we have a test suite *running on the server*, which is currently failing. The fact that it runs on the server **for the test suite** and not the actual production code is beside the point.

**Comment by cedvdb** [comment]
Okay I managed to do it, The documentation is misleading, you have to send the body as a string as opposed to FormData.
