### ISSUE TITLE
UpdateBankAccount

### ISSUE THREAD

**Issue by Kafei59** [Mangopay/mangopay2-php-sdk#113]
Bonjour,

Il est possible de désactiver un BankAccount en utilisant une requête Http PUT et de préciser:
{
Active: false
}

Cependant, il n'y a toujours pas la méthode disponible dans votre SDK :)
Serait-il possible de rajouter une méthode: updateBankAccount ?

**Comment by hobailey** [comment]
Solved with #114 :-)

**Comment by huggy06** [comment]
Bonjour la methode UpdateBankAccount ne fonctionne pas.
J'essai de modifier l'IBAN mais cela ne fonctionne pas.
Avez vous une idée ?

$UserId = "37872694";
            $BankAccount = new \MangoPay\BankAccount();
            $BankAccount->Id='37895159';
            $BankAccount->Type = "IBAN";
            $BankAccount->Details = new \MangoPay\BankAccountDetailsIBAN();
            $BankAccount->Details->IBAN = "FR7618829754160173622224154";
            $BankAccount->Details->BIC = "CMBRFR2BCME";
            $BankAccount->OwnerName = "titi";
            $BankAccount->OwnerAddress = new \MangoPay\Address();
            $BankAccount->OwnerAddress->AddressLine1 = "rue de la paix";
            $BankAccount->OwnerAddress->City = "Paris";
            $BankAccount->OwnerAddress->Region = "";
            $BankAccount->OwnerAddress->PostalCode = "75001";
            $BankAccount->OwnerAddress->Country = "FR";
            $result = $mangoPayApi->Users->UpdateBankAccount($UserId, $BankAccount);
