### ISSUE TITLE
error 105206, Registration data : Invalid format

### ISSUE THREAD

**Issue by Zebu78** [Mangopay/mangopay2-php-sdk#116]
Bonjour j'essaye d'implementer votre api j'ai donc creer un compte sandbox pour creer un user, wallet il n'y a pas de probleme mais quand je veux creer une carte quand j'arrive a l'étape ou il faut update la cardRegistration une erreur survient. Je ne comprend pas d'ou cela peut venir j'utilise postman pour faire les requetes.
<img width="1109" alt="capture d ecran 2016-07-12 a 23 44 32" src="https://cloud.githubusercontent.com/assets/9802652/16784840/fbbe3d98-488a-11e6-8dc9-ffdc61ffbc06.png">

Les headers sont vides, cela vient de la?

**Comment by mpozz** [comment]
Bonjour @Zebu78, 

Nous n'arrivons pas à décrypter les données pour cette carte. A première vue il manque un "data=" devant la valeur "RegistrationData : WlFLN..." dans les données envoyées. Pourriez-vous modifier / refaire une tentative et nous tenir au courant ? (Reprendre l'intégralité des données en retour du post sur le CardRegistrationUrl)

**Comment by Zebu78** [comment]
Bonjour @mpozz Merci beaucoup effectivement cela du fait que je n'envoyais que ce qui se trouvait apres le data= et non ce que je recevais en entier.
