### ISSUE TITLE
PayOut and Bank Account Create returns Internal server Error 500

### ISSUE THREAD

**Issue by Daneel-Olivaw** [Mangopay/mangopay2-php-sdk#117]
this is my object

```
{
"Tag": "custom meta",
"AuthorId": "8494514",
"DebitedFunds": {
"Currency": "EUR",
"Amount": 12
},
"Fees": {
"Currency": "EUR",
"Amount": 12
},
"BankAccountId": "14213351",
"DebitedWalletId": "8519987",
"BankWireRef": "invoice 7282"
}
````

```
try {


        $payOutObject = new \MangoPay\PayOut();

        $payOutObject->Tag = $data['Tag'];

        $payOutObject->AuthorId = $data['AuthorId'];

        $payOutObject->DebitedFunds = new \MangoPay\Money();

        $payOutObject->DebitedFunds->Currency = $data['AuthorId'];
        $payOutObject->DebitedFunds->Amount = $data['Amount'];

        $payOutObject->Fees = new \MangoPay\Money();

        $payOutObject->Fees->Currency = $data["Fees"]["Currency"];
        $payOutObject->Fees->Amount = 0;

        $payOutObject->BankAccountId = $data['BankAccountId'];
        $payOutObject->DebitedWalletId = $data['DebitedWalletId'];


        $Result = $api->PayOuts->Create($payOutObject);

        print_r($Result);

        } catch(MangoPay\Libraries\ResponseException $e) {

            print_r($e->GetErrorDetails());

        } catch(MangoPay\Libraries\Exception $e) {

            print_r($e->GetErrorDetails());

        }
```

Don't catch any error and returns Internal Server Error only

The same when I try to create a Bank Account

**Comment by hobailey** [comment]
Hi @Daneel-Olivaw, I haven't tried your code, but I think it's most likely because you're missing certain parameters and also some of your variables look incorrect (providing an authorId to the DebitedFunds Currency parameter for one). 
Here's an example (from [here](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/workflow/scripts/payout.php)):
```
$PayOut = new \MangoPay\PayOut();
$PayOut->AuthorId = $_SESSION["MangoPayDemo"]["UserLegal"];
$PayOut->DebitedWalletID = $_SESSION["MangoPayDemo"]["WalletForLegalUser"];
$PayOut->DebitedFunds = new \MangoPay\Money();
$PayOut->DebitedFunds->Currency = "EUR";
$PayOut->DebitedFunds->Amount = 610;
$PayOut->Fees = new \MangoPay\Money();
$PayOut->Fees->Currency = "EUR";
$PayOut->Fees->Amount = 125;
$PayOut->MeanOfPaymentDetails = new \MangoPay\PayOutPaymentDetailsBankWire();
$PayOut->MeanOfPaymentDetails->BankAccountId = $_SESSION["MangoPayDemo"]["BankAccount"];
$result = $mangoPayApi->PayOuts->Create($PayOut);
```

**Comment by Daneel-Olivaw** [comment]
@hobailey Thank you! the problem was that I didn't had 

`$PayOut->MeanOfPaymentDetails = new \MangoPay\PayOutPaymentDetailsBankWire();
`

and this method is not reflected in API Endpoints of Mangopay beacuse codesample isn't avaliable.

The issue with the Bank Account was the same. I was using this snnipet provided in the Mangopay API page:

`try {

$UserId = 8494514;

$BankAccount = new \MangoPay\BankAccount();
$BankAccount->Tag = "custom meta";
$BankAccount->OwnerAddress = new \MangoPay\Address();
$BankAccount->OwnerAddress->AddressLine1 = "1 Mangopay Street";
$BankAccount->OwnerAddress->AddressLine2 = "The Loop";
$BankAccount->OwnerAddress->City = "Paris";
$BankAccount->OwnerAddress->Region = "Ile de France";
$BankAccount->OwnerAddress->PostalCode = "75001";
$BankAccount->OwnerAddress->Country = "FR";
$BankAccount->OwnerName = "Joe Blogs";
$BankAccount->IBAN = "FR3020041010124530725S03383";
$BankAccount->BIC = "CRLYFRPP";

$Result = $Api->Users->CreateBankAccount($UserId, $BankAccount);

} catch(MangoPay\Libraries\ResponseException $e) {
// handle/log the response exception with code $e->GetCode(), message $e->GetMessage() and error(s) $e->GetErrorDetails()

} catch(MangoPay\Libraries\Exception $e) {
// handle/log the exception $e->GetMessage()

}`

And Here There is no method

`        $BankAccount->Details = new MangoPay\BankAccountDetailsIBAN();
`

**Comment by hobailey** [comment]
Ah yes, we'll correct that - thanks for the feedback :-)
