### ISSUE TITLE
JS Example failing when CORS supported but protocolls don't match

### ISSUE THREAD

**Issue by ferdynator** [Mangopay/mangopay2-php-sdk#119]
I experienced a problem when testing locally on http://localhost. Since the redirect url is https the browser (Firefox 48.0) refused to call the resource from an unprotected page.

I was able to fix this by adding an additional test to the `corsSupport` function:

    // IE 10 and above, Firefox, Chrome, Opera etc.
    if ("withCredentials" in new XMLHttpRequest()) {
        return (window.location.protocol === _cardRegisterData.cardRegistrationURL.substr(0, 5));
    }

I can open a PR if this fixes the issue correctly.

**Comment by hobailey** [comment]
Hey @ferdynator, I'm not sure I understand what you're trying to do infact. This SDK is in PHP - are you perhaps using our [JS card registration kit](https://github.com/Mangopay/cardregistration-js-kit)?

**Comment by ferdynator** [comment]
Oh indeed. I just saw the file in this repository. You include an old version of the kit: https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/js/mangopay.js

Also the issue I reported is valid for the card registration kit too. Should I open an issue there?

**Comment by hobailey** [comment]
That would be great - and why not add a PR if you've already got the working modification :-)
Thanks very much!
And we'll update the old file in this repo to avoid confusion.
