### ISSUE TITLE
ResponseException in RestTool.php line 335: Unauthorized

### ISSUE THREAD

**Issue by devngenious** [Mangopay/mangopay2-php-sdk#121]
ive set up the sdk in laravel but when i try to create a natural user i get 
ResponseException in RestTool.php line 335:
Unauthorized

**Comment by hobailey** [comment]
Hi @devngenious - does everything work correctly for other functions? I'm guessing not and hence it is most likely because your Passsphrase/ClientId/Environment combination is wrong somewhere :-/
