### ISSUE TITLE
Bad Request create Infinite Loop on PayOut

### ISSUE THREAD

**Issue by Kafei59** [Mangopay/mangopay2-php-sdk#124]
Salut les gars,

J'ai lancé une mauvaise requête sur l'API (v2), en voulant implémenter un PayOut.
Au lieu de mettre un DebitedWalletID, j'ai mis directement mon propre object Wallet.
De ce fait, au lieu de lire un string, l'API a lu un objet.
Pas de problème, me direz-vous, mais votre API m'a sorti une boucle infinie sans me préciser quoi que ce soit ! J'ai cherché presque une heure avant de trouver mon problème (oops).
Je ne sais pas trop d'où cela peut provenir, je viens de faire des tests avec plusieurs objets/types, et le problème ne se reproduit pas, mais d'après mon XDEBUG, cela viendrait d'un return ...

Dans ApiPayOuts:
> return $this->CreateObject('payouts_' . $paymentKey . '_create', $payOut, '\MangoPay\PayOut', null, null, $idempotencyKey);

Je me permets quand même de lancer une issue pour vérifier quand même s'il ne s'agit pas d'un petit problème chez vous (et si pas, n'hésitez pas à close mon issue).
Au plaisir,

Pierrick.

**Comment by hobailey** [comment]
Hey @Kafei59, this sounds strange - do you have the original request/code you did? And/or the time when you did this (so I can check the logs)? 
Unfortunatley I'm unable to reproduce the problem with this:
```
$Wallet = $mangoPayApi->Wallets->Get("1696924");

$PayOut = new \MangoPay\PayOut();
$PayOut->DebitedWalletId = $Wallet;
$PayOut->AuthorId = "1696923";
$PayOut->DebitedFunds = new \MangoPay\Money();
$PayOut->DebitedFunds->Currency = "EUR";
$PayOut->DebitedFunds->Amount = 15;
$PayOut->Fees = new \MangoPay\Money();
$PayOut->Fees->Currency = "EUR";
$PayOut->Fees->Amount = 0;

$PayOut->PaymentType = \MangoPay\PayOutPaymentType::BankWire;
$PayOut->MeanOfPaymentDetails = new \MangoPay\PayOutPaymentDetailsBankWire();
$PayOut->MeanOfPaymentDetails->BankAccountId = "2408454";

try {
$result = $mangoPayApi->PayOuts->Create($PayOut);
var_dump($result);

} catch(MangoPay\Libraries\ResponseException $e) {
var_dump($e->GetErrorDetails());

} catch(MangoPay\Libraries\Exception $e) {


}
```
As the `GetErrorDetails() ` `var_dump` gives some (rather inaccurate!) errors, but no loop issue: 
```
object(MangoPay\Libraries\Error)#35 (5) {
  ["Message"]=>
  string(117) "One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error."
  ["Errors"]=>
  object(stdClass)#37 (5) {
    ["AuthorId"]=>
    string(31) "The AuthorId field is required."
    ["DebitedFunds"]=>
    string(35) "The DebitedFunds field is required."
    ["Fees"]=>
    string(27) "The Fees field is required."
    ["DebitedWalletId"]=>
    string(38) "The DebitedWalletId field is required."
    ["BankAccountId"]=>
    string(36) "The BankAccountId field is required."
  }
  ["Id"]=>
  string(47) "704152ef-7998-4579-a05d-7c40fc2c3052#1473269399"
  ["Date"]=>
  float(1473269400)
  ["Type"]=>
  string(11) "param_error"
}
```
