### ISSUE TITLE
Error class does not contain the attribute Type 

### ISSUE THREAD

**Issue by bn-fondative** [Mangopay/mangopay2-php-sdk#127]
Hello,
Why «Error» class does not contain the attribute «Type»?
In fact, I want to set up a Listner to identify exceptions for the invalid forms inputs. In this case, I want to return the errors array ([param => errorMessage, ...]). To identify these exceptions, I'll have to test (code = 400 and Error.Type = "param_error").
I think it could be interesting if we add this attribute to the Error class.
thanks

**Comment by hobailey** [comment]
Hey @bn-fondative, thanks very much for the feedback - I've just added this in for you.
So if you're using the usual `try`/`catch`, I guess you could use something like this:
```
try {
  $result = $mangoPayApi->Users->Create($User);
  //do something with the result
 
 } catch(MangoPay\Libraries\ResponseException $e) {
  // handle/log the response exception with code $e->GetCode(), message $e->GetMessage() and error(s) $e->GetErrorDetails()
  if ($e->GetErrorDetails()->Type=="param_error") {
    //foreach through $e->GetErrorDetails()->Errors ?
  }

} catch(MangoPay\Libraries\Exception $e) {
  // handle/log the exception $e->GetMessage()

}
```

**Comment by bn-fondative** [comment]
It's great that you've take in consideration all the parameters returned by the API. 
Thank you for your quick reply.
