### ISSUE TITLE
AuthorizationTokenManager error

### ISSUE THREAD

**Issue by electrixx90** [Mangopay/mangopay2-php-sdk#129]
I've updated the SDK from v1 to v2.
Now I can't call the API from localhost and I have this error when I try to create a natural user

`Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: MangoPay\Libraries\AuthorizationTokenManager::GetToken(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;MangoPay\OAuthToken&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition " at .........}`

How can I fix? I've tried to install a self signed certificate on my local Apache but the problem persists.
Thanks.

**Comment by electrixx90** [comment]
This is the code from my Symfony project:
`$new_mango_user = new MangoPay\UserNatural();
        $new_mango_user->PersonType = "NATURAL";
        $new_mango_user->Email = $supplier->getEmail();
        $new_mango_user->FirstName = $supplier->getFirstName();
        $new_mango_user->LastName = $supplier->getLastName();
        $new_mango_user->Tag = "SUPPLIER_IT";

        $new_mango_user->CountryOfResidence = "IT";
        $new_mango_user->Nationality = "IT";
        $int = rand(-757728000,914803200);
        $birthday = new \DateTime();
        $birthday->setTimestamp($int);
        $new_mango_user->Birthday = $birthday->getTimestamp();

        $this->logger->info("Starting MP supplier creation: ".print_r($new_mango_user,true));
        try {
// >>> Here error happen
            $mangoUser = $this->mangoPayApi->Users->Create($new_mango_user);
        } catch (MangoPay\Libraries\ResponseException  $e) {
           // ...
        } catch (MangoPay\Libraries\Exception $e) {
            // ....
        }`

**Comment by electrixx90** [comment]
Ok I've solved. 
I've deleted my temporary oauth file. 
Sorry for inconvenience.

**Comment by hobailey** [comment]
No worries - thanks for updating us with the outcome :-)
