### ISSUE TITLE
only variables should be passed by reference

### ISSUE THREAD

**Issue by Zebu78** [Mangopay/mangopay2-php-sdk#130]
I'm using symfony3 and i use you php SDK but i get this error:

in vendor/mangopay/php-sdk-v2/MangoPay/ApiClients.php at line 111 
`public function GetWallets($fundsType = null)
{
        if (is_null($fundsType)){
            return $this->GetList('client_wallets', new \MangoPay\Pagination(), '\MangoPay\Wallet');
        } else if ($fundsType == FundsType::FEES){
            return $this->GetList('client_wallets_fees', new \MangoPay\Pagination(), '\MangoPay\Wallet');
        } else if ($fundsType == FundsType::CREDIT){`

**Comment by hobailey** [comment]
Hi, I think your message was missing a screenshot (or info about the error)?

**Comment by Zebu78** [comment]
i'm trying to get The client Wallet

here is my method
`    public function getClientWallet()
    {
        try {
            $result = $this->mangoPayApi->Clients->GetWallets();

        } catch(MangoPay\Libraries\ResponseException $e) {
            $result = $e->GetErrorDetails();
            // handle/log the response exception with code $e->GetCode(), message $e->GetMessage() and error(s) $e->GetErrorDetails()
        } catch(MangoPay\Libraries\Exception $e) {
            // handle/log the exception $e->GetMessage()
            $result = $e->GetMessage();
        }

        return ($result);
    }`
![screenshot from 2016-09-23 15-53-44](https://cloud.githubusercontent.com/assets/9802652/18788131/070ffc78-81a6-11e6-841a-346751a5a5b3.png)
 :

**Comment by hobailey** [comment]
Hmm, I don't have a problem with this function - are you using the latest version of the SDK? And from looking at your code, I'd say that `$this` is going to be unset though?

**Comment by Zebu78** [comment]
it come from only this function, i won't use it.
Thanks for replying so fast.

**Comment by nclavaud** [comment]
This is PHP7 raising a notice because [only variables should be passed by reference](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.error-handling.strict).

And Symfony [Debug component](http://symfony.com/doc/current/components/debug.html)'s ErrorHandler converting this _notice_ into an exception.

You might want to give a try with debug mode off.

**Comment by hobailey** [comment]
Glad it's resolved @Zebu78. And thanks for the useful info @nclavaud :-)

**Comment by Zebu78** [comment]
ok thanks @nclavaud
