### ISSUE TITLE
can't integrate Mangopay

### ISSUE THREAD

**Issue by recharde** [Mangopay/mangopay2-php-sdk#131]
Hello, From This Github code there are two section one is demos and one is
Mangopay, if i run demos file then i get a registration form and i get the
something value as an array, i think its not a proper way for send a value.
but when i run mangopay file there i get blank page or error, i give all
client details in config file, i check ApiUser file but i cant get any
output how can i get it ? how i give natural user details, i check your all
github file very carefully but i cant integrate it.

**Comment by hobailey** [comment]
Hi @recharde, could you give the Github URL of the files you are referring to - I'm afraid I don't quite understand otherwise. And could you include the relevant bit of your code too?

**Comment by recharde** [comment]
<?php

namespace Path\To\Service;

use MangoPay;


class MangoPayService
{

    private $mangoPayApi;

    public function __construct()
    {
		echo 'hi1';
        $this->mangoPayApi = new MangoPay\MangoPayApi();
        $this->mangoPayApi->Config->ClientId = 'nageshwarandanirban';
        $this->mangoPayApi->Config->ClientPassword = '1YKLSdLV2wsrMYLSHDbQta9DSyct';
        $this->mangoPayApi->Config->TemporaryFolder = '/cache/';    
        $this->mangoPayApi->Config->BaseUrl = 'https://api.sandbox.mangopay.com';
		echo 'hi2';
    }

    /**
     * Create Mangopay User
     * @return MangopPayUser $mangoUser
     */
    public function getMangoUser()
    {
        echo 'hi3';
        $mangoUser = new \MangoPay\UserNatural();
        $mangoUser->PersonType = "NATURAL";
        $mangoUser->FirstName = 'Recharde';
        $mangoUser->LastName = 'William';
        $mangoUser->Birthday = 1409735187;
        $mangoUser->Nationality = "FR";
        $mangoUser->CountryOfResidence = "FR";
        $mangoUser->Email = 'recharde2016@gmail.com';

        //Send the request
        $mangoUser = $this->mangoPayApi->Users->Create($mangoUser);
		print '<pre>';print_r($mangoUser);print '</pre>';
		echo "hi User".$mangoUser;

        return $mangoUser;
    }
}
using this code i get only blank page no echo no print_r.
https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/ApiUsers.php
This File i changes but i cant get any output ?

**Comment by nclavaud** [comment]
Hi @recharde,

I suggest you take care of **not** publishing your personal information and credentials (client id / password) publicly. Obfuscating data before posting is good practice.

The code your are quoting is a PHP class, but this class is never instanciated. You can find more information in the [PHP documentation](http://php.net/manual/fr/language.types.object.php) on how to instantiate objects from classes.

However, I strongly suggest you dig into [this example](https://github.com/Mangopay/mangopay2-php-sdk/blob/2.4.4/demos/users_create.php) which does exactly what you want. You could try to edit and run `users_create.php`. Should work.

**Comment by hobailey** [comment]
Thanks @nclavaud.
I indeed suggest you use the existing demos :-)
