### ISSUE TITLE
Create a Card Registration

### ISSUE THREAD

**Issue by ZherebcovSergey** [Mangopay/mangopay2-php-sdk#136]
I use this example [mangopay2-php-sdk](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/non_js.php)

I create mango user (natural) and get it's ID
Then, according to [docs.mangopay](https://docs.mangopay.com/endpoints/v2.01/cards#e177_the-card-registration-object)
 
**Steps**

1. Send the request

I send the REQUEST 
```
$CardRegistration = new \MangoPay\CardRegistration();
$CardRegistration->UserId = 17721559; (my created user)
$CardRegistration->Currency = "GBP";
```
2. And I get response from Mango, such
![screen shot 2016-11-18 at 11 54 23 am](https://cloud.githubusercontent.com/assets/5315160/20425995/cff15050-ad85-11e6-9c53-2f2743755d6d.png)

3. On step 3 `Send card details`

Then I  send to the tokenization server the fields, according to example [mangopay2-php-sdk](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/non_js.php) , values I get from response on step 2 + card values (from [test visa cards](https://docs.mangopay.com/guide/testing-payments) )

```
<form action="https://homologation-webpayment.payline.com/webpayment/getToken" method="post">
    <input type="hidden" name="data" value="XBDYiG8w9PrylPS01KmupUyK93RrrOlbPFPIzpaLSpPXvZph51NOKNEOFkLNjosd7qGR3aNxrLUiPbx-Z--VxQ" />
    <input type="hidden" name="accessKeyRef" value="1X0m87dmM2LiwFgxPLBJ" />
    <input type="hidden" name="returnURL" value="https://api-test.taplend.com/mangopay/card/registration/complete/216" />

    <label for="cardNumber">Card Number</label>
    <input type="text" name="cardNumber" value="4706750000000009" />
    <div class="clear"></div>

    <label for="cardExpirationDate">Expiration Date</label>
    <input type="text" name="cardExpirationDate" value="0918" />
    <div class="clear"></div>

    <label for="cardCvx">CVV</label>
    <input type="text" name="cardCvx" value="123" />
    <div class="clear"></div>

    <input type="submit" value="Pay" />
</form>
```

But, response is `errorCode=09101` and I  have no answer to the "returnURL" specified by me. Do Mangopay will send data to it (Post request from Mnagopay with data=bla bla bla)? Or how? I wrote to support@mangopay.com but have not received a clear answer + the response will be faster here. Thanks.

**Comment by ZherebcovSergey** [comment]
I forgot to add that using a sanbox account

**Comment by hobailey** [comment]
Hey, are you using [the example](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/non_js.php) _exactly_ as it is, or have you made some changes?

**Comment by ZherebcovSergey** [comment]
It's Laravel interpretation of code example
```
$mangoPayApi = new \MangoPay\MangoPayApi();
$mangoPayApi->Config->ClientId = 'sdk-unit-tests';
$mangoPayApi->Config->ClientPassword = 'cqFfFrWfCcb7UadHNxx2C9Lo6Djw8ZduLi7J9USTmu8bhxxpju';
$mangoPayApi->Config->TemporaryFolder = storage_path()."/mangopay/sandbox/";

$user = new UserNatural();
$user->FirstName = 'John';
$user->LastName = 'Smith';
$user->Email = 'email@domain.com';
$user->Birthday = time();
$user->Nationality = 'GB';
$user->CountryOfResidence = 'GB';
$user->Occupation = "programmer";
$user->IncomeRange = 3;
$createdUser = $mangoPayApi->Users->Create($user);
// register card
$cardRegister = new \MangoPay\CardRegistration();
$cardRegister->UserId = $createdUser->Id;
$cardRegister->Currency = "GBP";
$cardRegister->CardType = 'CB_VISA_MASTERCARD';
$createdCardRegister = $mangoPayApi->CardRegistrations->Create($cardRegister);
        
$cardRegistrationUrl = $createdCardRegister->CardRegistrationURL;
$preregistrationData = $createdCardRegister->PreregistrationData;
$accessKey = $createdCardRegister->AccessKey;
$returnUrl = env('API_URL') . '/mangopay/card/registration/complete/2';
$pan = $requestData['pan'];
$expiry = $requestData['expiry'];
$cvc = $requestData['cvc'];

return view('mangopay.add_card', compact(
                                 'preregistrationData', 'accessKey',
                                 'cardRegistrationUrl', 'pan', 'expiry', 'cvc', 'returnUrl'));
```
And I get this form 
![screen shot 2016-11-18 at 3 51 28 pm](https://cloud.githubusercontent.com/assets/5315160/20432255/eedb0968-ada6-11e6-9b59-eb9282ec498d.png)

And when i send it from `html-render` or throw Postman as params, second screen , there is no response on `returnUrl`(I logged incoming requests to this URL). And response for posting form is  `errorCode=09101`

![screen shot 2016-11-18 at 3 54 22 pm](https://cloud.githubusercontent.com/assets/5315160/20432354/5f3a50ce-ada7-11e6-8ecd-e91c823f9899.png)

What I doing wrong? I don't understand...

**Comment by hobailey** [comment]
Hmm, and if you try with no `ReturnURL` at all (just remove this field) do you still have the problem?

**Comment by hobailey** [comment]
And also, when you do the Postman POST, could you try setting it to "www-form-urlencoded" instead of "form-data"?

**Comment by ZherebcovSergey** [comment]
Works, without `returnURL`... Maybe we should remove it from the example?

![screen shot 2016-11-18 at 4 25 30 pm](https://cloud.githubusercontent.com/assets/5315160/20433308/a76afc28-adab-11e6-96ed-0ad005f37fbd.png)

**Comment by ZherebcovSergey** [comment]
With it and "www-form-urlencoded" , there is no response on form and on that URL

**Comment by hobailey** [comment]
Ah, that's why - so it's content type that wasn't right and should indeed be "application/x-www-form-urlencoded". The reason for you not getting a response is simply because your [`ReturnURL`](https://api-test.taplend.com/mangopay/card/registration/complete/2) doesn't return any content :-)

**Comment by kamdjouduplex** [comment]
Hello there,
I know this is a close issue my problem is at the coding level not with the MANGOPAY API,
I am using Laravel too, and I am stock here:
- How do you get the response from this form post on laravel 5.5 ?
`
<form action="{{ $createdCardRegister->CardRegistrationURL }}" method="post">
		    	{{ csrf_field() }}
		    	<input type="hidden" id="data" name="data" 
		    	value="{{$createdCardRegister->PreregistrationData}}" />
		    	<input type="hidden" id="accessKeyRef" name="accessKeyRef" 
		    	value="{{$createdCardRegister->AccessKey}}" />

		        <div class="form-group">
		        	<label for="cardNumber">Card Number</label>
		        	<div class="input-group">
		        		<div class="input-group-addon">
		        		    <i class="livicon" data-name="mail" data-size="18" data-c="#000" data-hc="#000" data-loop="true"></i>
		        		</div>
		        		<input class="form-control" type="text" id="cardNumber" name="cardNumber" value="" />
		        	</div>
		        </div>
				<div class="form-group">
		        	<label for="cardExpirationDate">Expiration Date</label>
		        	<div class="input-group">
		        		<div class="input-group-addon">
		        		    <i class="livicon" data-name="mail" data-size="18" data-c="#000" data-hc="#000" data-loop="true"></i>
		        		</div>
		        		<input class="form-control" type="text" id="cardExpirationDate" name="cardExpirationDate" value="" />
		        	</div>
		        </div>
				
				<div class="form-group">
					<label for="cardCvx">CVV</label>
					<div class="input-group">
						<div class="input-group-addon">
							<i class="livicon" data-name="mail" data-size="18" data-c="#000" data-hc="#000" data-loop="true"></i>
						</div>
						<input class="form-control" type="text" id="cardCvx" name="cardCvx" value="" />
					</div>
				</div>

		        <button  class="btn btn-block btn-primary" type="submit" >Add Your Card</button>

</form>
`
