### ISSUE TITLE
Problems with "payments with 3D Secure"

### ISSUE THREAD

**Issue by ZherebcovSergey** [Mangopay/mangopay2-php-sdk#137]
> sandbox account

Hello! With the help of your api I created user, purse, tied BIC. At the stage of creating the payment card, I use one of the cards (https://docs.mangopay.com/guide/testing-payments) for "payments with 3D Secure". Payment card created successfully and now has the status of "VALIDATED". But when I try to make the payment (in the amount of more than 100 €), it does not come "SecureModeReturnURL". Payment takes place as a standard ... The reason may be what? It may need some special parameter in the API?

```
// execution type as DIRECT
$payIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
$payIn->ExecutionDetails->SecureModeReturnURL = 'http://my_return_URL';
```

**Comment by hobailey** [comment]
Hi, I'm not quite sure I entirely understand the problem - you're saying that you want to do a 3DS payment, but in the API response `SecureModeNeed` = _false_ and you were expecting _true_?

**Comment by ZherebcovSergey** [comment]
> API response SecureModeNeed = false and you were expecting true

exactly

**Comment by ZherebcovSergey** [comment]
```
SecureModeRedirectURL":null,
"SecureModeNeeded":false
```

**Comment by hobailey** [comment]
And are you using a specific 3DS card from [this list](https://docs.mangopay.com/guide/testing-payments)?

**Comment by ZherebcovSergey** [comment]
Yes, I tried both

3569990000000132
3569990000000157

**Comment by hobailey** [comment]
Could you post the code you're using for the payin please?

**Comment by ZherebcovSergey** [comment]
```
use MangoPay\Money;
use MangoPay\PayIn;
use MangoPay\PayInExecutionDetailsDirect;
use MangoPay\PayInPaymentDetailsCard;
use MangoPay\MangoPayApi;
```

> in my class method

```
$mangoPayApi = new \MangoPay\MangoPayApi();

$payIn = new PayIn();
$payIn->CreditedWalletId = $myWalletID;
$payIn->AuthorId = $myID;
$payIn->DebitedFunds = new Money();
$payIn->DebitedFunds->Amount = $amount;
$payIn->DebitedFunds->Currency = 'GBP';
$payIn->Fees = new Money();
$payIn->Fees->Amount = 0;
$payIn->Fees->Currency = 'GBP';
// payment type as CARD
$payIn->PaymentDetails = new PayInPaymentDetailsCard();
$payIn->PaymentDetails->CardId = $myCardID;
// execution type as DIRECT
$payIn->ExecutionDetails = new PayInExecutionDetailsDirect();
$payIn->ExecutionDetails->SecureModeReturnURL = "some my return URL";

$mangoPayApi->PayIns->Create($payIn);
```

**Comment by hobailey** [comment]
OK, thanks. Could I have one of your payin IDs please? And can you confirm the amount you're putting for `$payIn->DebitedFunds->Amount` is definitely > 10000 (eg in cents, and more than 100€)?
