### ISSUE TITLE
failed to open stream: Permission denied 

### ISSUE THREAD

**Issue by jyyyy** [Mangopay/mangopay2-php-sdk#139]
hello 

my error is 
Warning: file_put_contents(/tmp//MangoPaySdkStorage.tmp.php): failed to open stream: Permission denied
in vendor/mangopay/php-sdk-v2/MangoPay/Libraries/DefaultStorageStrategy.php at line 49   -

**Comment by mickaelpois** [comment]
Hello @jyyyy !
Could you tell me a little bit more about your issue?
What method are you trying to use / action are you going to do?
Is your client account well created?

Thanks for your feedback, I hope I can help you ASAP !
