### ISSUE TITLE
Provide middleware interface

### ISSUE THREAD

**Issue by harlynx** [Mangopay/mangopay2-php-sdk#140]
Digging through the source I was not able to find a way to add middleware to the API class. I want to implement a rate limiter which would listen to each API call and interfere if a user reached a certain threshold, but this is not easily possible since you divided the API into subclasses for each endpoint, e.g. `Cards` -> `ApiCards` which inherits from `Libraries\ApiBase`. I would also use the middleware interface to attach a logger so the code does not get convoluted by countless $api->getLogger()->x() calls inside my service classes.

**Comment by mickaelpois** [comment]
Hello @harlynx,
Thanks for your feedback !
What is your own feeling about that, what kind of implementation could help you the most?

About rate limiting, don't you have any custom header values provided by our SDK?
If not, it seems that is an issue that we could fix ASAP, helping you a little bit !

**Comment by harlynx** [comment]
Hello @mickaelpois 

It would be nice to have something like [this](https://github.com/php-fig/fig-standards/blob/master/proposed/http-middleware/middleware.md), just in the context of the MangoPay API. It is basically a chain of responsibility that takes a request / response, does something with it, and then passes it to the next chain element or throws on fatal errors. 

In the practical sense, if we wanted to make an API call, the SDK would first let all the middlewares or 'listeners' process the request before actually sending it to the MangoPay server. The same goes for the responses from the MangoPay server, before they are passed back to the service which made the request.
Right now it is impossible to extend the SDK Libraries that way because of how the SDK is structured (inheritance vs composition).

Quick examples of how we currently do it:

On requests:
```php
// other error checking
// ...
if (!$this->limitSvc->check($user, 'mangopay')) {
    return ServiceResult::failure(/* too many mango pay requests*/);
}
// all ok, we can do the api call
```
On responses:
```php
// api returned the wallet object for instance but it has an error
// or the SDK threw an exception
$this->api->getLogger()->error(/* the wallet error */);
```
Result: Try MangoPayException try-catch blocks everywhere and dozens of logger calls inside the service classes. 

These things could be done by a dedicated middleware at the core of the SDK:

```php
// initialization code
$this->api->attachMiddlewares([$rateLimiter, $logger, $statistics, /*other*/]);
```
Another way of doing this would be to have an event system for requests and responses, but this is essentially the same and would have to be framework agnostic.

**Comment by mickaelpois** [comment]
Hello @harlynx 

Thanks for this very interesting and detailled example.
I can't provide you any agenda about your proposal as it is not a feature that is strongly asked and prio, but be sure that we keep that in mind for analysis !
