### ISSUE TITLE
PayIn by direct debit with a mandate - FAILED

### ISSUE THREAD

**Issue by raBlanc** [Mangopay/mangopay2-php-sdk#143]
Hello!

Our tests are failing because the PSP is throwing an error on Sandbox mode when creating payment Direct PayIn with mandate, this is the response body:

Response object: stdClass Object
(
    [Id] => 20988259
    [CreationDate] => 1487153356
    [AuthorId] => 20729052
    [CreditedUserId] => 20728636
    [Status] => FAILED
    [ExecutionDate] => 
    [Type] => PAYIN
    [Nature] => REGULAR
    [CreditedWalletId] => 20728637
    [DebitedWalletId] => 
    [CreditedFunds] => stdClass Object
        (
            [Currency] => EUR
            [Amount] => 290
        )

    [DebitedFunds] => stdClass Object
        (
            [Currency] => EUR
            [Amount] => 300
        )

    [Fees] => stdClass Object
        (
            [Currency] => EUR
            [Amount] => 10
        )

    [ResultCode] => 009199
    [ResultMessage] => PSP technical error
    [PaymentType] => DIRECT_DEBIT
    [ExecutionType] => DIRECT
    [Tag] => 
    [MandateId] => 20931473
    [StatementDescriptor] => PrelÃ¨vement sur le compte de Accu2
)

**Comment by hobailey** [comment]
Hi @raBlanc, the `StatementDescriptor` can only accept alphanumeric characters, and it looks like this might not be the case with your example.
