### ISSUE TITLE
How to list user's cards?

### ISSUE THREAD

**Issue by abalit** [Mangopay/mangopay2-php-sdk#144]
Hi there,

MangoPay technical support addressed me to this GitHub forum.
I have fully implemented the platform in PHP but I have only one remaining issue which I cannot figure out how to achieve:

I cannot manage to implement the USER'S CARDS LIST, in the PHP examples it seems that I need to create a card registration to list all cards; but in the documentation (https://docs.mangopay.com/endpoints/v2.01/cards#e886_list-cards-for-a-user) I cannot figure out how to do it.

Any help will be welcome.

Thank you in advance!

**Comment by iammichiel** [comment]
You don't need to create a token to access the users card list. 
When using this library, you can call it quite simply :

```
$mango = new \MangoPay\MangoPayApi();
$cards = $mango->Users->GetCards($userId)
```

**Comment by abalit** [comment]
thank you
