### ISSUE TITLE
Why does mangopay2-php-sdk need mangopay2-php-sdk as a dependency? 

### ISSUE THREAD

**Issue by nicosomb** [Mangopay/mangopay2-php-sdk#145]
Hello, 

In your composer.json, you have this line `"mangopay/php-sdk-v2": "^2.3"` in the require section. 
https://github.com/Mangopay/mangopay2-php-sdk/blob/master/composer.json#L12

I want to know why there is this (useless) line.

**Comment by mickaelpois** [comment]
Hi @nicosomb and sorry for this (very late) answer !
It was a mistake, and it has been fixed, thanks for pointing this out.
