### ISSUE TITLE
secureMode  change from FORCE To DEFAULT error

### ISSUE THREAD

**Issue by anbwar** [Mangopay/mangopay2-php-sdk#153]
Hi Everyone,
Recently , i have tried to change my secureMode on Creating CardPreAuthorization , from "FORCE" to DEFAULT, but i got this  400 error in production client payement 
"the card registration has already been processed" 
You must know that this is the first time this card has processed to a payment via my website.
Does anyone have idea ?

Thankyou

**Comment by mickaelpois** [comment]
Hello @anbwar !

This error message ("The card registration has already been processed") is sent when you are trying to register a card (even if it is a "new" card on your system) with a same Card token twice (token is generated thanks to POST /CardRegistrations/ endpoint).
In my opinion, it is not related to your PreAuthorization.

Could you tell me exactly how you have register this card?

As a reminder:
https://docs.mangopay.com/endpoints/v2.01/cards#e177_the-card-registration-object

Thanks for your answer to come, I hope I could be helpful !

Mickaël

**Comment by anbwar** [comment]
Below my source code of process.php file,
But i got the ("The card registration has already been processed") error only when i change secureMode to "DEFAULT" or when i disable it or comment it !
Otherwise the card preauthorisation works fine with "FORCE" 3D secureMode

try {
		// update register card with registration data from Payline service
		$cardRegister = $mangoPayApi->CardRegistrations->Get($_SESSION['payment']['cardRegisterId']);
		$cardRegister->RegistrationData = isset($_GET['data']) ? 'data=' . $_GET['data'] : 'errorCode=' . $_GET['errorCode'];
		$updatedCardRegister = $mangoPayApi->CardRegistrations->Update($cardRegister);

		// Erreur carte
		if($updatedCardRegister->Status != \MangoPay\CardRegistrationStatus::Validated || !isset($updatedCardRegister->CardId)) {
			if(isset($_SESSION['giftcard'])) 	header2('Location: carte-cadeau-paiement.html?error');
			elseif(isset($_SESSION['meeting']))	header2('Location: services-paiement.html?error');
			else 								header2('Location: /');
		}

		$secureModeReturnURL = 'http' . ( isset($_SERVER['HTTPS']) ? 's' : '' ) . '://' . $_SERVER['HTTP_HOST'];
		$secureModeReturnURL .= substr($_SERVER['REQUEST_URI'], 0, strripos($_SERVER['REQUEST_URI'], '/') + 1);
		$secureModeReturnURL .= 'finish.php';

		$CardPreAuthorization = new \MangoPay\CardPreAuthorization();
		$CardPreAuthorization->AuthorId = $updatedCardRegister->UserId;
		$CardPreAuthorization->DebitedFunds = new \MangoPay\Money();
		$CardPreAuthorization->DebitedFunds->Currency = "EUR";
		$CardPreAuthorization->DebitedFunds->Amount = $_SESSION['payment']['amount'] * 100;
		$CardPreAuthorization->SecureMode = "FORCE";
		$CardPreAuthorization->CardId = $updatedCardRegister->CardId;
		$CardPreAuthorization->SecureModeReturnURL = $secureModeReturnURL;
		$result = $mangoPayApi->CardPreAuthorizations->Create($CardPreAuthorization);
		$pre_id = $result->Id;


		header('Location: '.$result->SecureModeRedirectURL);


	} catch (\MangoPay\Libraries\ResponseException $e) {

		print '<div style="color: red;">'
			.'\MangoPay\ResponseException: Code: '
			. $e->getCode() . '<br/>Message: ' . $e->getMessage()
			.'<br/><br/>Details: '; print_r($e->GetErrorDetails())
		.'</div>';

		$_SESSION['payment']['updatedCardRegister'] = $updatedCardRegister;
	}



Thank you for your quickly response

**Comment by mickaelpois** [comment]
@anbwar,

So, into your "try" block, you are:
1. updating a card registration object (you have create outside this block?) with client card data
2. check that your card registration is OK
3. Try to do a PreAuth with this card

I just want to be sure that before step 1, your card registration object is created as follows:
```
$cardRegister = new \MangoPay\CardRegistration();
$cardRegister->UserId = $_SESSION["Foo"]["FooUserID"];
$cardRegister->Currency = "EUR";
$result = $mangoPayApi->CardRegistrations->Create($cardRegister);
```

Maybe when you have tried to do a second PreAuth with "FORCE" value, you have tried to use an old card registration object, without having this part of code runned again. As a consequence, error message happend before at step 2, before step 3 and PreAuth process.

I just tried to do a card registration in Sandbox environment and a card pre-auth transaction: successful.

**Comment by anbwar** [comment]
.
.
....
$createdUser = $mangoPayApi->Users->Create($user);

	// register card
	$cardRegister	 		= new \MangoPay\CardRegistration();
	$cardRegister->UserId 	= $createdUser->Id;
	$cardRegister->Currency = $_SESSION['payment']['currency'];
	$cardRegister->CardType = $_SESSION['payment']['cardType'];
	
	$createdCardRegister = $mangoPayApi->CardRegistrations->Create($cardRegister);
	
	$_SESSION['payment']['cardRegisterId'] = $createdCardRegister->Id;

	// build the return URL to capture token response
	$returnUrl = 'http' . ( isset($_SERVER['HTTPS']) ? 's' : '' ) . '://' . $_SERVER['HTTP_HOST'];
	$returnUrl .= substr($_SERVER['REQUEST_URI'], 0, strripos($_SERVER['REQUEST_URI'], '/') + 1);
	$returnUrl .= 'process.php';

	include 'payment.php';


You can see that before step1 we create the card regitration object.
After some tests : For more details about the problem, The preauthorisation object is successfully created , and i can pass to the payin/payout but this error appear to client when we only change the secureMode from FORCE to DEFAULT ; i think that this due to the catch excepton error but i dont know from what.

Thank you for your time 👍

**Comment by mickaelpois** [comment]
Hello @anbwar,

We will try to give you an answer ASAP.

**Comment by anbwar** [comment]
ok Thanks

**Comment by hobailey** [comment]
Hey @anbwar, when you switch the `SecureMode` from DEFAULT to FORCE, do you just refresh the page of process.php, or do you rerun the whole workflow again?
Because the error "The card registration has already been processed" is only linked to the card registration process, and it is completely unrelated to the preauthorization (and hence `SecureMode`).

Also, mini (unrelated) tip - I think the `!isset($updatedCardRegister->CardId)` should actually be `empty($updatedCardRegister->CardId)` because it could be set, but _null_ :-)

**Comment by anbwar** [comment]
I think this is the fault , i need to use empty instead of isset.
Then now, i dont want to change the secure mode.

Thank you for the help.
