### ISSUE TITLE
CardPreAuthorization Payin -  Call to undefined method stdClass::GetReadOnlyProperties() 

### ISSUE THREAD

**Issue by KLevezier** [Mangopay/mangopay2-php-sdk#154]
Hello,
I m trying to create CardPreAuthorization payin but i got this fatal error : 

> PHP Fatal error:  Call to undefined method stdClass::GetReadOnlyProperties() in .../MangoPay/Libraries/ApiBase.php on line 398

Bellow my source code : 

```
$payIn = new \MangoPay\PayIn();
$payIn->CreditedWalletId = $id_wallet_global;  
$payIn->AuthorId = $id_user;
$payIn->PaymentType = \MangoPay\PayInPaymentType::Card;
$PayIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsPreAuthorized();
$payIn->PaymentDetails->PreauthorizationId = $this->pre_autorisation->Id;
	
$payIn->DebitedFunds = new \MangoPay\Money();
$payIn->DebitedFunds->Currency = "EUR";
$payIn->DebitedFunds->Amount = $amount*100;
			 
$payIn->Fees = new MangoPay\Money();
$payIn->Fees->Currency = "EUR";
$payIn->Fees->Amount = $amount*100;
		
$payIn->ExecutionType = \MangoPay\PayInExecutionType::Direct;
$payIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
			
$payIn = $api->PayIns->Create($payIn);
```

Thanks for your answer to come

Kevin

**Comment by hobailey** [comment]
Hey @KLevezier, so there's a couple of problems - the main one being:
```
$PayIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsPreAuthorized();
```
You need to use a lowercase "p" for `$PayIn` to match the existing `$payIn` variable. Secondly (although not code related as such), you can not have the DebitedFunds->Amount = Fees->Amount (therefore you need to rework the `$amount` usage.
