### ISSUE TITLE
Direct Debit Pay In

### ISSUE THREAD

**Issue by Daneel-Olivaw** [Mangopay/mangopay2-php-sdk#157]
Hi

I'm trying to do a Direct Debit Pay In for a SEPA payment (I have the Mandate submited already)

I couldn't find an example for this kind of payment (At the Mangopay Docs Webpage the Code is unavaliable) https://docs.mangopay.com/endpoints/v2.01/payins#e282_create-a-direct-debit-direct-payin

I get this error:

`MangoPay\Libraries\Exception Object
(
    [message:protected] => Payment is not defined or it is not object type
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => D:\home\site\wwwroot\vendor\mangopay\php-sdk-v2\MangoPay\ApiPayIns.php
    [line:protected] => 59
    [trace:Exception:private] => Array`

**Comment by hobailey** [comment]
Hey @Daneel-Olivaw, could you please show us the relevant bit of your code so we can help identify the problem?

**Comment by iammichiel** [comment]
Quite similar to the classic Payin process. Here is an example below : 

```
$payIn = new PayIn();
$payIn->Tag = $tag;
$payIn->CreditedWalletId = $creditedWalletId;
$payIn->AuthorId = $authorId;

$payIn->DebitedFunds = new Money();
$payIn->DebitedFunds->Amount = $amount;
$payIn->DebitedFunds->Currency = CurrencyIso::EUR;

$payIn->Fees = new Money();
$payIn->Fees->Amount = $fees;
$payIn->Fees->Currency = CurrencyIso::EUR;

$payIn->PaymentDetails = new PayInPaymentDetailsDirectDebit();
$payIn->PaymentDetails->MandateId = $mandateId;
$payIn->PaymentType = PayInPaymentType::DirectDebit;

$payIn->ExecutionType = PayInExecutionType::Direct;
$payIn->ExecutionDetails = new PayInExecutionDetailsDirect();
```

**Comment by mickaelpois** [comment]
Thanks for your example @iammichiel !
