### ISSUE TITLE
customisation of PayInWEB with CSS stylesheat

### ISSUE THREAD

**Issue by Doctys** [Mangopay/mangopay2-php-sdk#163]
I have a file : https://www.mysite/webpayin_style.css  following all 
where do I upload it ?
here:   ->ExecutionDetails->TemplateURLOptions->PAYLINE = "" ?
but then I get the PAYLINE standard page in the iFrame of my ReturnURL !!!
any idea on how to fix it and get a customised PayinWeb page ?

**Comment by mickaelpois** [comment]
Hello @Doctys,

Have you tried to apply every advices that are given on this documentation page?
https://docs.mangopay.com/guide/customising-the-design

Please check that everything you've done is perfectly in compliance with that.
If we want some help, please give us a snippet of your CSS code please !

Regards, 

Mickaël
