### ISSUE TITLE
SDK requires a Temporary Folder 

### ISSUE THREAD

**Issue by casimir25** [Mangopay/mangopay2-php-sdk#172]
The PHP SDK requires a Temporary Folder : 
$api->Config->TemporaryFolder = '/some/path/';

I am using Heroku Paas on which there is no possiblity to have persistency on the file system (storing file in a temp folder is only ok for some minutes as it get recycled).
I can use Amazon S3 to save my files, but how can I specify this for your API ?
Can I perhaps use an URL ?

thanks

**Comment by paulhristea** [comment]
Hello there, @casimir25!

The temporary folder is used for the sole purpose of creating files to store OAuth tokens (for API call authorization). This is the default behaviour (see https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/Libraries/DefaultStorageStrategy.php).

However, the SDK allows you to define your own storage strategy for OAuth tokens, by calling the `RegisterCustomStorageStrategy` method available on the `OAuthTokenManager` object accessible directly through the `MangoPayApi` object. Simply create a class which abides by the definition stated in the `IStorageStrategy` interface and pass an object of that class to the mentioned method.

You could either use in-memory storing (something like the `MockStorageStrategy` used in tests - see: https://github.com/Mangopay/mangopay2-php-sdk/blob/master/tests/mocks/mockStorageStrategy.php), or implement your own functionality to make use of your Amazon-provided services.

Thanks for your interest, and please do not hesitate to inquire further!

**Comment by jonnyleigh** [comment]
My app runs on a single server so in-memory approach would work for me, and I'm getting occasional error with writing to file.
Could you give me a little more detail on how to implement the in-memory approach.  Currently I use the following to set up the SDK:

```
    require_once 'psr/LogLevel.php';
    require_once 'psr/LoggerInterface.php';
    require_once 'psr/AbstractLogger.php';
    require_once 'psr/NullLogger.php';
    require_once 'mangopay_api/Autoloader.php';
    $api = new MangoPay\MangoPayApi();
    $api->Config->ClientId = '########';
    $api->Config->ClientPassword = '#################';
    $api->Config->TemporaryFolder = 'mangotemp';
```

What do  need to do with $api->Config to use memory rather than file based?

I'm getting occasional error, see issue #171 

Thanks,

**Comment by hobailey** [comment]
Hey @jonnyleigh, have a look at [this example](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/workflow/inc/config.php) - you basically need to include the mock storage file that Paul mentioned (or make your own), remove the temporary file config setting and replace it with:
`$mangoPayApi->OAuthTokenManager->RegisterCustomStorageStrategy(new \MangoPay\DemoWorkflow\MockStorageStrategy());`

**Comment by jonnyleigh** [comment]
Thanks @hobailey, this is working for me.
