### ISSUE TITLE
Unable to 'desactivate' a bank account

### ISSUE THREAD

**Issue by wiseKid** [Mangopay/mangopay2-php-sdk#180]
I followed the recommendations of your api documentation.
But when I'm trying to 'desactivate' a bank account, I'm getting a Warning and a Fatal Error on _MangoPay/Libraries/ApiBase.php_ file.

Please tell me what I'm doing wrong.

**Input:**
```
$bank_account = new ExternalSystemBankAccount();
$bank_account->Id = $bank_account_id;
$bank_account->Active = false;

$result = $this->MangoApi->Users->UpdateBankAccount($user_id, $bank_account);
```

**Output**:
`PHP Warning:  get_object_vars() expects parameter 1 to be object, null given in .../vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php on line 398
PHP Fatal error:  Uncaught Error: Call to a member function GetReadOnlyProperties() on null in .../vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php:399`

**Comment by mickaelpois** [comment]
Hi @wiseKid,

Could you explain what's on your ExternalSystemBankAccount object? I can't remember this is an object from our SDK / API.

As a reminder, if you want to update an existing bankaccount, you have to get it first thanks to its ID (and not only put its ID on a new object).
Then, put a false value on this bankaccount object, and update it.

If you could provide me some extra details about the way you try to update it, feel free to answer here.
I'll try to help you as fast as I can.

Mickaël

**Comment by paulhristea** [comment]
Here you can find some fresh code which tests exactly the functionality that you are targeting:
https://github.com/Mangopay/mangopay2-php-sdk/pull/181/files#diff-1711d9646049db3731a911f79fb57c48R250

Please note that the `$this->getJohn()` and `$this->getJohnsBankAccount()` methods both launch API calls through the `MangoPayApi->Users` service class to retrieve the data.
