### ISSUE TITLE
Help with updating user

### ISSUE THREAD

**Issue by jonnyleigh** [Mangopay/mangopay2-php-sdk#185]
Please can you show me some working sample code for updating a user using the PHP SDK?
My code looks like this and it isn't updating the user successfully.  No error message, but the changes to Company Name are not reflecting in $result:

```
        $mangopay_userid = $myPsychDetails[mangopay_userid];
        print_r($_POST); //for debugging
        
        //update existing user
        try
        {
            $User = $api->Users->Get($mangopay_userid);
            echo(json_encode($User)); //for debugging
            
            if($_POST[listing_type] == 'Company')
            {
                $User->Name = $_POST[company_name];
                $User->LegalPersonType = $_POST[organisation_type];
                $User->Email = $_POST[legal_email];
                $User->LegalRepresentativeFirstName = $_POST[legal_firstname];
                $User->LegalRepresentativeLastName = $_POST[legal_lastname];
                $User->LegalRepresentativeBirthday = strtotime($_POST[legal_dob]);
                $User->LegalRepresentativeNationality = $_POST[legal_nationality];
                $User->LegalRepresentativeCountryOfResidence = $_POST[legal_country];
                
            }
            else
            {
                $User->Email = $_POST[natural_email];
                $User->FirstName = $_POST[natural_firstname];
                $User->LastName = $_POST[natural_lastname];
                $User->Birthday = strtotime($_POST[natural_dob]);
                $User->Nationality = $_POST[natural_nationality];
                $User->CountryOfResidence = $_POST[natural_country];
                
            }

            $result = $api->Users->Update($User);

            echo(json_encode($result)); //for debugging
        }
```

print_r($_POST);
`Array ( [user_id] => 467 [company_name] => Company Name2 [organisation_type] => BUSINESS [legal_firstname] => Jonny [legal_lastname] => Leigh [legal_email] => jonny@jonnyleigh.co.uk [legal_dob] => 2015-02-01 [legal_nationality] => GB [legal_country] => GB [natural_firstname] => Jonny [natural_lastname] => Leigh [natural_email] => jonny@jonnyleigh.co.uk [natural_dob] => 2015-02-01 [natural_nationality] => GB [natural_country] => GB )`

echo(json_encode($User));
`{"Name":"Company Name","LegalPersonType":"BUSINESS","HeadquartersAddress":{"AddressLine1":null,"AddressLine2":null,"City":null,"Region":null,"PostalCode":null,"Country":null},"LegalRepresentativeFirstName":"Jonny","LegalRepresentativeLastName":"Leigh","LegalRepresentativeAddress":{"AddressLine1":null,"AddressLine2":null,"City":null,"Region":null,"PostalCode":null,"Country":null},"LegalRepresentativeEmail":null,"LegalRepresentativeBirthday":1422770400,"LegalRepresentativeNationality":"GB","LegalRepresentativeCountryOfResidence":"GB","ProofOfIdentity":null,"Statute":null,"ProofOfRegistration":null,"ShareholderDeclaration":null,"PersonType":"LEGAL","Email":"jonny@jonnyleigh.co.uk","KYCLevel":"LIGHT","Id":"33100580","Tag":null,"CreationDate":1504908607}
`

 echo(json_encode($result));
`{"Name":"Company Name","LegalPersonType":"BUSINESS","HeadquartersAddress":{"AddressLine1":null,"AddressLine2":null,"City":null,"Region":null,"PostalCode":null,"Country":null},"LegalRepresentativeFirstName":"Jonny","LegalRepresentativeLastName":"Leigh","LegalRepresentativeAddress":{"AddressLine1":null,"AddressLine2":null,"City":null,"Region":null,"PostalCode":null,"Country":null},"LegalRepresentativeEmail":null,"LegalRepresentativeBirthday":1422770400,"LegalRepresentativeNationality":"GB","LegalRepresentativeCountryOfResidence":"GB","ProofOfIdentity":null,"Statute":null,"ProofOfRegistration":null,"ShareholderDeclaration":null,"PersonType":"LEGAL","Email":"jonny@jonnyleigh.co.uk","KYCLevel":"LIGHT","Id":"33100580","Tag":null,"CreationDate":1504908607}`

**Comment by jonnyleigh** [comment]
@paulhristea

**Comment by paulhristea** [comment]
Hi again @jonnyleigh!

I just ran some tests, retrieved a legal user entity by id and, after changing the `$Name` property, was able to see the change reflected in the response. I think the issue here has to do with the way that the new name is being retrieved from the `$_POST` variable.

In your examples, I can see that the result of `json_encode($User)` has the field `"Name":"Company Name"`, but in the `$_POST` variable there is `[company_name] => Company Name2`. I assume that the call to `json_encode($User)` is made after updating the user data, so the problem should be where the new value is being retrieved from the `$_POST` variable.

Try adding quote characters to the `$_POST` field names, I think that's the way it's supposed to be done:

Instead of
`$User->Name = $_POST[company_name];
$User->Email = $_POST[email];
...`

Try
`$User->Name = $_POST['company_name'];
$User->Email = $_POST['email'];
...`

**Comment by paulhristea** [comment]
I just realised that the `json_encode($User)` call is done before updating the user's data. Could you please do that call again after updating it and put the result here as well?

Thanks!

**Comment by jonnyleigh** [comment]
Hi @paulhristea 
Thanks for getting back to me on a Saturday.

Here is my updated code with additional echo(json_encode) as requested.  Also I used the quoted string indexer as you suggested:
```php
         print_r($_POST); //for debugging
        
        //update existing user
        try
        {
            $User = $api->Users->Get($mangopay_userid);
            echo(json_encode($User)); //for debugging
            
            if($_POST[listing_type] == 'Company')
            {
                $User->Name = $_POST["company_name"];
                $User->LegalPersonType = $_POST["organisation_type"];
                $User->Email = $_POST["legal_email"];
                $User->LegalRepresentativeFirstName = $_POST["legal_firstname"];
                $User->LegalRepresentativeLastName = $_POST["legal_lastname"];
                $User->LegalRepresentativeBirthday = strtotime($_POST["legal_dob"]);
                $User->LegalRepresentativeNationality = $_POST["legal_nationality"];
                $User->LegalRepresentativeCountryOfResidence = $_POST["legal_country"];
                
            }
            else
            {
                $User->Email = $_POST["natural_email"];
                $User->FirstName = $_POST["natural_firstname"];
                $User->LastName = $_POST["natural_lastname"];
                $User->Birthday = strtotime($_POST["natural_dob"]);
                $User->Nationality = $_POST["natural_nationality"];
                $User->CountryOfResidence = $_POST["natural_country"];
                
            }
            
            echo(json_encode($User)); //for debugging

            $result = $api->Users->Update($User);

            echo(json_encode($result)); //for debugging
```

And the output:
```
Array ( [user_id] => 467 [company_name] => NewCo [organisation_type] => BUSINESS [legal_firstname] => Jonny [legal_lastname] => Leigh [legal_email] => jonny@jonnyleigh.co.uk [legal_dob] => 2015-02-01 [legal_nationality] => GB [legal_country] => GB [natural_firstname] => Jonny [natural_lastname] => Leigh [natural_email] => jonny@jonnyleigh.co.uk [natural_dob] => 2015-02-01 [natural_nationality] => GB [natural_country] => GB ) 

{"Name":"Company Name","LegalPersonType":"BUSINESS","HeadquartersAddress":{"AddressLine1":null,"AddressLine2":null,"City":null,"Region":null,"PostalCode":null,"Country":null},"LegalRepresentativeFirstName":"Jonny","LegalRepresentativeLastName":"Leigh","LegalRepresentativeAddress":{"AddressLine1":null,"AddressLine2":null,"City":null,"Region":null,"PostalCode":null,"Country":null},"LegalRepresentativeEmail":null,"LegalRepresentativeBirthday":1422770400,"LegalRepresentativeNationality":"GB","LegalRepresentativeCountryOfResidence":"GB","ProofOfIdentity":null,"Statute":null,"ProofOfRegistration":null,"ShareholderDeclaration":null,"PersonType":"LEGAL","Email":"jonny@jonnyleigh.co.uk","KYCLevel":"LIGHT","Id":"33100580","Tag":null,"CreationDate":1504908607}


{"Name":"Company Name","LegalPersonType":"BUSINESS","HeadquartersAddress":{"AddressLine1":null,"AddressLine2":null,"City":null,"Region":null,"PostalCode":null,"Country":null},"LegalRepresentativeFirstName":"Jonny","LegalRepresentativeLastName":"Leigh","LegalRepresentativeAddress":{"AddressLine1":null,"AddressLine2":null,"City":null,"Region":null,"PostalCode":null,"Country":null},"LegalRepresentativeEmail":null,"LegalRepresentativeBirthday":1422770400,"LegalRepresentativeNationality":"GB","LegalRepresentativeCountryOfResidence":"GB","ProofOfIdentity":null,"Statute":null,"ProofOfRegistration":null,"ShareholderDeclaration":null,"PersonType":"LEGAL","Email":"jonny@jonnyleigh.co.uk","KYCLevel":"LIGHT","Id":"33100580","Tag":null,"CreationDate":1504908607,"FirstName":"Jonny","LastName":"Leigh","Birthday":1422770400,"Nationality":"GB","CountryOfResidence":"GB"}


{"Name":"Company Name","LegalPersonType":"BUSINESS","HeadquartersAddress":{"AddressLine1":null,"AddressLine2":null,"City":null,"Region":null,"PostalCode":null,"Country":null},"LegalRepresentativeFirstName":"Jonny","LegalRepresentativeLastName":"Leigh","LegalRepresentativeAddress":{"AddressLine1":null,"AddressLine2":null,"City":null,"Region":null,"PostalCode":null,"Country":null},"LegalRepresentativeEmail":null,"LegalRepresentativeBirthday":1422770400,"LegalRepresentativeNationality":"GB","LegalRepresentativeCountryOfResidence":"GB","ProofOfIdentity":null,"Statute":null,"ProofOfRegistration":null,"ShareholderDeclaration":null,"PersonType":"LEGAL","Email":"jonny@jonnyleigh.co.uk","KYCLevel":"LIGHT","Id":"33100580","Tag":null,"CreationDate":1504908607}
```

What you say about getting the value from the $_POST variable seems to make sense, if you have been able to make it work in your environment.  I'll keep on playing around and see if I can get anywhere, but do let me know if you have any thoughts.

Thanks,

**Comment by paulhristea** [comment]
Sure thing, my pleasure!

Well, you might as well just try the call without using the `$_POST` variable at all; just put new values in the `$User` entity (`$User->Name = "Company Name2"`) and launch the update request. If that doesn't return the user correctly updated, then we might have a problem.

**Comment by jonnyleigh** [comment]
@paulhristea I worked it out, totally my fault.
$_POST[listing_type] wasn't coming through properly so the IF statement was not able to determine if it was a natural or legal user.

PHP is a weakly typed language so I need to be more careful with my IF statements.

**Comment by paulhristea** [comment]
Haha, yes that's right I completely overlooked that point.
Alright, great! Anything else comes up, just whip up another issue.

See you around!

**Comment by paulhristea** [comment]
Now you mention it, does it work to get the `$_POST` data without using quotes around the tags?

**Comment by jonnyleigh** [comment]
Yes it does!
However it's not good practice (I just found out): [https://stackoverflow.com/questions/8276784/using-no-quotes-vs-single-quotes-vs-double-quotes-in-post-value](https://stackoverflow.com/questions/8276784/using-no-quotes-vs-single-quotes-vs-double-quotes-in-post-value)

I'm new to PHP...in case you haven't guessed :-)

**Comment by paulhristea** [comment]
So am I - in case _you_ haven't guessed!
