### ISSUE TITLE
GetMandatesForBankAccount wrong filter class object

### ISSUE THREAD

**Issue by thomas-blackbird** [Mangopay/mangopay2-php-sdk#191]
Hi,
In your sdk, the method GetMandatesForBankAccount require \MangoPay\FilterTransactions object in the phpdoc, but it seems that the only allowed filter object is \MangoPay\FilterBase. See in your documentation  at https://docs.mangopay.com/endpoints/v2.01/mandates#e236_list-a-bank-accounts-mandates

**Comment by paulhristea** [comment]
Hi @thomas-blackbird, sorry about the delayed response.

I looked into this, and I found that the reason for allowing a `FilterTransactions` object here is that the results actually can be filtered by the `Status` parameter. It is indeed a little 'dirty', and the documentation probably should be updated to reflect this.

Thanks for bringing this up!
