### ISSUE TITLE
Ressource not found when trying to create a card registration

### ISSUE THREAD

**Issue by tarekfellah** [Mangopay/mangopay2-php-sdk#192]
Hi,
I'm trying to register a new card with this code
 `private function mangopayCardRegistration() {
        try {

            $obj_cardregister = new MangoPay\CardRegistration();
            $obj_cardregister->UserId = $this->buyer_mangopay_userid;  //required
            $obj_cardregister->Currency = Configuration::get('MANGOPAY_CURRENCY'); //required
            $obj_cardregister->CardType = 'CB_VISA_MASTERCARD';
            echo 'begin';
            var_dump($this->obj_api->CardRegistrations->Create($obj_cardregister));
            echo 'end';
            exit;
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }`
But i got this error in sandbox mode
`Not found. The ressource does not exist`
Thanks.

**Comment by iammichiel** [comment]
Are you sure the user is defined? However, I noticed you can get way more information from Mangopay errors. You should try `var_dump` instead.

**Comment by tarekfellah** [comment]
Thanks @iammichiel  for your response,
With 
`var_dump($obj_cardregister);`
it return this
 `object(MangoPay\CardRegistration)#418 (13) { ["UserId"]=> string(9) "221744622" ["AccessKey"]=> NULL ["PreregistrationData"]=> NULL ["CardRegistrationURL"]=> NULL ["CardId"]=> NULL ["RegistrationData"]=> NULL ["ResultCode"]=> NULL ["Currency"]=> string(3) "EUR" ["Status"]=> NULL ["Id"]=> NULL ["Tag"]=> NULL ["CreationDate"]=> NULL ["CardType"]=> string(18) "CB_VISA_MASTERCARD" }  `
When using the Production mode
I got this error
`\MangoPay\ResponseException: Code: 405
Message: Method not allowed. The requested resource does not support http method 'GET'.

Details: MangoPay\Error Object ( [Message] => The requested resource does not support http method 'GET'. [Errors] => )`
I don't know how it uses GET request, i didn't use it.
PS: i'm using Prestashop

**Comment by tarekfellah** [comment]
Any help?
up!

**Comment by paulhristea** [comment]
Hi there @tarekfellah!

I can't imagine why there would be a GET request from your code, it seems like you have made the call correctly.

Could you post the full URL and any other HTTP details (Headers, Request/Response Body etc.) that you can? Hopefully we can then figure it out.

Thanks!

**Comment by mickaelpois** [comment]
Hi @tarekfellah, could you provide @paulhristea extra informations ?

**Comment by tarekfellah** [comment]
Sorry for the delay,
The website is https://www.thefullroom.com and the payment page https://www.thefullroom.com/modules/mangopayprestashop/payment.php,
Sorry i don't  know how to get HTTP details (Headers, Request/Response Body etc.), it's not me that created the module.
Thanks.

**Comment by mickaelpois** [comment]
@tarekfellah 
Sorry, I do not see you're using Prestashop module for Mangopay !
We do not provide support for this module, because it's not a module we own.
Please contact directly its developer for further informations and help !

Mickaël
