### ISSUE TITLE
How to receive card info in PayIn?

### ISSUE THREAD

**Issue by jerronimo** [Mangopay/mangopay2-php-sdk#193]
Hi. I have used **php-sdk** method ``$mangoPayApi->PayIns->Get(35084312)``, but I always receive http://joxi.ru/Vm6dbWwFDYpY3A without card info. I have found in api docs ``View card details for a PayIn Web`` ability, but I didn't find method in **php-sdk** for it. What is the method in **php-sdk** for get that information?

**Comment by iammichiel** [comment]
How about you try to get it directly from the `Card` endpoint ? 

```
$cardInfo = $mango->Cards->Get($idCard);
```

**Comment by jerronimo** [comment]
Hi @iammichiel . In my project  I'm using web **Web PayIn** and don't know information about **cardId** . Also I don't see any information about card in [mangopay sandbox dashboard](dashboard.sandbox.mangopay.com)

**Comment by mickaelpois** [comment]
Hi @jerronimo and @iammichiel and sorry for the late answer.
I'm afraid this endpoint is not supported by our SDK. I'll try to add it very soon (this week) and give you a quick release.

We're working very hard on a new version of our dashboard (live in 3 months apex) , where card info for Payin Web will appear.

Mickaël

**Comment by mickaelpois** [comment]
Hi @jerronimo,
Late update, but we have finally added this missing endpoint to our last version thanks to #228 

Mickaël

**Comment by Aasif001** [comment]
How to make payment using web Payin..
Please create some video on youtube and upload it.
I do found too much information about the implementation.
Upload the detail video on your own site or youtube so people can find the way to integrate your api in their project.

because i do not able to find the proper way to implement your api for Web PayIn.
