### ISSUE TITLE
Missing  method for ...ClientId/disputes/pendingsettlement endpoint

### ISSUE THREAD

**Issue by Ridder90** [Mangopay/mangopay2-php-sdk#194]
Hi there, Maybe i have missed it. But it seems the SDK is missing a method for the  `.../v2.01/ClientId/disputes/pendingsettlement` endpoint. Can you please add it to the sdk or point me in the right direction ?

**Comment by mickaelpois** [comment]
Hi @Ridder90,

Yes, this endpoint is clearly missing now.
Thanks a lot for your PRs, I'll have a quick look at it and merge it if everything is fine.

Mickaël
