### ISSUE TITLE
Card is not registered into Mango pay dashboard

### ISSUE THREAD

**Issue by ypresta** [Mangopay/mangopay2-php-sdk#198]
Hi everyone!
I am using prestashop version 1.4, and I am using mangopayprestashop module for payement orders on prestashop online website. when I make a payement
in the main page of the module in initcontent() function this $result does not register card into mango pay dashboard.
$result = $this->mangopayCardRegistration();
Iget this ::
object(MangoPay\CardRegistration)#394 (13) { ["UserId"]=> string(9) "230327793" ["AccessKey"]=> NULL ["PreregistrationData"]=> NULL ["CardRegistrationURL"]=> NULL ["CardId"]=> NULL ["RegistrationData"]=> NULL ["ResultCode"]=> NULL ["Currency"]=> string(3) "EUR" ["Status"]=> NULL ["Id"]=> NULL ["Tag"]=> NULL ["CreationDate"]=> NULL ["CardType"]=> string(18) "CB_VISA_MASTERCARD" }
AND this
\MangoPay\ResponseException: Code: 405
Message: Method not allowed. The requested resource does not support http method 'GET'.

Details: MangoPay\Error Object ( [Message] => The requested resource does not support http method 'GET'. [Errors] => )
UNEXPECTED PAYMENT ERROR

HOWEVER, the user and the wallet are created into mango pay dashboard.
So please I need a help to get this to work!
Any help....

**Comment by ypresta** [comment]
PS: the function that does not work as mentioned in previous message is as follow
function mangopayCardRegistration() i{

try {

        $obj_cardregister = new MangoPay\CardRegistration();
        $obj_cardregister->UserId = $this->buyer_mangopay_userid;  //required
        $obj_cardregister->Currency = Configuration::get('MANGOPAY_CURRENCY'); //required
        $obj_cardregister->CardType = 'CB_VISA_MASTERCARD';
        echo 'begin';
        var_dump($this->obj_api->CardRegistrations->Create($obj_cardregister));
        echo 'end';
        exit;
    } catch (Exception $e) {
        die($e->getMessage());
    }
}`
any help

**Comment by mickaelpois** [comment]
Please see my comment here: https://github.com/Mangopay/mangopay/issues/46
We do not provide any support for prestashop module, because we do not own it.

Thanks for you understanding !

Mickaël
