### ISSUE TITLE
PHP 5.3 compatibility

### ISSUE THREAD

**Issue by GillesChila** [Mangopay/mangopay2-php-sdk#199]
Hi,

Before doing any test, I need to use this SDK for one of my client who is using an old PHP version (5.3)

Apparently PHP 5.4 is required but does anybody managed to make this SDK work with PHP 5.3 ?

Rgds

**Comment by mickaelpois** [comment]
Hi @GillesChila,

5.4 PHP version is the oldest one we decided to support now (hard choice to defined an older version ;) )
If somebody there could give you some information and propose some PR with quickfixes needed to support 5.3 PHP version, she/he will be very welcome !

Mickaël

**Comment by alcaeus** [comment]
> If somebody there could give you some information and propose some PR with quickfixes needed to support 5.3 PHP version, she/he will be very welcome

Oh god please no. PHP 5.3 has been dead for years now, it's time to move on. Please don't encourage people to submit pull requests to keep the thing alive. Just put it out of its misery. Thanks.
