### ISSUE TITLE
Creating mandate in sandbox

### ISSUE THREAD

**Issue by navihtot** [Mangopay/mangopay2-php-sdk#203]
Hi,

I'm trying to create mandate in sandbox but I'm constantly getting an error:

> "Bad request. Error this mean of payment for this asked currency has been disabled"

my code is:
```php
// 0. Just crate random user for sandbox
$User = new \MangoPay\UserNatural();
$User->FirstName = 'Successful'; //needs to be this string for testing mandate creation
$User->LastName = 'Smith';
$User->Email = 'email@domain.com';
$User->Birthday = time();
$User->Nationality = 'DE';
$User->CountryOfResidence = 'FR';
$createdUser = $this->mangopay->Users->Create($User);

// 1. create bank account for user (customer)
$UserId = $createdUser->Id;
$BankAccount = new \MangoPay\BankAccount();
$BankAccount->Type = "IBAN";
$BankAccount->Details = new \MangoPay\BankAccountDetailsIBAN();
$BankAccount->Details->IBAN = "FR7618829754160173622224154";
$BankAccount->Details->BIC = "CMBRFR2BCME";
$BankAccount->OwnerName = "Successful Smith";
$BankAccount->OwnerAddress = new \MangoPay\Address();
$BankAccount->OwnerAddress->AddressLine1 = 'Nowhere street 7';
$BankAccount->OwnerAddress->City = 'Paris';
$BankAccount->OwnerAddress->Country = 'FR';
$BankAccount->OwnerAddress->PostalCode = '10247';

$createdBankAccount = $this->mangopay->Users->CreateBankAccount($UserId, $BankAccount);

// 2. create a mandate
$Mandate = new \MangoPay\Mandate();
$Mandate->BankAccountId = $createdBankAccount->Id;
$Mandate->UserId = $UserId;
$Mandate->Culture = 'DE';
$Mandate->MandateType = 'DIRECT_DEBIT';
$Mandate->ExecutionType = 'WEB';
$Mandate->Scheme = 'SEPA';
$Mandate->ReturnURL = url("/shop/payin_debit".$pid);
$createdMandate = $this->mangopay->Mandates->Create($Mandate);
```

Why am I not able to create mandate?

**Comment by t-prod** [comment]
I think they put a new release and there are several problems.
Wait and see for 1 day for me

Your code will typically work.

**Comment by navihtot** [comment]
Thanks for your feedback, I was unsure if I'm doing something wrong

**Comment by mickaelpois** [comment]
Hi @navihtot and @t-prod and very sorry for this long delay.
That's true, we have released a new version of our API named Cockatoo on Nov 9th.
I will have a look at this today.

Mickaël

**Comment by kiwibun** [comment]
Maybe it is necessary to activate mandates for your account.

The exception holds the exact error, which is in my case: "The method payment DIRECT_DEBIT_GOCARDLESS with the ccy EUR is not active for the partner ****".

**Comment by dinatih** [comment]
Hello @mickaelpois, do you have any news about this issue, please, because I can't start to develop this feature without sandbox env. ?

**Comment by kiwibun** [comment]
It is not a bug, @dinatih , you need to contact the customer service to activate mandates in sandbox mode. This solved the problem for me.

**Comment by dinatih** [comment]
Oh alright ! Thanks a lot @kiwibun

**Comment by navihtot** [comment]
Thanks @kiwibun I will try contacting them to enable it

**Comment by domaze** [comment]
Did you encounter problems any more ?
