### ISSUE TITLE
UpdateBankAccount problem

### ISSUE THREAD

**Issue by huggy06** [Mangopay/mangopay2-php-sdk#204]
Bonjour la methode UpdateBankAccount ne fonctionne pas.
J'essai de modifier l'IBAN mais cela ne fonctionne pas.
Avez vous une idée ?

$UserId = "37872694";
$BankAccount = new \MangoPay\BankAccount();
$BankAccount->Id='37895159';
$BankAccount->Type = "IBAN";
$BankAccount->Details = new \MangoPay\BankAccountDetailsIBAN();
$BankAccount->Details->IBAN = "FR7618829754160173622224154";
$BankAccount->Details->BIC = "CMBRFR2BCME";
$BankAccount->OwnerName = "titi";
$BankAccount->OwnerAddress = new \MangoPay\Address();
$BankAccount->OwnerAddress->AddressLine1 = "rue de la paix";
$BankAccount->OwnerAddress->City = "Paris";
$BankAccount->OwnerAddress->Region = "";
$BankAccount->OwnerAddress->PostalCode = "75001";
$BankAccount->OwnerAddress->Country = "FR";
$result = $mangoPayApi->Users->UpdateBankAccount($UserId, $BankAccount);

**Comment by t-prod** [comment]
Bonjour,

Cette fonction ne marchera pas car l'API de MangoPay l'a désactivé.
Il vous faut désactiver le compte bancaire concerné puis et en créer un autre.

**Comment by mickaelpois** [comment]
Bonjour,

Absolument, comme @t-prod l'explique à juste titre, l'édition d'un compte bancaire est simplement limitée à sa désactivation, définitive. 
La raison est assez simple: garder un historique cohérent, ne pas risquer de modifier et de rendre incohérentes les données d'opérations en cours (si l'on acceptait le changement des coordonnées d'un compte bancaire alors qu'un Pay-Out est en cours par ex).

Mickaël
