### ISSUE TITLE
Get status bank account

### ISSUE THREAD

**Issue by aksld** [Mangopay/mangopay2-php-sdk#223]
Hi,

I can not find how to recover the status 'Active' of a bank account.

Here is how i get the list of bank accounts :

`$mangoPayApi->Users->GetBankAccounts`

https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e2_view-a-bank-account

Thanks for your help.

**Comment by mickaelpois** [comment]
Hello @aksld ,

I'm affraid I do not understand your question.
Do you want to know how to:
* get the value of Active property (which is a boolean) for a bankaccount?
* filter this list to get only active bankaccounts?
* make a bankaccount being active after being set as an inactive one?

Mickaël

**Comment by aksld** [comment]
Hi,

Thanks for your help.

Just the first point is good for me. With that, I can made the second point.

I just need to read the Active property.

**Comment by mickaelpois** [comment]
Hello,

If you look to this snippet of code (from SDK tests), you can see 
* how to get a particular Bankaccount through a list result: https://github.com/Mangopay/mangopay2-php-sdk/blob/master/tests/cases/users.php#L295
* how to get this `Active` property: https://github.com/Mangopay/mangopay2-php-sdk/blob/master/tests/cases/users.php#L250

But it seems filtering is missing for some endpoints, as I can see here: https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/ApiUsers.php#L139

We're currently supporting filtering on our API, but it seems it's lacking on this SDK.
I'll put it on our roadmap to be done very soon.

Mickaël

**Comment by aksld** [comment]
Hello,

With this code :

`
$john = $this->getJohn();
$account = $this->getJohnsAccount();`

You set the active value to true.

But can I read the active value ?

**Comment by paulhristea** [comment]
Hi @aksld!

Sorry about the delay.
That should be exactly right! Could you please confirm that calling `$account->Active` on a valid account object does not allow you to read the value of the Active property? I just tried it out and it behaves as expected.

Please let us know!
