### ISSUE TITLE
Update KYC page documentation for API v2.01

### ISSUE THREAD

**Issue by daniel18387** [Mangopay/mangopay2-php-sdk#224]
The documentation for creating a KYC page is incorrect. The `File` value should be a path to a local file. Not a base64 encoded version of the file. As [you can see](https://github.com/Mangopay/mangopay2-php-sdk/blob/5d6a589ecac93c50a29b7afb80fe2d7e22a3d383/MangoPay/ApiUsers.php#L308) from the `CreateKycPageFromFile` method, specifically line `320`, the SDK handles the base64 encoding of the file. 

```
    public function CreateKycPageFromFile($userId, $kycDocumentId, $filePath, $idempotencyKey = null)
    {
        if (empty($filePath)) {
            throw new \MangoPay\Libraries\Exception('Path of file cannot be empty');
        }
        if (!file_exists($filePath)) {
            throw new \MangoPay\Libraries\Exception('File not exist');
        }
        $kycPage = new \MangoPay\KycPage();
        $kycPage->File = base64_encode(file_get_contents($filePath));
        if (empty($kycPage->File)) {
            throw new \MangoPay\Libraries\Exception('Content of the file cannot be empty');
        }
        $this->CreateKycPage($userId, $kycDocumentId, $kycPage, $idempotencyKey);
    }
```
Please update the documentation at your earliest convenience. For the sake of other developers and their time I insist that this is dealt with sooner rather tan later.

**Comment by mickaelpois** [comment]
Hi @daniel18387,

I suppose you were refering to [this page](https://docs.mangopay.com/endpoints/v2.01/kyc-documents#e208_create-a-kyc-page) on our documentation website.
This documentation is strongly linted to our API, and not to every SDKs we're providing to developers. Our API is managing a base64 value for this particular endpoint, that's the reason our documentation mentions this type.
We're strongly aware of this lack of precision on our documentation page depending what kind of SDK is used (PHP, Python, Node etc.) and an update of this website is planned this year.

As a workaround, I can update shortly our PHP documentation to be more precise on what type must be used to make this call work properly.

Mickaël

**Comment by daniel18387** [comment]
Hi @mickaelpois 

Thanks for getting back to me. Your workaround should be more than sufficient. It was more a case of me drawing your attention to the differences, in case you were unaware.

Feel free to close this issue :smile:
