### ISSUE TITLE
Missing LegalRepresentativeProofOfIdentity in ApiUsers Get method

### ISSUE THREAD

**Issue by gaetan-petit** [Mangopay/mangopay2-php-sdk#225]
If you GET a LegalUser with the SDK, incorrect IdentityProof gets return:

`+ProofOfIdentity: null`

Should be:

` +LegalRepresentativeProofOfIdentity: "0123456789"`

**Comment by mickaelpois** [comment]
Hello @gaetan-petit,

Thanks a lot for your fix :)
Your PR is now merged and will be shortly released in a minor 2.7.1 update.

Mickaël

**Comment by gaetan-petit** [comment]
2.7.1 available through packagist.
Closing this issue.
