### ISSUE TITLE
API Integration impossible 

### ISSUE THREAD

**Issue by airjobbing** [Mangopay/mangopay2-php-sdk#231]
We have a very simple PHP project with 
- MangoPay folder
- MangoPay/Psr/Log folder

and this file :

require_once "../MangoPay/Autoloader.php";

$MangopayApi = new MangoPay\MangoPayApi();
$MangopayApi->Config->ClientId = "xxxxxx";
$MangopayApi->Config->ClientPassword = "xxxxxx";
$MangopayApi->Config->TemporaryFolder = "/tmp/";
$User = new MangoPay\UserNatural();
$User->Email = "xxx@xxx.com";
$User->FirstName = "xxx";
$User->LastName = "xxxxx";
$User->Birthday = xxxxxx;
$User->Nationality = "FR";
$User->CountryOfResidence = "ZA";
$result = $mangoPayApi->Users->Create($User);

The first problem is with new MangoPay/MangoPayApi(), it doesn't work because there is a problem with the line $this->logger = new NullLogger(); in the constructor.
And if we comment this line, we have a second problem with le line $result = $mangoPayApi->Users->Create($User); it doesn't work.

Please, Can you explain us how we have to get directory for working good ?

Thanks a lot.

**Comment by airjobbing** [comment]
There is no error displayed.
No i use the installation without composer method.

**Comment by airjobbing** [comment]
You can find my very simple code here : [http://www.airjobbing.com/mangopay/mangopay.zip](http://www.airjobbing.com/mangopay/mangopay.zip)

**Comment by gaetan-petit** [comment]
I think you missed, from the instructions : 
> (don't forget to include the required library dependencies though)
You can see the dependencies in packagist  : https://packagist.org/packages/mangopay/php-sdk-v2

You should use composer, this make the whole process easier.

**Comment by airjobbing** [comment]
You specify : You do not have to use Composer, but you are strongly advised to (particularly for handling the dependency on the PSR Log library)
I would like not use Composer just for this SDK.
Can we do otherwise for use Log ?

otherwise |  
-- | --




otherwise |  
-- | --

**Comment by airjobbing** [comment]
Finnaly we have used composer. Thanks
