### ISSUE TITLE
MangoPay\Exception Message: Cannot create or write to file 

### ISSUE THREAD

**Issue by rajinth** [Mangopay/mangopay2-php-sdk#238]
i create the tmp folder and set permission also but still it gives the mention error while i create the new natural user : can anybody help?

**Comment by paulhristea** [comment]
Hello @rajinth!

What system (Windows/Mac/etc) are you running when you encounter this problem? Please make sure you've created a folder and have correctly specified the full path to it when configuring Mangopay (ex: `$this->mangoPayApi->Config->TemporaryFolder = 'C:\\path\\to\\folder';`), following the README.md documentation from https://github.com/Mangopay/mangopay2-php-sdk .

Please let us know some more details if you still have this issue.
Thank you!
