### ISSUE TITLE
AuthenticationHelper.php: GetHttpHeaderBasicKey() not working as described in documentation, breaking ApiOAuth.

### ISSUE THREAD

**Issue by Quesstor** [Mangopay/mangopay2-php-sdk#240]
Using the implementation i always get the following error, when CreateToken() in ApiOAuth.php is called.

```
MangoPay\ResponseException Code: 401
-------------------------------
Message: Unauthorized
-------------------------------
Details: 
-------------------------------
```

After some code reviewing i found the following line in AuthenticationHelper.php 
Line 45: `$signature = $this->_root->Config->ClientId . ':' . $this->_root->Config->ClientPassword;`

Looking at the Documentation (https://docs.mangopay.com/guide/authentification) this should be ClientId:API_KEY.
After replacing `$this->_root->Config->ClientPassword` with the (hardcoded) API_KEY it suddendly worked. Not sure if ClientId:ClientPassword is supposed to work, too, but in my case it did not.

**Comment by paulhristea** [comment]
Hi there @Quesstor! Sorry about the delayed response.

Is the value in `$this->_root->Config->ClientPassword` identical to the hardcoded API_KEY which actually works for you? Please print that value and check, maybe your Mangopay Configuration is incorrectly set up.

Please get back to us.
Thanks!

**Comment by Quesstor** [comment]
Hi @paulhristea ,
it is probably just a naming error. 
When you configure MangoPayApi, `api->Config->ClientPassword` needs to be set with the API_KEY and not the client password. 

Renaming `api->Config->ClientPassword` to `api->Config->ApiKey` would probably prevent future confusion.

Additionally in the README.md you state that 
> Using the credential info from the signup process above, you should then set `$api->Config->ClientId` to your Mangopay ClientId and `$api->Config->ClientPassword` to your Mangopay passphrase.

which is not correct because you have to set `$api->Config->ClientPassword` to your Mangopay API_KEY.

**Comment by paulhristea** [comment]
I see. Sorry about the confusion.

Please use the API Key during the configuration process, that should work for now. I will see what we can do about renaming/editing the docs to make this point clearer and to avoid this problem in the future.

Thank you!

**Comment by mickaelpois** [comment]
Hi @Quesstor ! ClientPassword will be renamed in ApiKey thanks to #272 to be clearer 👍
