### ISSUE TITLE
Can't list More than 10 Wallet Transactions

### ISSUE THREAD

**Issue by vestaxpdx** [Mangopay/mangopay2-php-sdk#241]
Hi

How can we list more than 10 results per page. I can't figure this out and it's driving me a bit mad.

This should work but it always only displays 10 results?

What am I doing wrong?

```
$pagination                 = new stdClass();
$pagination->Page           = 1;
$pagination->ItemsPerPage   = 100; //this doesn't work... why... :(
$filter                     = array('Status' => 'SUCCEEDED', 'Sort' => 'CreationDate:DESC');
$transactions               = $mangopay->Wallets->GetTransactions($wallet_id, $pagination, $filter);

print_r($transactions);
```

I hope someone can help. I am using the latest version of the SDK.

**Comment by iammichiel** [comment]
And why are you using a `stdClass` ? Use a Pagination class directly :
```
$pagination = new Pagination();
$pagination->Page  = 1;
$pagination->ItemsPerPage = 100;
```

That should work better. 

This is taken from the method that creates the Http Request : 
```
        if (is_null($pagination) || !is_object($pagination) || get_class($pagination) != 'MangoPay\Pagination') {
            $pagination = new \MangoPay\Pagination();
        }
```

You pagination object get dropped as it is not a `Pagination` object.

**Comment by vestaxpdx** [comment]
Awesome many thanks!

I did try digging into the code but did not realise the pagination was a whole class of it's own that you needed to pass and could not find any code examples with pagination.

Thanks again :)
