### ISSUE TITLE
Issue with pre-auth with release 2.8.0

### ISSUE THREAD

**Issue by coolmic** [Mangopay/mangopay2-php-sdk#243]
I have this error when doing a pre-auth pay-in.
(I didn't define the Billing parameter, as it should be optional)

```json
{
"Billing.Address.AddressLine1": "The AddressLine1 field is required.", 
"Billing.Address.City": "The City field is required.", 
"Billing.Address.Country": "The Country field is required."
} 
```

I don't have error when doing direct pay-in, or with the sdk 2.7.1 .
Guess it's an error on mangopay api side? I

**Comment by paulhristea** [comment]
Hello @coolmic!

Which step of the process is it that you get this error? Most likely, an empty Billing object is actually set when you are doing the request. Please print the value of the Preauth object right before sending the failing request and paste it here, along with some of the code where you are sending the request.

Thank you!

**Comment by mickaelpois** [comment]
Hello @coolmic and sorry for the very late answer.
This issue must be resolved thanks to our last API release (done last week).

Billing Address was not ignored if not required by our API (PUT Preauth or POST Payin Preauth), and the way we retrieve and update data on our SDKs has revealed this issue.
