### ISSUE TITLE
Issue - Transfer amount from user to client wallet

### ISSUE THREAD

**Issue by Shaz4584** [Mangopay/mangopay2-php-sdk#244]
Hi, 
I wrote below code for transfer amount from Natural user wallet to mangopay client's wallet. But it show me error: 

> [CreditedWalletId] => Wallet not found

                    $transfer = new \MangoPay\Transfer();
			$transfer->Tag = "Transfering into client wallet";
			$transfer->AuthorId = $user_id;
			$transfer->CreditedUserId = $MangoPay_ClientId;
			$transfer->DebitedFunds = new \MangoPay\Money();
			$transfer->DebitedFunds->Currency = "USD";
			$transfer->DebitedFunds->Amount = 30;
			$transfer->Fees = new \MangoPay\Money();
			$transfer->Fees->Currency = "USD";
			$transfer->Fees->Amount = 30;
			$transfer->DebitedWalletId = $userWalletId;
			$transfer->CreditedWalletId = "CREDIT_USD"; // Client's USD Wallet ID

			$result = $api->Transfers->Create($transfer);

I get Client's wallets using:  `$api->Clients->GetWallets();`
And get the response ( attached file ) [ClientWalletResponse.txt](https://github.com/Mangopay/mangopay2-php-sdk/files/1971128/ClientWalletResponse.txt)

I see [previous posted issue](https://github.com/Mangopay/mangopay2-php-sdk/issues/91) but this didn't help me.

Thanks in advance. Its urgent.

**Comment by jarjini** [comment]
anyone found solution for that :)

**Comment by mickaelpois** [comment]
Hello @Shaz4584,

I guess it's too late now, but I'll answer your question:
You can't transfer funds from a user wallet to your credit wallet.
The best way to put some money on your side is to use Fees feature, available on Pay-In, Transfer and Pay-out, to make funds available on your Fees wallet.
