### ISSUE TITLE
Erreur Class 'Psr\Log\NullLogger' not found (Codeiginter 3)

### ISSUE THREAD

**Issue by AJ-20** [Mangopay/mangopay2-php-sdk#246]
Nous utilisons Codeigniter 3  et nous rencontrons un problème. Nous avons
besoin d'une version complète avec dépendances (pas de composer) mais la
version 2.8.0 <https://github.com/Mangopay/mangopay2-php-sdk/tree/2.8.0> ne
fournit pas le paquet entier.

Voici l'erreur :  Class 'Psr\Log\NullLogger' not found

**Comment by alcaeus** [comment]
`NullLogger` is a class provided by `psr/log` which is a hard requirement for this package. If you want to install it without composer, the readme tells you to make sure to install dependencies:

> You do not have to use Composer, but you are strongly advised to (particularly for handling the dependency on the PSR Log library

> If you're not using PSR-4 or Composer, the installation is as easy as downloading the library and storing it under any location that will be available for including in your project (don't forget to include the required library dependencies though)

**Comment by AJ-20** [comment]
Hello thx for your reply but what dependencies where we can find them Thx a lot

**Comment by alcaeus** [comment]
> but what dependencies where we can find them

I strongly suggest using composer to handle them, especially since you don't know how to figure out where you can find dependencies for the library. In this case, you're looking for https://packagist.org/packages/psr/log.

**Comment by AJ-20** [comment]
ok done we installed psr/log via composer in the root of the project, the we find un folder under cendor named psr inside there is all files mangopay is in the libraries folder under application in codeiginter, what u do next ? thx

**Comment by AJ-20** [comment]
We solved the problem by the compser, but we have this erreor actually

An uncaught Exception was encountered
Type: MangoPay\Libraries\ResponseException

Message: Unauthorized

**Comment by AJ-20** [comment]
We solved the problem by the composer, but we have this error actually

An uncaught Exception was encountered
Type: MangoPay\Libraries\ResponseException

Message: Unauthorized

**Comment by paulhristea** [comment]
Hello @AJ-20!

Have you configured the Mangopay Configuration using your Client ID and Passphrase?
Please provide some of the code where this error happens.

Thanks!

**Comment by paulhristea** [comment]
Closing as this issue has actually been solved.
Continued at https://github.com/Mangopay/mangopay2-php-sdk/issues/247
