### ISSUE TITLE
An uncaught Exception was encountered Type: MangoPay\Libraries\ResponseException  Message: Unauthorized

### ISSUE THREAD

**Issue by AJ-20** [Mangopay/mangopay2-php-sdk#247]
Bojour, nous rencontrons ce problème, merci d'avance de votre aide

An uncaught Exception was encountered
Type: MangoPay\Libraries\ResponseException
Message: Unauthorized

**Comment by paulhristea** [comment]
Hello @ AJ-20 !

Have you configured the Mangopay Configuration using your Client ID and Passphrase?
Please provide some of the code where this error happens.

Thanks!

**Comment by paulhristea** [comment]
Hello  @AJ-20 !

Have you configured the Mangopay Configuration using your Client ID and Passphrase?
Please provide some of the code where this error happens.

Thanks!

**Comment by mickaelpois** [comment]
Hello @AJ-20,

I guess your issue about authentication is now solved :)

**Comment by IbrahimCamara** [comment]
Bonjour j'ai à peu près le même problème sauf que pour moi c'est une erreur comme ça : 

MangoPay\Libraries\ResponseException: Not found in (DirProject)\vendor\mangopay\php-sdk-v2\MangoPay\Libraries\RestTool.php: 330

Ma fonction
public function setTransfer()
    {
        $mangoTransfer = new Transfer();
        $mangoTransfer->AuthorId = "80003178";
        $mangoTransfer->CreditedUserId = "80002671";
        $mangoTransfer->DebitedFunds = new Money();
        $mangoTransfer->DebitedFunds->Currency = "EUR";
        $mangoTransfer->DebitedFunds->Amount = 3000;
        $mangoTransfer->Fees = new Money();
        $mangoTransfer->Fees->Currency = "EUR";
        $mangoTransfer->Fees->Amount = 500;
        $mangoTransfer->DebitedWalletId = "80003350";
        $mangoTransfer->CreditedWalletId = "80002894";
        $mangoTransfer->Tag = "tag";

        $Transfer = null;

        //Send the request
        try {
            $Transfer = $this->mangoPayApi->Transfers->Create($mangoTransfer);
        }catch (Exception $exception){
            //return $exception->getMessage();
            printf($exception);
        }

        return $Transfer;
    }
