### ISSUE TITLE
Get all user cards without paginator

### ISSUE THREAD

**Issue by XemaA** [Mangopay/mangopay2-php-sdk#248]
Hello ! When I send a request to get all user cards (without paginator ) I only get the first 10 cards.
Is there any way to get all registered cards on one request?
This how I do it :  $mangoapi->Users->GetCards($user_mango_id);

**Comment by iammichiel** [comment]
No, you cannot get more then 10 objects without using a Pagination object. As stated in[ the documentation](https://docs.mangopay.com/guide/lists-pagination-management), by default, all listing are limited to 10 results. If you want more, you will have to pass on a Paginator object. 

```
Page: index of the page (start to 1) Default value: 1
Per_Page: number of items returned. Default value: 10 Max: 100
```

Here is how you would do it with a Pagination object :
```
$pagination = new \Mangopay\Pagination();
$pagination->Page = 1;
$pagination->ItemsPerPage = 100;

$cards = $mango->Users->GetCards($user_mango_id, $pagination);
```

**Comment by XemaA** [comment]
Thanks @iammichiel !
