### ISSUE TITLE
Mangopay\Money $Amount doc-block reference of @var Long can not be found.

### ISSUE THREAD

**Issue by wRLSS** [Mangopay/mangopay2-php-sdk#252]
`\Mangopay\Money` variable `$Amount` has reference to unknown type `@var Long`. This leads to static analysis problems. 

```
    /**
     * The currency amount of money
     * @var Long
     */
    public $Amount;
```

**Comment by paulhristea** [comment]
Hello @wRLSS!

A PR is submitted to solve this and will be merged ASAP.

Thanks for bringing this to our attention!

**Comment by mickaelpois** [comment]
Hello @wRLSS (and thanks @paulhristea for your PR),

This enhancement has been merged and will be released this week !
