### ISSUE TITLE
cURL error: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.sandbox.mangopay.com:443

### ISSUE THREAD

**Issue by kamdjouduplex** [Mangopay/mangopay2-php-sdk#256]
Hello there I am running through this error and I don't know exactly what to do.

I manage to setup mangopay on my Laravel Application and when creating a Natural User this the code exeption error i am getting.
`{"message":"cURL error: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.sandbox.mangopay.com:443 ","code":0}`
 and here is my code:
` //Create user mangopay account and initiate the card registration
    public function createUser(Request $request)
    {
    	
    	$country = $this->country_to_code($request->get('country'));
    	$date_of_birth = Carbon::parse($request->get('dob').' 00:00:00');

    	try {
    		// create user for payment
    		$user = new MangoPay\UserNatural();
    		$user->FirstName = $request->get('nom');
    		$user->LastName = $request->get('prenom');
    		$user->Email = $request->get('email');
    		$user->Birthday = $date_of_birth->timestamp;
    		$user->Nationality = $country;
    		$user->CountryOfResidence = $country;
    		$user->Occupation = "Occupation";
    		$user->IncomeRange = 3;
    		$createdUser = $this->mangopay->Users->Create($user);

    		// initiate the card registration
    		$cardRegister = new \MangoPay\CardRegistration();
    		$cardRegister->UserId = $createdUser->Id;
    		$cardRegister->Currency = 'EUR';
    		$cardRegister->CardType = 'CB_VISA_MASTERCARD';
    		$createdCardRegister = $this->mangopay->CardRegistrations->Create($cardRegister);

    		return view('card-info', compact('createdCardRegister'));

    	} catch(MangoPay\Libraries\Exception $e) {
    		// handle/log the exception $e->GetMessage()
    		return response()->json([
    		    'message' => $e->GetMessage(),
    		    'code' => $e->GetCode()
    		]);

    	}
    }`

Please what does the error mean ?
**Note** I used the same code some few days ago and it was working.

**Comment by iammichiel** [comment]
That error seems to indicate a problem with your curl setup and not with the library itself. Could you try to curl any other https url using php-curl?

**Comment by kamdjouduplex** [comment]
Sure that was the problem.

**Comment by CurvesTech** [comment]
how did you fix it?

**Comment by stifler97** [comment]
> Sure that was the problem.

how did you fix this?
