### ISSUE TITLE
Use an up-to-date testing framework

### ISSUE THREAD

**Issue by alcaeus** [Mangopay/mangopay2-php-sdk#262]
The `simpletest/simpletest` library used to test the library is dead for all we know: the last release was almost 3 years ago (November 2015) with the last commit to the repository almost a year ago. I would suggest moving to a supported and better-known testing framework, e.g. PHPUnit. I could help rewrite some of the tests for PHPUnit, but didn't want to do so before getting an opinion from the maintainers on this. What's your take?

**Comment by mickaelpois** [comment]
Hello @alcaeus !

Thanks for your feedback and your proposal, we really appreciate it  👍 
I will take a look with @paulhristea very soon and we will keep you posted here about our choice, but that's definitively something we want to do as a short term enhancement !

Mickaël

**Comment by mickaelpois** [comment]
Hello @alcaeus !
#274 will replace our outdated testing framework by PHPUnit, in our next SDK release 👍
