### ISSUE TITLE
Mandate Status

### ISSUE THREAD

**Issue by bagdoul** [Mangopay/mangopay2-php-sdk#266]
Hello,

As `PayinStatus` and `DisputeStatus`, is it possible to add a simple class `MandateStatus` with constance from https://docs.mangopay.com/endpoints/v2.01/mandates#e230_the-mandate-object ?

**Comment by mickaelpois** [comment]
Hi @bagdoul,
It makes perfectly sense, thanks for your feedback.
We will add it very shortly and release a new version of our SDK to let you use this new class !

**Comment by mickaelpois** [comment]
Hello @bagdoul !
Our next SDK release will feature this new class thanks to #279 👍
