### ISSUE TITLE
Get infos for one IDTRANSACTION

### ISSUE THREAD

**Issue by titoff002** [Mangopay/mangopay2-php-sdk#269]
Hello,

Using the PHP SDK, I would like to retrieve the information of the transaction (I only pass the number of the transaction (transaction_id), and I recover all of its information).

Can you tell me how to do it, and if possible put me a PHP program that is fine.

Thank you,
Regards,
Christophe

**Comment by iammichiel** [comment]
Hi there, 

Of course, this is possible. However, you have to know the type of the transaction. All entrypoints require the type of transaction. A small example below : 

```php
$payin = $api->PayIns->Get($idTransaction);
$transfer = $api->Transfers->Get($idTransaction);
$payout = $api->PayOuts->Get($idTransaction);
```

**Comment by mickaelpois** [comment]
Hi @titoff002 and thanks @iammichiel for your prompt and right answer !

Transaction is an upper level of abstraction which represents every monetary operation on our API. You can't use it as-is, and you need to know what kind of transaction it is to retrieve it, as each type has some specifics concepts and properties.

Let us know if everything is OK on your side @titoff002.
