### ISSUE TITLE
Feature request: extra argument to the notification / callback

### ISSUE THREAD

**Issue by patricksavalle** [Mangopay/mangopay2-php-sdk#27]
Our system, and I think most other systems would be MUCH simpler if you change the notification callback slightly.

The callback/notification should contain the URL of the resource. If you add the URL of the resource, all existing systems would still work. Like this:

    http://oursite.com/callback?RessourceId=914329&EventType=KYC_SUCCEEDED&Date=1413991648&Url=/users/8578/KYC/documents/87670

Of course this would need to be URL encoded, like this:

    http://oursite.com/callback?RessourceId=914329&EventType=KYC_SUCCEEDED&Date=1413991648&Url=%2Fusers%2F8578%2FKYC%2Fdocuments%2F87670

Ideally you would send the URL as the only parameter.

**Comment by patricksavalle** [comment]
I hope you didn't forget this :) VERY USEFUL!

**Comment by hobailey** [comment]
Absolutely not, just quite a few things to get through before this I'm afraid ;-)
But that doesn't mean it won't happen!

**Comment by patricksavalle** [comment]
Ok, nice. To me it seems a very simple adjustment :) It won't break existing application either.

**Comment by hobailey** [comment]
It is pretty simple, but unfortunately there are lots of not so simple things to get through the pipe first :-)

**Comment by patricksavalle** [comment]
Ok, I ran into another problem with this. 

When I upload a KYC document from  https://dashboard.mangopay.com/Operations/UploadKycDocument our application receives a notification. This is good :) But the notification only sends us the document_id. It is impossible to deduce which user_id it is. 

So this makes the dashboard unusable for this operation because we cannot update/inform the user.

**Comment by hobailey** [comment]
Just so you know, the Dashboard is effectively a 3rd party that makes API calls on your behalf, therefore it has the same capability of the API and has access to no more/less data/functionality that the normal API.

**Comment by hobailey** [comment]
Hi @patricksavalle, just to let you know that we've just released a new API call for the KYC docs (GET /kyc/documents/:documentId) which doesn't require you to know the UserId of the doc :-)
