### ISSUE TITLE
Error when creating a Direct-Debit Direct PayIn

### ISSUE THREAD

**Issue by remy-shopopop** [Mangopay/mangopay2-php-sdk#273]
Hello,

I tried to create a PayIn with PayInPaymentDetailsDirectDebitDirect and PayInExecutionDetailsDirect for a Direct-Debit Direct. But it fails saying that the key payins_directdebitdirect-direct_create is out of index.

In fact the key is not in the APiBase.php, the good one is payins_directdebit-direct_create. I suggest you to remove the class "PayInPaymentDetailsDirectDebitDirect" (developers can use PayInPaymentDetailsDirectDebit in the meanwhile) or change the key ;)

Thanks a lot !

**Comment by kevindesousa** [comment]
Hello,
I have the same problem, do you resolve ?

**Comment by remy-shopopop** [comment]
@kevindesousa Yes, I found the trick. You should use PayInPaymentDetailsDirectDebit with a PayInExecutionDetailsDirect. See the example below ;)

$payIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsDirectDebit();
$payIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();

**Comment by AntoineLemaire** [comment]
Question solved, but problem is still there. We can't use `PayInPaymentDetailsDirectDebitDirect`

**Comment by matthieuuu** [comment]
@AntoineLemaire well, it's not a problem since you should make Direct-Debit Direct PayIn without it :)

@remy-shopopop suggested to remove the useless class `PayInPaymentDetailsDirectDebitDirect`, this should avoid any misunderstanding in the future

Maybe @mickaelpois could tell us more !
