### ISSUE TITLE
[!] Error installing Firebase , curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.google.com:443 

### ISSUE THREAD

**Issue by pradeepapps16** [Mangopay/mangopay2-php-sdk#275]
While am trying to install Crashlytics to my Xcode project to update crash reporting to Crashlytics.Am getting error like 
*[!] Error installing Firebase
*curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.google.com:443

**Comment by iammichiel** [comment]
Hi there, 

Why would you use the php version of the library in a XCode project? Perhaps, you should open this issue on the iOs SDK? And I see no error related to mangopay in your issue?

**Comment by mickaelpois** [comment]
@pradeepapps16 I guess this is a purely technical issue not strongly linked to our SDK.
I will close this issue, feel free to re-opened it if you find something wrong on our side :)
