### ISSUE TITLE
Clarify Readme : Client-password should be API-key (Unauthorized error)

### ISSUE THREAD

**Issue by Nicolas-Bouteille** [Mangopay/mangopay2-php-sdk#276]
Hello,

May I suggest you clarify the documentation on the readme file, as I have been spending a few hours trying to make the SDK example work but could not until I figured out that I should enter the API-Key as the Client-password and not my client password ^^

I was getting an 401 Unauthorized error.

**Comment by mickaelpois** [comment]
Hello @Nicolas-Bouteille and thans for your feedback.
#279 + a readme update will make this clearer, sorry for your lost of time !
