### ISSUE TITLE
Feature request: opportunity for client to abort a payment/action during XXX_CREATED callback

### ISSUE THREAD

**Issue by patricksavalle** [Mangopay/mangopay2-php-sdk#28]
It would be nice if a client could signal the Mangopay API to abort for instance a PAYOUT during the PAYOUT_NORMAL_CREATED notification.

If the client returns a HTTP 403 Forbidden for instance, this could mean that Mangopay needs to abort the payout.

This mechanisme gives much extra security. If an unauthorized payment was done for instance.

**Comment by hobailey** [comment]
Hi @patricksavalle, sorry for the delay getting back to you but this is something we've decided that we're not planning to implement in the near future I'm afraid. Our events (and hence hooks) are triggered after the transaction has happened, so it would require some serious rework to this whole mechanism to incorporate your suggestion unfortunately. 
It's something we may well review in the second half of next year though :-)
