### ISSUE TITLE
How to Use Pagination Properly

### ISSUE THREAD

**Issue by vestaxpdx** [Mangopay/mangopay2-php-sdk#282]
Hi

Forgive me if I am being really thick here but I can't see any useful data returned like number of pages to loop through when getting transactions.

I have set to just 2 items per page to ensure there are more items to show.

```
$pagination  = new \MangoPay\Pagination();
$pagination->Page  = 1;
$pagination->ItemsPerPage = 2;
$filter = array('Status' => 'SUCCEEDED', 'Sort' => 'CreationDate:DESC', 'Type' => 'PAYIN');
$results = $mangopay->Users->GetTransactions($mangopayuser_id, $pagination, $filter);
```

The above just returns an array of transactions. There is no $Links = array() added at the end or anything. Can't see anything obvious in the docs either: https://docs.mangopay.com/guide/lists-pagination-management

I have even left out the pagination object so it just shows default 10 items, but still no pagination data?

Any help appreciated.

Thanks

**Comment by iammichiel** [comment]
Hello, 

I don't think the result contains any information about the number of results remaining. You can solve it however by using a `while` condition. 

```
$pagination = new Pagination(1, 100);
do {
    $results = $mangopay->Users->GetTransactions($mangopayuser_id, $pagination, $filter);
    $pagination->Page = $pagination->Page + 1;
} while (count($results) == 100;

```

**Comment by vestaxpdx** [comment]
Ok thanks! I will go with this approach.

I would be interested to know when the SDK is supposed to provide us with X-Number-Of-Items, X-Number-Of-Pages ?

I can see it in the Libraries\RestTool.php `ReadResponseHeader($headers)` function but have never seen it in the response.
