### ISSUE TITLE
How to update KYC status of MANGOPAY??

### ISSUE THREAD

**Issue by Aasif001** [Mangopay/mangopay2-php-sdk#284]
I have created KYC document for those mangopay user whose transaction amount is crossing 1000 EUR! And yes I am getting a response from the mangopay for the successful  KYC document creation but the validation status is "VALIDATION_ASKED"  how can set up a cron job for updating KYC status of that particular user!

**Comment by iammichiel** [comment]
Do not use cronjobs, use webhooks. 

It will send you an event when the status of the KYC validation changes.  That way you will know in real time what happens. You can find more information about that here: https://docs.mangopay.com/endpoints/v2.01/hooks#e246_the-hook-object

**Comment by mickaelpois** [comment]
Hello @Aasif001 and thanks for your question !
To complete @iammichiel answer (thanks for your prompt answer, always appreciated 👍 ), as a reminder:
- MANGOPAY's Compliance team is the only one responsible for KYC Document update from the moment you put it in a `VALIDATION_ASKED` `Status`. Our team will validate of refused this document, and only when this process is done on our side, your KYC Document `Status` will be updated.
- The best way to be aware of this `Status` update is to use webhooks as it has been said above. Use KYC_SUCCEEDED and KYC_FAILED one to know if our team considers documents as good or wrong. If it's failed, you could GET `kyc/documents/-id-` for more information.

I hope @iammichiel and my own answer will help you ! 👍

**Comment by Aasif001** [comment]
how can i update user KYC status individually??
I have created hook for KYC update!
that hook is not giving a user id of which user status is updated!
how can i identify which user status is updated!

**Comment by Aasif001** [comment]
here is my code of hook
//KYC hook create
    public function createKYCHook()
    {
         $mangoPayApi=$this->initMangoPay(); 
         try {
            $Hook = new \MangoPay\Hook();
            $Hook->Tag = "KYC UPDATE HOOK";
            $Hook->EventType = "KYC_SUCCEEDED";
            $Hook->Url = "https://payment.taskenator.com/updateKYC/";
            
            $Result = $mangoPayApi->Hooks->Create($Hook);
            
            echo "<pre>";
            print_r($Result);
            
            } catch(MangoPay\Libraries\ResponseException $e) {
            // handle/log the response exception with code $e->GetCode(), message $e->GetMessage() and error(s) $e->GetErrorDetails()
            
            } catch(MangoPay\Libraries\Exception $e) {
            // handle/log the exception $e->GetMessage()
            
            }
    }
    //KYC hook update
    public function updateKYC(Request $request)
    {
        //how can I identify which user status is changed ??
        //update KYC query will goes here
         DB::table('tbl_dummy')->insert(['dummy_txt'=>"kyc hook ran"]);
    }
