### ISSUE TITLE
what will be the URL parameters if Mangopay KYC refused. I don't find any document for this.

### ISSUE THREAD

**Issue by Aasif001** [Mangopay/mangopay2-php-sdk#289]
Like if KYC Validated then URL is
http://www.mynotificationurl.com?EventType=KYC_SUCCEEDED&RessourceId=1309853&Date=1397037093

but what parameter will hook URL send if KYC Refused ??

**Comment by Aasif001** [comment]
Please let me know ASAP

**Comment by mickaelpois** [comment]
Hello @Aasif001,

Status when a KYC Document is refused is `KYC_FAILED`.
