### ISSUE TITLE
Insecure connection in SDK

### ISSUE THREAD

**Issue by vinitraje** [Mangopay/mangopay2-php-sdk#292]
I have concern about this file: https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/Libraries/HttpCurl.php

If the certificate path is not set, is the connection to API made ignoring the validity of certificate?

**Comment by mangomaxoasis** [comment]
Hi @vinitraje 

The functionality is working on our recent tests,

Regards,
Max
