### ISSUE TITLE
2 systems using mangopay are suddenly throwing exceptions creating a natural user

### ISSUE THREAD

**Issue by kevin-finesse** [Mangopay/mangopay2-php-sdk#294]
I have 2 apps using mangopay2-php-sdk on the servers to process payments. In the last 2 weeks both have them have suddenly started throwing exceptions when trying to create a new natural user. I am getting a 404 exception response code. Has something changed at mangopay and how can I resolve this asap as we are effectively unable to onboard new customers.

**Comment by venyii** [comment]
Are you already on 2.9.2? There was an issue that caused 404 errors for some people which got fixed in that version https://github.com/Mangopay/mangopay2-php-sdk/issues/291

**Comment by kevin-finesse** [comment]
thank you for your swift reply. I've upgraded to 2.9.2 and that appears to fix the problem....

**Comment by mickaelpois** [comment]
Thanks for your prompt answer @venyii !
