### ISSUE TITLE
Fatal Error (1): Call to undefined method MangoPay\MangoPayApi::getHttpClient() 

### ISSUE THREAD

**Issue by lem356** [Mangopay/mangopay2-php-sdk#298]
Hi,

I'm getting this error once the last versión of the library is installed.

Thank you.

**Comment by venyii** [comment]
Do you have a stack trace or what are you exactly doing? It's still there in 2.9.2 https://github.com/Mangopay/mangopay2-php-sdk/blob/ad6dec126b9f6ee2b3e26a4b37b311a5ae595520/MangoPay/MangoPayApi.php#L262-L268

**Comment by SoloJr** [comment]
I could not reproduce the error..

**Comment by mangomaxoasis** [comment]
Hi @lem356 

We are currently unable to reproduce the error, feel free to contact us if the problem persists.

Regard,
max
