### ISSUE TITLE
Attempted to call an undefined method named "GetSubObjects" of class "MangoPay\PayInWebExtendedView".

### ISSUE THREAD

**Issue by gaelcancre** [Mangopay/mangopay2-php-sdk#300]
`public function GetExtendedCardView($payInId)
{
return $this->GetObject('get_extended_card_view', $payInId, '\MangoPay\PayInWebExtendedView');
}`

**Comment by mangomaxoasis** [comment]
Hi @gaelcancre 
This method seems outdated, can you reload the latest version of the SDK. Let us know of any issues.
Regards,
Max
