### ISSUE TITLE
404 "not found" error while creating a new natural user

### ISSUE THREAD

**Issue by zakrundrive** [Mangopay/mangopay2-php-sdk#301]
Hello,

Here's my function:

public function CreateMangoUser($firstname,$lastname,$birthdate,$email,$iduser)
    {
        $mangoUser = new \MangoPay\UserNatural();
        $mangoUser->PersonType = "NATURAL";
        $mangoUser->FirstName = $firstname;
        $mangoUser->LastName = $lastname;
	$bday = date_create($birthdate)->setTimezone(timezone_open('UTC'))->modify('midnight')->getTimestamp();
        $mangoUser->Birthday = $bday;
        $mangoUser->Nationality = "FR"; 
        $mangoUser->CountryOfResidence = "RE";
        $mangoUser->Email = $email;
	$mangoUser->IncomeRange = 2;
	$mangoUser->Tag = $iduser;
	try {
		$result = $this->mangoPayApi->Users->Create($mangoUser);
		return $result;
	} catch(MangoPay\Libraries\ResponseException $e) {
		// handle/log the response exception with code $e->GetCode(), message $e->GetMessage() and error(s) $e->GetErrorDetails()
		echo $e->GetCode()." - ".$e->GetMessage();
		var_dump($e->GetErrorDetails());
		return 4;
	} catch(MangoPay\Libraries\Exception $e) {
		// handle/log the exception $e->GetMessage()
		echo $e->GetMessage();
		return 4;
	}
    }

Do you know why I get this error?

my client id is "rundrive"
this code is in prod environment

**Comment by venyii** [comment]
Try to upgrade the lib if you're on an old version (<2.9.2) https://github.com/Mangopay/mangopay2-php-sdk/issues/294#issuecomment-442034957

**Comment by zakrundrive** [comment]
could you please explain to me how can I upgrade the lib?
I used "composer update" but I'm not sure that mangopay lib is upgraded. actually, I still have the same issue.

**Comment by iammichiel** [comment]
Hi, 

As @zakrundrive noted, there was a whitespace in the url of the oauth url in older versions of the library that may have induced 404 errors. Upgrading to a later version of the library corrects it.
