### ISSUE TITLE
Updating from version 2.4.3 to 2.10.0 is critical?

### ISSUE THREAD

**Issue by liorphp** [Mangopay/mangopay2-php-sdk#302]
I started developing on an old system that used this library.
It's critical to update to the current version?

2.4.3 is stable and good version?

Thanks!

**Comment by iammichiel** [comment]
Let's ask this question differently. Is there any reason for you not to upgrade to a newer version? 

As this library follows the semver versioning, there should be no backward-compatibility problems between the 2.4 and the 2.10 version.

**Comment by mickaelpois** [comment]
@liorphp Except any unwanted bugs, switching to a newer verson of our SDK is a good reason :)
We ensure backward-compatibility for all of our minor versions.
The next version without backward-compatibility will be a 3.x one.
