### ISSUE TITLE
codeigniter Class 'MangoPay\MangoPayApi' not found

### ISSUE THREAD

**Issue by danibe83** [Mangopay/mangopay2-php-sdk#304]
Hi all,
I'm new in codeigniter and PHP in general, anyway, I try integrate MangoPay in codeigniter. When I installed php sdk by composer and try to access i see this error message:

**Class 'MangoPay\MangoPayApi' not found**

**The Library**

`require_once './vendor/autoload.php';
class Mangopayservice {
    private $mangoPayApi;
    private $user;

    public function __construct()
    {
        $this->mangoPayApi = new MangoPay\MangoPayApi();
        $this->mangoPayApi->Config->ClientId = '*****';
        $this->mangoPayApi->Config->ClientPassword = '******';
        $this->mangoPayApi->Config->BaseUrl = 'https://api.sandbox.mangopay.com';
        $this->mangoPayApi->Config->TemporaryFolder = ' ';    
    }
    public function add_user()
    {
        //CREATE NATURAL USER
        $user = new MangoPay\UserNatural();
        $user->Email = 'test_natural@testmangopay.com';
        $user->FirstName = "John";
        $user->LastName = "Smith";
        $user->Birthday = 121271;
        $user->Nationality = "FR";
        $user->CountryOfResidence = "ZA";

        $add_userResult = $this->mangoPayApi->Users->Create($user);
        var_dump($add_userResult);
    }
}`

**The controller**

`	public function show()
	{
		$this->load->library('mangopayservice');
		$this->mangopayservice->add_user();
	}`

Can you help me?

**Comment by iammichiel** [comment]
Do you mind sharing the `vendor/autoload.php` file?

**Comment by danibe83** [comment]
@iammichiel sure

require_once __DIR__ . '/composer/autoload_real.php';
return ComposerAutoloaderInit236611059ba60dbafe0a8d7342c25d1e::getLoader();

**Comment by danibe83** [comment]
Hi,
I re-installed mangopay dependencies because was installed wrong. (there are not mangopay folder in vendor folder).  
Now i received this error:  **Undefined variable: mangoPayApi** 
But I declared this variable inside class:
`class Mangopayservice {`
`private $mangoPayApi;`
`private $user;`
`public function __construct()`
`{`
    `$this->mangoPayApi = new MangoPay\MangoPayApi();`
    `$this->mangoPayApi->Config->ClientId = '*****';`
    `$this->mangoPayApi->Config->ClientPassword = '******';`
    `$this->mangoPayApi->Config->BaseUrl = 'https://api.sandbox.mangopay.com';`
    `$this->mangoPayApi->Config->TemporaryFolder = ' ';`    
`}`
`public function add_user()`
`{`
    `//CREATE NATURAL USER`
    `$user = new MangoPay\UserNatural();`
    `$user->Email = 'test_natural@testmangopay.com';`
    `$user->FirstName = "John";`
    `$user->LastName = "Smith";`
    `$user->Birthday = 121271;`
    `$user->Nationality = "FR";`
    `$user->CountryOfResidence = "ZA";`

    `$add_userResult = $this->mangoPayApi->Users->Create($user);`
    `var_dump($add_userResult);`
`}`

Any suggestion?

**Comment by mickaelpois** [comment]
@danibe83 

What about your issue resolution? Had you found some solution?
Feel free to give us some feedback here :)

Mickaël
