### ISSUE TITLE
Use sorting properly in user listing

### ISSUE THREAD

**Issue by danibe83** [Mangopay/mangopay2-php-sdk#307]
Hi all,
I try to sorting user by CreationDate:DESC but seem not sorting data.
`        $pagination = new MangoPay\Pagination();
        $pagination->Page = 1;
        $pagination->ItemsPerPage = 20;
        $pagination->Sort = "CreationDate:DESC";
        $utenti = $this->mangoPayApi->Users->GetAll($pagination);`

**Comment by catacraciun** [comment]
Hi @danibe83 ,
Sorting is not built into the Pagination object. Instead, there's the MangoPay\Sorting class. In your case, sorting would look like the following:
```php
$pagination = new \MangoPay\Pagination();
$pagination->Page = 1;
$pagination->ItemsPerPage = 20;

$sorting = new \MangoPay\Sorting();
$sorting->AddField("CreationDate", \MangoPay\SortDirection::DESC);

$utenti = $this->mangoPayApi->Users->GetAll($pagination, $sorting);
```

Best,
Catalin.

**Comment by danibe83** [comment]
Thankyou!
Another fast question :)
It's possible sorting also PersonType by using SDK?

**Comment by catacraciun** [comment]
@danibe83 Not sure if I understood your question: Do you want to sort the enumeration (just string constants in PHP) PersonType? It has two values, 'NATURAL' and 'LEGAL'.

**Comment by danibe83** [comment]
> @danibe83 Not sure if I understood your question: Do you want to sort the enumeration (just string constants in PHP) PersonType? It has two values, 'NATURAL' and 'LEGAL'.

I mean, I would show only LEGAL persons filtering directly by SDK

**Comment by catacraciun** [comment]
The API does not support this, so neither the SDKs, sorry :)

**Comment by danibe83** [comment]
> The API does not support this, so neither the SDKs, sorry :)

:(  bad news
Could be a new functionality for the future?

**Comment by danibe83** [comment]
Hi, I re-opened because since 3 days I've problem with pagination.
The pagination object get these informations:

PAGINATION OBJECT: MangoPay\Pagination Object
(
    [Page] => 1
    [ItemsPerPage] => 20
    [TotalPages] => 0
    [TotalItems] => 0
    [Links] => Array
        (
            [first] => 
The problem is that in the sandbox account we have almost 3800 records...
This is the code 

        $pagination = new MangoPay\Pagination();
        $pagination->Page = $page;
        $pagination->ItemsPerPage = 20;

        $sorting = new MangoPay\Sorting();
        $sorting->AddField("CreationDate",\MangoPay\SortDirection::DESC);

        $user = $this->mangoPayApi->Users->GetAll($pagination,$sorting);
