### ISSUE TITLE
How to provide custom message to a payin and transfer trxns

### ISSUE THREAD

**Issue by ashok-kr** [Mangopay/mangopay2-php-sdk#308]
Hello,

We need to provide a custom message to the payin and transfer trxns which should be seen on mangopay dashboard and on the API endpoints, I can see the same can be achieved using Tag parameter however your SDK doesn't have any such or similar parameters. Can you
please tell me how to do this?

Regards,
Ashok

**Comment by iammichiel** [comment]
Hi, 

You can set any tag you want on the objects. Simply set the property of the object before saving and the tag will be saved. 

```
$payin = new PayIn();
$payin->Tag = "Whatever you want";
// Set the other properties 

$mango->PayIns->Create($payIn);
```

**Comment by ashok-kr** [comment]
hello,

thanks for the update. We have rather added a property in Transaction class which is a base class of Payin and Transfer classes.

It is working well now.

Regards,
Ashok
