### ISSUE TITLE
Message: Not found  Filename: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php

### ISSUE THREAD

**Issue by priyankapanwar0911** [Mangopay/mangopay2-php-sdk#310]
﻿
An uncaught Exception was encountered
Type: MangoPay\Libraries\ResponseException

Message: Not found

Filename: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php

Line Number: 290

Backtrace:

File: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php
Line: 150
Function: CheckResponseCode

File: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiOAuth.php
Line: 28
Function: Request

File: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthorizationTokenManager.php
Line: 33
Function: CreateToken

File: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthenticationHelper.php
Line: 83
Function: GetToken

File: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthenticationHelper.php
Line: 27
Function: GetHttpHeaderStrong

File: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php
Line: 260
Function: GetHttpHeaderKey

File: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php
Line: 183
Function: GetHttpHeaders

File: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php
Line: 137
Function: BuildRequest

File: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php
Line: 257
Function: Request

File: /home/omarada329/domains/booksbase.rent/public_html/vendor/mangopay/php-sdk-v2/MangoPay/ApiWallets.php
Line: 26
Function: GetObject

File: /home/omarada329/domains/booksbase.rent/public_html/application/modules/dashboard/controllers/Dashboard.php
Line: 5842
Function: Get

File: /home/omarada329/domains/booksbase.rent/public_html/index.php
Line: 292
Function: require_once

**Comment by iammichiel** [comment]
Hi, 

Do you mind adding a little more information? Like for example, have you loaded the `autoload.php` file as required?

**Comment by priyankapanwar0911** [comment]
> Hi,
> 
> Do you mind adding a little more information? Like for example, have you loaded the `autoload.php` file as required?

Hi , thanks for your reply, i added autoload file in vendor root.


following is the code:

<?php

// autoload.php @generated by Composer


require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit9591f2c86f80e0217eef8afa87da6e3b::getLoader();
?>

please  help ,me in this, what else i need to add.

**Comment by iammichiel** [comment]
Oh, I misread your message. The error you are posting is a Not Found Response Exception. Meaning you requested a non-existent item using the API. For instance, you are fetching a wallet but does the wallet really exist?

**Comment by priyankapanwar0911** [comment]
Actually, am not getting this error for wallet only, infact i run any api on server, i get same error. I don't know what i am missing. should i install mangopay again on  server.

**Comment by annamasc** [comment]
I also had trouble with this. And although I was getting the error when I tried to retrieve a resource that didn't exist, I think it's not the best practice to throw an exception in a private method of one of the sdk classes and expect the developers to find it and handle it... What I mean to say is that by reading the php-docs of the Request public method in RestTool this exception is not mentioned, it isn't until I had a request with a non-existent resource id that I found out about this. Furthermore, I'm not even using the Request method in my code but the methods in ApiBase, that in turn use the RestTool class.

**Comment by sayalivaidya** [comment]
Hello,
        **i am using payment gateway with php sdk it is working fine on my local server but same code is on my live server then getting following error Message: Not found,**

An uncaught Exception was encountered
Type: MangoPay\Libraries\ResponseException

Message: Not found

Filename: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php

Line Number: 330

Backtrace:

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php
Line: 152
Function: CheckResponseCode

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php
Line: 110
Function: RunRequest

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiOAuth.php
Line: 28
Function: Request

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthorizationTokenManager.php
Line: 33
Function: CreateToken

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthenticationHelper.php
Line: 68
Function: GetToken

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthenticationHelper.php
Line: 27
Function: GetHttpHeaderStrong

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php
Line: 308
Function: GetHttpHeaderKey

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php
Line: 213
Function: GetHttpHeaders

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php
Line: 109
Function: BuildRequest

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php
Line: 209
Function: Request

File: /home/fruiteefy/public_html/dev/vendor/mangopay/php-sdk-v2/MangoPay/ApiWallets.php
Line: 26
Function: GetObject

File: /home/fruiteefy/public_html/dev/application/controllers/Welcome.php
Line: 423
Function: Get

File: /home/fruiteefy/public_html/dev/index.php
Line: 316
Function: require_once

**Comment by MuraruMihai** [comment]
I can't reproduce

**Comment by mangomaxoasis** [comment]
Hi @sayalivaidya 
Have you confirmed that there is no cache issue on the live serveur?  
Feel free to reach out if the issue persists.
Regards,
Max
