### ISSUE TITLE
Can't have redirect URL with custom payment page

### ISSUE THREAD

**Issue by coqpit** [Mangopay/mangopay2-php-sdk#311]
Hello,

I've got a problem with custom payment pages. 
Can you give me the best solutions to do that ?

``php
$WebPayIn->ExecutionDetails->TemplateURLOptions = new PayInTemplateURLOptions();
$WebPayIn->ExecutionDetails->TemplateURLOptions->PAYLINE = $templateRoute;
``
I don't have any errors but page is blank.

Help please

**Comment by Azim-pix** [comment]
Hi @coqpit 

if want to create custom payment page ,you can go through the card registration process and do direct payin by storing card in mangopay and in return you will get card id ,using the card_id you cab do payin ,,

in you custome payment page you need to pass these think 
CardRegistrationURL in FORM url method POST
PreregistrationData in input hidden field 
AccessKey in input hidden field 
returnUrl from your side .
Card number 14 digit ,you can https://jquerycreditcardvalidator.com/ this
card expiry 01/20
CVV

**Comment by Riwak** [comment]
Hello @coqpit 

Yes exactly @Azim-pix have the right answer ! 🙂  

In fact, we highly recommend you to use instead the Direct PayIn method as it will allow you to have deeply customization on your payment page. 

The documentation is here : https://docs.mangopay.com/endpoints/v2.01/payins#e278_create-a-card-direct-payin

Feel free if you need help,

Best regards,

Audouin,
