### ISSUE TITLE
Ensure https on dashboard

### ISSUE THREAD

**Issue by iammichiel** [Mangopay/mangopay2-php-sdk#312]
Hi, 

I am quite surprised to see the dashboard is actually available using http connections. From a security point of view, that is quite surprising/disturbing. Could it be possible to ensure https when accessing the dashboard? Sounds like a minor change for a major risk IMO.

Thanks,

**Comment by mickaelpois** [comment]
Hi @iammichiel and thanks again for your precious feedback.

Cloudfare allows by default HTTP requests. Even if we're using by default https calls, you could manually use http calls without any restriction.

Our ops team is updating our Cloudfare configuration yet, and will disallow any http request on our dashboard 👍
