### ISSUE TITLE
Mangopay unable to add the bank account of a user

### ISSUE THREAD

**Issue by gkv10** [Mangopay/mangopay2-php-sdk#313]
Hello,

I need some help for create a bank account to users. Indeed when I try to create a bank account I got this error message : 
`` Error Message > MangoPay\Exception Message: Details is not defined or it is not object type.``

In attachment my code.

![mangopay_code](https://user-images.githubusercontent.com/48588621/54427267-51497080-471a-11e9-94ad-8c2c25fece65.PNG)

> I hidden my Clientpassword for this picture

Could you please help me for that ?

Best regards,

**Comment by iammichiel** [comment]
Hi, 

The error is quite explicit. Juste as you created an address using the `Mangopay\Address` class, you have to provide bank-information using the `Mangopay\Details` class. 

As below : 

```
$BankAccount->Details = new BankAccountDetailsIBAN();
$BankAccount->Details->IBAN = $iban;
$BankAccount->Details->BIC = $bic;
```

**Comment by mickaelpois** [comment]
Hi @gkv10 ,
I hope @iammichiel's answer has been helpful 👍

**Comment by gkv10** [comment]
Hello @mickaelpois @iammichiel 
Thank you for your support, indeed the answer helped me.
Regards,
