### ISSUE TITLE
Installing without composer

### ISSUE THREAD

**Issue by kidygetnada** [Mangopay/mangopay2-php-sdk#315]
I am trying to use this SDK without composer, but I cannot get it working, as it requires the logger. I tried downloading the psr/log and placing it into the main folder, but I don't know where to set this path. I would use another logger as described in the readme, but all of them need composer. Can you please elaborate on this and tell us how to use this SDK with avoiding composer completely?

This is the error I get:
Fatal error: Uncaught Error: Class 'Psr\Log\NullLogger' not found in /usr/local/apache2/htdocs/MangoPay/MangoPayApi.php:223 Stack trace: #0 /usr/local/apache2/htdocs/pay.php(30): MangoPay\MangoPayApi->__construct() #1 {main} thrown in /usr/local/apache2/htdocs/MangoPay/MangoPayApi.php on line 223

**Comment by iammichiel** [comment]
Hi, 

Let me elaborate on the composer logger dependency. As for any other language, `composer` is the de-facto dependency manager. Same as yarn, npm, maven, sbt, you name it, composer will handle download/configuration of every dependency of your application. Not using composer on a php project with multiple dependencies is like using a bike without pedals. It works but is pretty useless.

Now, if you are familiar with PHP, you might know there is a group of users that try to define standards for PHP project. This is called the PHP-FIG. They edit standards called PSR's. There is one existing for logging library, called the psr/log which defines an interface which loggers should implement. 

In this SDK, there is no hard-requirement for the logger. Users a free to use a null logger or a file logger, or logstash or whatever. The only requirement this library has is the stadnard psr/log library for the interface. 

You are free to use whatever you want, however you want, but if you go against all best practices and take security risks by not using composer, that is your problem and up to you to make things work.
