### ISSUE TITLE
Company Number support for Legal User

### ISSUE THREAD

**Issue by guillaumecauchois** [Mangopay/mangopay2-php-sdk#316]
Hi,

As said in this part of the documentation (https://docs.mangopay.com/guide/user-verification), I need provide a CompanyNumber to create a valid LegalUser. But the sdk not allow to set this data (attribute not exist in the class)

Is it still necessary to provide it to get the regular state for my users ?

Thank you for your help !

**Comment by mickaelpois** [comment]
Hello @guillaumecauchois, thanks for your question !
We will shortly update our SDK (in a few days) to provide a way to set this data for Legal User registration and update.

This value is not yet mandatory for KYC validation, but will become:
- From April 30th if your account is not activated in production yet.
- In october if you're already an activated client.
