### ISSUE TITLE
Cancel link on 3D Secure box

### ISSUE THREAD

**Issue by kermit-lyon** [Mangopay/mangopay2-php-sdk#317]
Hi. I have a probleme with the 3DS process. Here is the case : 

I properly initiate a payin > 50 Euros with a valid url for SecureModeReturnURL.
Mangopay returns me a 3DS URL on SecureModeRedirectURL, OK
I redirect the customer to the 3DS URL

Here is the probleme : 

When I fill the right 3DS information OR click onto the "Cancel" link on the 3DS window, my customer is redirected to the SAME SecureModeReturnURL. I have no idea how to determinate if the transaction has passed the 3DS or has been "3DS cancelled".

I tried to check the transaction ID after that, to block the process if 3DS is not ok, but i don't think this is the best method.

My question is : how to configure the URL of the 3DS cancel link ? 
OR
Is there an url server-to-server called by the process ? 

Best regards and sorry for my bad english :)

**Comment by kermit-lyon** [comment]
![1554306857](https://user-images.githubusercontent.com/18679828/55493601-8a9a3f80-5639-11e9-93ca-48ce9d71cc36.jpg)

Here is a screenshot of the cancel link

**Comment by iammichiel** [comment]
I am not sure about this but I guess the preAuthorization code might simply be missing in the query ?

For example, when successfully redirecting to the RedirectPage : 

```
http://web.site/return-url?preAuthorization=1234
```

Whilst in case of error : 

```
http://web.site/return-url
```

In any case, you could simply check the status of the pre-authorization to see if it was cancelled.

**Comment by kermit-lyon** [comment]
Hi iamicheil : I do make a direct payin without preauth. In this case, the two urls are the same, 3DS validated or not :( The TransactionId is return in both case.

I can check the status of the Payin, that's I do at this time. Do you thin it is the good way to solve the "cancel" pb ?

**Comment by iammichiel** [comment]
Yeah, sure. I think this remains an edge case of your implementation. Not that many users will cancel their pre-authorization. Checking the payin status will work in this case.

**Comment by kermit-lyon** [comment]
Not that many, but you know that, 90% of computers probleme are between chair and keyboard ...

**Comment by kermit-lyon** [comment]
Thank you for your advises !
