### ISSUE TITLE
BankAccount ID from User ID

### ISSUE THREAD

**Issue by wppatrickk** [Mangopay/mangopay2-php-sdk#319]
Hello,

This is more of a support question.

I am trying to get the Bank Account ID of the user from user id. I tried searching around and couldn't find anything to get the bank account details from user id. Did a view user API call as well, but it just returns the personal details of the user.

Thanks.

**Comment by iammichiel** [comment]
Hi ! 

You can actually get all bank-accounts of a given user very easily. There is a specific api entry-point. 

```php
$bankAccounts = $api->Users->GetBankAccounts($userId);
```

This will return an array of `BankAccount` which contains all details of the users bankaccounts. 
Does this answer your question?
