### ISSUE TITLE
Logger replacement (without composer)

### ISSUE THREAD

**Issue by kidygetnada** [Mangopay/mangopay2-php-sdk#322]
Is it possible to manually add any logger when initialising mangopay api? I am having trouble getting everything started without composer. Your README saying to only include autoloader.php is not correct as I get errors. Could you please provide a quick fix on either how to:

1. Disable logger function all together; or
2. Manually upload any simple logger (and dependency files) to the mangopay directory and initialise it together with mangopay autoloader?

[Stackoverflow](https://stackoverflow.com/questions/55845274/how-to-use-logger-without-composer-and-namespaces#comment98353283_55845274)

@mickaelpois @catacraciun I am out of options.. I would be very grateful for any suggestions.

**Comment by iammichiel** [comment]
Hello, 

First of all, let me express my concerns about not using composer. Handling security updates of critical libraries is going to be very complicated without composer and thus **exposing your application to security breaches.** 

However, if you are ready to take that risk and go against best practices and do not want to use composer, you can always initialise the library without a logger, you simply have to include the correct `autoload.php` file. 

Let me also add your comment from Stackoverflow :  
```
I am only asking here because I am not getting any response from the developers. 
```

You posted your question a thursday. You have got an answer 4 days later including weekend. You might need to reconsider the way open-source works.
