### ISSUE TITLE
Code erreur 09101

### ISSUE THREAD

**Issue by bebar974** [Mangopay/mangopay2-php-sdk#323]
Bonjour,

J'ai une erreur 09101 lors de mes tests sur **Sandbox**, je n'ai pas touché les paramètres d'authentification et j'utilise une carte de test 

```
CardRegistration {#1069 ▼
  +UserId: "64494412"
  +CardType: "CB_VISA_MASTERCARD"
  +AccessKey: "1X0m87dmM2LiwFgxPLBJ"
  +PreregistrationData: "YkgVxL1yNY4ZOfKtqEew_Vq3EXS9jJkLnQjP68I_dt48xc0CuN205zueBA48au49S4wCy-yiraxeE65tmxOe8A"
  +CardRegistrationURL: "https://homologation-webpayment.payline.com/webpayment/getToken"
  +CardId: null
  +RegistrationData: "errorCode=09101"
  +ResultCode: null
  +ResultMessage: null
  +Currency: "EUR"
  +Status: "CREATED"
  +Id: "64499491"
  +Tag: null
  +CreationDate: 1556272902
}
```

Pourriez-vous m'aider ?

Cordialement,

**Comment by iammichiel** [comment]
Bonjour, 

L'erreur 09101 indique un problème de username/password. As-tu pu vérifier les différentes informations de connexion? 

De quelle facon crées-tu l'objet API? 

Il faut bien préciser toutes les informations : 

```php

  $mangopay = new MangoPayApi();
  $mangopay->Config->ClientId = $clientId;
  $mangopay->Config->ClientPassword = $clientPassword;
  $mangopay->Config->TemporaryFolder = $temporaryFolder;
  $mangopay->Config->BaseUrl = $baseUrl;
```

**Comment by bebar974** [comment]
Bonjour,
Cela fait plus d'un an que cela marchait et je n'ai pas modifié les paramètres de connexion depuis.
Je me base bien sur ce schéma et j'utilise bien deux URLs différentes.
Le problème n'était pas présent en production et je n'ai plus celui actuellement sur la SANDBOX.
Merci pour votre réponse.
Cordialement

**Comment by iammichiel** [comment]
Effectivement, la sandbox n'est pas des plus stable chez Mangopay. Je confirme également qu'il y avait bien un problème sur les card-registration en Sandbox le 26. 

Vous pouvez vous abonner à la status-page de Mangopay pour être averti en temps réel des dysfonctionnements:  http://status.mangopay.com/incidents/j7s5h7xs3dfh

**Comment by bebar974** [comment]
Merci pour ce lien, j'en prends note.
Bonne journée

**Comment by walidthebest** [comment]
Bonjour, 
J'ai l'impression d'avoir le même problème lors de mes test sur Sandbox. Je reçois l'error 09101. 
Voici la requête que j'envoie en POST :
`
url = card_registration.card_registration_url

data = {
    "accessKeyRef" : card_registration.access_key,
    "data" : card_registration.preregistration_data,
    "cardNumber" : XXXXXXXXXXXXX,
    "cardExpirationDate" : XXXX,
    "cardCvx" : XXX,
}
`
Ou card_registration est la demande d'enregistrement. 

Pourriez-vous m'aider ? 

Merci
