### ISSUE TITLE
msngopay api is not working 

### ISSUE THREAD

**Issue by Mfaisal541** [Mangopay/mangopay2-php-sdk#325]
when i am creating a legal user on mango pay api then api si not working and throw exception 

like this 

Warning: Creating default object from empty value in /home/leadconcept/public_html/clients/abrar/freelancer/wp-content/themes/superlist-child/vpb_create_mangopay.php on line 204

Warning: Creating default object from empty value in /home/leadconcept/public_html/clients/abrar/freelancer/wp-content/themes/superlist-child/vpb_create_mangopay.php on line 211

MangoPay\ResponseException Code: 404
-------------------------------
Message: Not found
-------------------------------
Details: 
-------------------------------

**Comment by iammichiel** [comment]
Hi, 

Could you share some more code ? Helping you with so few information is going to be difficult...

**Comment by mickaelpois** [comment]
Hello @Mfaisal541 ,

Are you using our Wordpress plugin ? (your website seems to be based on WP)
Feel free to share more information about your issue on our Wordpress support forum [here](https://wordpress.org/support/plugin/mangopay-woocommerce/)

Have a nice day ! 

Mickaël
