### ISSUE TITLE
Missing UBO related EventTypes

### ISSUE THREAD

**Issue by vincentbab** [Mangopay/mangopay2-php-sdk#327]
The class \MangoPay\EventType is missing some constants for UBO related hooks:

UBO_DECLARATION_CREATED,
UBO_DECLARATION_VALIDATION_ASKED,
UBO_DECLARATION_REFUSED,
UBO_DECLARATION_VALIDATED,
UBO_DECLARATION_INCOMPLETE

**Comment by mickaelpois** [comment]
Live thanks to 2.12.1 version.
Thanks for your add @vincentbab !
