### ISSUE TITLE
3d Secure payment mode

### ISSUE THREAD

**Issue by kidygetnada** [Mangopay/mangopay2-php-sdk#330]
I am trying to test payments above 50eur and I am not getting the SecureMode parameter.

This is my code:

`    $createdWallet = $mangoPayApi->Wallets->Create($wallet);

    // create pay-in CARD DIRECT
    $payIn = new \MangoPay\PayIn();
    $payIn->CreditedWalletId = $createdWallet->Id;
    $payIn->AuthorId = $mangosource;
    $payIn->DebitedFunds = new \MangoPay\Money();
    $payIn->DebitedFunds->Amount = $decvalue;
    $payIn->DebitedFunds->Currency = "EUR";
    $payIn->Fees = new \MangoPay\Money();
    $payIn->Fees->Amount = $decvalue * 0.03 + 33;
    $payIn->Fees->Currency = "EUR";
    
    $payIn->SecureMode = "FORCE";

    $payIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsCard();
    $payIn->PaymentDetails->CardType = $card->CardType;
    $payIn->PaymentDetails->CardId = $card->Id;

    $payIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
    $payIn->ExecutionDetails->SecureModeReturnURL = 'https://www.something.com/#'.$oid;

    $createdPayIn = $mangoPayApi->PayIns->Create($payIn);
    $chargeID = $createdPayIn->Id;

    if ($createdPayIn->Status == \MangoPay\PayInStatus::Succeeded) { 
    mysqli_stmt_bind_param($instra, "s", $chargeID); mysqli_stmt_execute($instra); 
    } else { echo "I don't get anything here!!!".$createdPayIn->ExecutionDetials->SecureModeNeeded.$createdPayIn->SecureModeRedirectURL.$createdPayIn->Status." - ".$createdPayIn->ResultCode;
    }; } catch (\MangoPay\Libraries\ResponseException $e) { echo $payIn->ExecutionDetails->SecureModeRedirectURL; print_r($e->GetErrorDetails()); };

**Comment by kidygetnada** [comment]
@mickaelpois Can you just confirm this is the right endpoint: $createdPayIn->ExecutionDetials->SecureModeNeeded ?

**Comment by iammichiel** [comment]
Hi, 

I do confirm your code looks ok. There a multiple settings working for the 3DS support. First of all, there is an account wide setting. By default, I think it triggers 3DS above 50€. 
Secondly, you as a dev, can force the usage of 3DS using the flag, `SecureMode`. 

```php
$CardPreAuthorization->SecureMode = 'FORCE';
```

Last but not least, the 3DS is not always very stable in sandbox. Might be related to sandbox errors...
