### ISSUE TITLE
Error when Creating a Bankwire Direct PayIn

### ISSUE THREAD

**Issue by jhfyang** [Mangopay/mangopay2-php-sdk#331]
Currently using; 
`mangopay/php-sdk-v2                      2.11.0               SDK PHP for Mangopay api V2`

I am trying to crreate a Bankwire Direct PayIn

``` 
       $payIn = new PayIn();

        $payIn->AuthorId = $this->utipUserId;

        $payIn->CreditedWalletId = $this->utipWalletId;
        $payIn->CreditedUserId = $this->utipUserId;

        $payIn->PaymentType = PayInPaymentType::BankWire;
        $payIn->PaymentDetails = new MangoPay\PayInPaymentDetailsBankWire();

        $payIn->PaymentDetails->DeclaredDebitedFunds = new Money();
        $payIn->PaymentDetails->DeclaredDebitedFunds->Amount = $debitedAmount;
        $payIn->PaymentDetails->DeclaredDebitedFunds->Currency = 'EUR';

        $payIn->PaymentDetails->DeclaredFees = new Money();
        $payIn->PaymentDetails->DeclaredFees->Amount = ($debitedAmount*1000)/5;
        $payIn->PaymentDetails->DeclaredFees->Currency = 'EUR';

        $payIn = $this->mangoPayApi->PayIns->Create($payIn);
```

However when doing this I get 

> ExecutionDetails is not defined or it is not object type

Which is normal when looking at the code of the mangopay-php-sdk:

```
    private function GetExecutionKey($payIn)
    {
        if (!isset($payIn->ExecutionDetails) || !is_object($payIn->ExecutionDetails)) {
            throw new Libraries\Exception('ExecutionDetails is not defined or it is not object type');
        }

        $className = str_replace('MangoPay\\PayInExecutionDetails', '', get_class($payIn->ExecutionDetails));
        return strtolower($className);
    }

```

However as I look the mangopay API doc there is no instructions about ExecutionDetails for a Bankwire Direct Payin;

https://docs.mangopay.com/endpoints/v2.01/payins#e280_create-a-bankwire-direct-payin

>Tag string  OPTIONAL
Custom data that you can add to this item

>AuthorId string  REQUIRED
A user's ID

>CreditedUserId string  OPTIONAL
The user ID who is credited (defaults to the owner of the wallet)

>CreditedWalletId string  REQUIRED
The ID of the wallet where money will be credited

>DeclaredDebitedFunds Money  REQUIRED
The declared debited funds

>DeclaredFees Money  REQUIRED
The declared fees

So I have tried too add the ExecutionDetails like in the `PayInsTest.php`

```

        $payIn = new PayIn();

        $payIn->AuthorId = $this->utipUserId;
        $payIn->CreditedWalletId = $this->utipWalletId;

        $payIn->CreditedUserId = $this->utipUserId;

//        $payIn->PaymentType = PayInPaymentType::BankWire;
        $payIn->PaymentDetails = new MangoPay\PayInPaymentDetailsBankWire();

        $payIn->PaymentDetails->DeclaredDebitedFunds = new Money();
        $payIn->PaymentDetails->DeclaredDebitedFunds->Amount = 10000;
        $payIn->PaymentDetails->DeclaredDebitedFunds->Currency = 'EUR';

        $payIn->PaymentDetails->DeclaredFees = new Money();
        $payIn->PaymentDetails->DeclaredFees->Amount = (10000*1000)/5;
        $payIn->PaymentDetails->DeclaredFees->Currency = 'EUR';

        // execution type as DIRECT
//        $payIn->ExecutionType = PayInExecutionType::Direct;
        $payIn->ExecutionDetails = new PayInExecutionDetailsDirect();
        $payIn->ExecutionDetails->Culture = "FR";

        $payIn = $this->mangoPayApi->PayIns->Create($payIn);
```

And now I get this error message: 

```
{"Message":"Internal Server Error","Errors":null,"Id":"82d7e4f8-9773-4e50-86ac-7dcc263ad4ab#1559134098","Date":1559134099,"Type":"other"}
```

**Comment by jhfyang** [comment]
I have solved this issue by putting :
```
        $payIn->PaymentDetails->DeclaredFees->Amount = 0;
```
Can somebody help me clarify why the Feed need to be at 0 ? How may I pay the fees from the PayIn ? since the

**Comment by Aurel4012** [comment]
If you want feed put your amount you wish exemple 300 for 3 euros. 
Personnaly to set feed amount i make function to take percentage of amount when user do Payout.

**Comment by mickaelpois** [comment]
Hi @jhfyang,

You were talking about paying MANGOPAY's fees thanks to `Fees` parameter on your Payin?
There's two distinct fees concepts:
* Fees you want to charge to your users (which may be higher or lower than the fees you owe us)
* Fees you owe to MANGOPAY at the end of each month

Either you collect fees when processing some transactions (Payin, Transfer or Payout) and we will charge each month your wallet fees of the good amount related to your activity via our service *or* if you do not wish to collect fees via our service, we will ask you to use our billing application for direct debit on a credit card.

Feel free to ask our support / finance team for more details if it remains unclear to you.

Mickaël

**Comment by jhfyang** [comment]
Thanks for your response,

I have solved this issue, and actually I have been giving a fees amount bigger than our Transaction thus giving me an error 

Sorry it was stupid from me
