### ISSUE TITLE
Card Registration errorCode=02626

### ISSUE THREAD

**Issue by wppatrickk** [Mangopay/mangopay2-php-sdk#332]
Hello,

I have setup a page on my website to enable card registration. I have copied the exact code from the sample code (https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/workflow/scripts/card-reg.php), however when I submit the form. I get the the following error code

"errorCode=02626"

I looked up the MangoPay error code list here https://docs.mangopay.com/guide/errors and it says that it's an invalid date.

I have tried both both formats for the expiry date, 10/21 as well as 1021, but neither seem 
to work?

Regards.

**Comment by mickaelpois** [comment]
Hello @wppatrickk ,

Could you tell me if you've found where your issue was?
⚠️ ExpiryDate on our sample code is currently outdated (1217, and this is the right format)

Mickaël
