### ISSUE TITLE
Code error Internal server error id Mangopay 597045302 

### ISSUE THREAD

**Issue by FlorianLuckey** [Mangopay/mangopay2-php-sdk#335]
"message" => "Response JSON : {"Message":"Internal Server Error","Type":"other","Id":"d182ac30-32f8-442b-bfdb-d34b98cc6f72#1563292184","Date":1563292185.0,"errors":null}",

+records: [
       [
         "level" => "debug",
         "message" => "New request",
         "context" => [],
       ],
       [
         "level" => "debug",
         "message" => "FullUrl : https://api.mangopay.com/v2.01/luckey/payouts/bankwire/",
         "context" => [],
       ],
       [
         "level" => "debug",
         "message" => "RequestType : POST",
         "context" => [],
       ],
       [
         "level" => "debug",
         "message" => """
           HTTP Headers : Array\n
           (\n
               [0] => Content-Type: application/json\n
               [1] => User-Agent: MangoPay V2 PHP/2.12.1\n
               [2] => Authorization: bearer a4b1702ddbaf42079debc62cda95e2a1\n
           )\n
           """,
         "context" => [],
       ],
       [
         "level" => "debug",
         "message" => """
           RequestData object :Array\n
           (\n
               [DebitedWalletId] => 597116786\n
               [BankAccountId] => computing_5cfe6684770ba\n
               [BankWireRef] => 31YX\n
               [AuthorId] => 597045302\n
               [DebitedFunds] => MangoPay\Money Object\n
                   (\n
                       [Currency] => EUR\n
                       [Amount] => 19100\n
                   )\n
           \n
               [Fees] => MangoPay\Money Object\n
                   (\n
                       [Currency] => EUR\n
                       [Amount] => 19100\n
                   )\n
           \n
           )\n
           """,
         "context" => [],
       ],
       [
         "level" => "debug",
         "message" => "RequestData JSON :{"DebitedWalletId":"597116786","BankAccountId":"computing_5cfe6684770ba","BankWireRef":"31YX","AuthorId":"597045302","DebitedFunds":{"Currency":"EUR","Amount":19100},"Fees":{"Currency":"EUR","Amount":19100}}",
         "context" => [],
       ],
       [
         "level" => "debug",
         "message" => "Response JSON : {"Message":"Internal Server Error","Type":"other","Id":"d182ac30-32f8-442b-bfdb-d34b98cc6f72#1563292184","Date":1563292185.0,"errors":null}",
         "context" => [],
       ],
       [
         "level" => "debug",
         "message" => """
           Decoded object : stdClass Object\n
           (\n
               [Message] => Internal Server Error\n
               [Type] => other\n
               [Id] => d182ac30-32f8-442b-bfdb-d34b98cc6f72#1563292184\n
               [Date] => 1563292185\n
               [errors] => \n
           )\n
           """,
         "context" => [],
       ],
     ],

**Comment by mickaelpois** [comment]
Hello @FlorianLuckey,

Your `bankaccountID` seems to be wrong (computing_5cfe6684770ba) as we're waiting for an numerical ID, not a alphanumerical one.
You need to provide us ID linked to the Bankaccount you should have previously created (linked to the user who's Bankaccount owner).

I hope this is helpful, feel free to ask any question related to your issue, I'll be very pleased to answer.

Mickaël
