### ISSUE TITLE
UpdateUBO

### ISSUE THREAD

**Issue by tsoko17** [Mangopay/mangopay2-php-sdk#337]
Hi everyone,

Something that I didn't catch :(

In case that our declaration UBO return INCOMPLETE, we need to update UBO profile.
In the official doc, we need 4 parameters : 
https://docs.mangopay.com/endpoints/v2.01/ubo-declarations#e1030_update-a-ubo
In php-sdk, 2 parameters to update UBO: 
https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/ApiUboDeclarations.php
`UpdateUbo($userId, $uboDeclarationId, $ubo)`
In official docs, all elements can be updated for a UBO so how can we update the right one UBO to validate declaration UBO if we do not define ID UBO to update ?
Do not forget that we can add 1 to 4 UBO profile ! 
https://docs.mangopay.com/endpoints/v2.01/ubo-declarations#e1027_create-a-ubo
`You should create at least 1 UBO (maximum 4 UBOs)`
So ID UBO isn't necessary to update ?

Tx

**Comment by matthieuuu** [comment]
Hello @tsoko17 

I'll try to help you for this part : `UpdateUbo($userId, $uboDeclarationId, $ubo)` :
- `$userId` : user's UserID
- `$uboDeclarationId` : UBO Declaration ID
- `$ubo` : the UBO object

About the last attribute `$ubo`, it must contain the UBO ID you are updating, for example :
```$ubo = new \MangoPay\Ubo();
$ubo->Id = 1234; //UBO ID you are updating
$ubo->FirstName = "Bob"; //I need to update the Firstname of UBO 1234
$mangoPayApi = new \MangoPay\MangoPayApi();
$mangoPayApi->UboDeclarations->UpdateUbo($userId, $uboDeclarationId, $ubo);```

Matt

**Comment by mickaelpois** [comment]
Thanks @matthieuuu for your helping answer !

@tsoko17 You can also have a look [here](https://github.com/Mangopay/mangopay2-php-sdk/blob/35518876c2973a5f063e1d6ff4af535d2cac91ed/tests/cases/UboDeclarationsTest.php#L86) to know how to use UBO update.

`UpdateUbo` function will call our generic `SaveObject` function which will get directly ID from your UBO object and update it properly (here is your 3rd parameter you're looking for I guess).

If I've well understood, you last expected parameter is just your clientID, which is automatically added to every request you're processing through this SDK thanks to your configuration info you've setup at the very beginning.

I hope this is helpful, please feel free to ask any other questions :)

Mickaël

**Comment by tsoko17** [comment]
Hi guys !
Thanks a lot @matthieuuu @mickaelpois for your help.
Now, everythings works fine.
Have a great day.
