### ISSUE TITLE
There is no isActive support in Ubo object

### ISSUE THREAD

**Issue by ostrolucky** [Mangopay/mangopay2-php-sdk#338]
So this is what your documentation at https://docs.mangopay.com/endpoints/v2.01/ubo-declarations#e1030_update-a-ubo says

![Screenshot 2019-07-30 at 16 13 01](https://user-images.githubusercontent.com/496233/62136741-0d2fc480-b2e5-11e9-96a6-242c68100bc0.png)

But there is no such thing in https://github.com/Mangopay/mangopay2-php-sdk/blob/35518876c2973a5f063e1d6ff4af535d2cac91ed/MangoPay/Ubo.php

**Comment by matthieuuu** [comment]
Hey @ostrolucky 

Although it's not inside the `Ubo.php` file you mentionned, you may use the `UpdateUbo` API method like this:
```
$ubo = new \MangoPay\Ubo();
$ubo->Id = 1234; //UBO ID you are updating
$ubo->isActive = false; //Remove the UBO from the UBO Declaration $uboDeclarationId
$mangoPayApi = new \MangoPay\MangoPayApi();
$mangoPayApi->UboDeclarations->UpdateUbo($userId, $uboDeclarationId, $ubo);
```

It should work!
Matt

**Comment by ostrolucky** [comment]
That's very awkward design, but thank you, that helped.

**Comment by leihog** [comment]
Even though I would actually prefer if MangoPay used camelCase instead of PascalCase, it would be a bit inconsistent to add **isActive** with a lower case _i_ when all other properties are capitalized. Something to fix in a future version?

**Comment by gaetan-petit** [comment]
@leihog yep totally inconsistent, but it just wrap the api parameter.
