### ISSUE TITLE
RestTool.php // FIXME This can also fail hard and is not checked.

### ISSUE THREAD

**Issue by Nicolas-Bouteille** [Mangopay/mangopay2-php-sdk#341]
Hello,

Lately we had a problem when trying to send a KYC Document. The process would take too long and fail.
I narrowed down the problem to some MangoPay code below from RestTool.php:

```
if (in_array(self::$_JSON_HEADER, $httpHeaders)) {
  // FIXME This can also fail hard and is not checked.
  $this->_requestData = json_encode($this->_requestData);
  $this->logger->debug('RequestData JSON :' . print_r($this->_requestData, true));
  if ($this->_root->Config->DebugMode) {
    $logClass::Debug('RequestData JSON', $this->_requestData);
  }
}
```
I noticed that someone already commented:
 // FIXME This can also fail hard and is not checked.

The error I was receiving in my logs was :
Column 'message' cannot be null: INSERT INTO @watchdog

So my fix so far is to add the following statement : 
`if ($this->_requestData != null) {`

Maybe to reproduce the error try a heavy file?

**Comment by mangomaxoasis** [comment]
Merged
