### ISSUE TITLE
UboDeclarations->CreateUbo Method not allowed. The requested resource does not support http method 'POST'.

### ISSUE THREAD

**Issue by Nicolas-Bouteille** [Mangopay/mangopay2-php-sdk#346]
Hello,

I am trying to implement the new UBO Declaration system. I have successfully created the UBO declaration and stored its ID.

Now I am trying to create and attach UBOs to it. Basically in a foreach loop, I create a Ubo Object, fill its properties and then try to create it on MangoPay API using UboDeclarations->CreateUbo()
```
$ubo_to_create = new MangoPay\Ubo();
$ubo_to_create->FirstName = $first_name;
$ubo_to_create->LastName = $last_name;
$ubo_to_create->Address = $address;
$ubo_to_create->Nationality = $nationality;
$ubo_to_create->Birthday = $birthday_timestamp;
$ubo_to_create->Birthplace = $birthplace;

$created_ubo = $this->mangoPayApi->UboDeclarations->CreateUbo($user_id, $ubo_declaration_id, $ubo_to_create);
```
I get the following response error : 
Method not allowed. The requested resource does not support http method 'POST'.

What I am missing or doing wrong?
Thank you!

**Comment by matthieuuu** [comment]
Hello @Nicolas-Bouteille,

I use the same method as you and I get no error :
```$created_ubo = $this->mangoPayApi->UboDeclarations->CreateUbo($user_id, $ubo_declaration_id, $ubo_to_create);```

Have you tried to put `DebugMode` to `true` in order to have more info?
If you are in sandbox environment, if I remember correctly, you first have to ask the support to enable UBO on your account. But your error seems more HTTP oriented...

Matt

**Comment by Nicolas-Bouteille** [comment]
Hello Matthieu,

Thank you for your feedback !
I think UBO is already enabled on my sandbox because I have successfully created the UBO Declaration via the SDK / API (step 1) and I can see it on the sandbox dashboard.
I have not tried the DebugMode though so I will try it!

Could you send me some of the code that you use in order to create the UBO Declaration, send the UBOs and then ask for validation ?

**Comment by matthieuuu** [comment]
Sure, here we go:

- Create UBO Declaration:
```
$this->mangoPayApi->UboDeclarations->Create($userId);
```

- Create UBO in UBO Declaration:
```
$ubo = new \MangoPay\Ubo();
$ubo->FirstName = $ubo_data['FirstName'];
$ubo->LastName = $ubo_data['LastName'];
$ubo->Address = new \MangoPay\Address();
$ubo->Address->AddressLine1 = $ubo_data['Address']['AddressLine1'];
$ubo->Address->AddressLine2 = $ubo_data['Address']['AddressLine2'];
$ubo->Address->City = $ubo_data['Address']['City'];
$ubo->Address->Region = $ubo_data['Address']['Region'];
$ubo->Address->PostalCode = $ubo_data['Address']['PostalCode'];
$ubo->Address->Country = $ubo_data['Address']['Country'];
$ubo->Nationality = $ubo_data['Nationality'];
$ubo->Birthday = $ubo_data['Birthday'];
$ubo->Birthplace = new \MangoPay\Birthplace();
$ubo->Birthplace->City = $ubo_data['Birthplace']['City'];
$ubo->Birthplace->Country = $ubo_data['Birthplace']['Country'];

$this->mangoPayApi->UboDeclarations->CreateUbo($userId, $UboDeclarationId, $ubo);
```

- Ask for UBO Validation:
```
$this->mangoPayApi->UboDeclarations->SubmitForValidation($userId, $UboDeclarationId);
```


Hope it helps!

**Comment by Nicolas-Bouteille** [comment]
Thanks !

**Comment by Nicolas-Bouteille** [comment]
I haven't had the time to have a look at it yet, but I've been thinking about something...
I don't have SSL enabled locally for testing... 
maybe The requested resource does not support http method 'POST' means sending UBO via HTTP is not allowed and requires HTTPS ??
Do you have SSL enabled on your side?

**Comment by matthieuuu** [comment]
I think the `DebugMode` will help you to understand what's wrong. My development environment is not in SSL, but I call mangopay through HTTPS tho:
```
$this->mangoPayApi->Config->BaseUrl = "https://api.sandbox.mangopay.com";
```

**Comment by Nicolas-Bouteille** [comment]
Thank you for your help Matthieu.
By setting $this->mangoPayApi->Config->DebugMode = true; I could see that the full API url called was ending with /ubodeclaration//ubos where it should be /ubodeclaration/SOME_ID/ubos
Which helped me understand that my $ubo_declaration_id parameter was null. I was not retrieving it properly.
Maybe there should be a check in function CreateUbo($userId, $uboDeclarationId, $ubo) that $uboDeclarationId is not null or empty and an Exception Thrown... will open a separate issue for that.
It now works for me now :) thank you again!
