### ISSUE TITLE
Code erreur 09101 

### ISSUE THREAD

**Issue by walidthebest** [Mangopay/mangopay2-php-sdk#347]
Bonjour, 
J'ai l'impression d'avoir le même problème lors de mes test sur Sandbox. Je reçois l'error 09101. 
Voici la requête que j'envoie en POST :
`
url = card_registration.card_registration_url

data = {
    "accessKeyRef" : card_registration.access_key,
    "data" : card_registration.preregistration_data,
    "cardNumber" : XXXXXXXXXXXXX,
    "cardExpirationDate" : XXXX,
    "cardCvx" : XXX,
}
`
Ou card_registration est la demande d'enregistrement. 

Pourriez-vous m'aider ? 

Merci

_Originally posted by @walidthebest in https://github.com/Mangopay/mangopay2-php-sdk/issues/323#issuecomment-524789906_

**Comment by mickaelpois** [comment]
Il arrive épisodiquement que notre système d'enregistrement soit indisponible pour de courte durées (et que certains messages soient peu explicites).

Dans ce cas précis, et comme indiqué dans l'issue #323 il est nécessaire de retenter un enregistrement ultérieurement.
