### ISSUE TITLE
Deleting UboDeclarations

### ISSUE THREAD

**Issue by leihog** [Mangopay/mangopay2-php-sdk#350]
There is currently no (that I can see) way of removing a UboDeclaration.

While I understand that you don't want to allow us to delete a UboDeclaration that is validated,
we should be able to delete one that isn't pending validation or validated yet. I.e. we haven't asked for it to be validated.

If nothing else it would be really useful to be able to delete in the sandbox so we could perform automated integration tests against your sandbox without creating new users each time.

**Comment by mickaelpois** [comment]
Hello @leihog,

Nothing is planned yet regarding data deletion, neither in Sandbox nor in production.
We could think about a dedicated status which coud make a declaration unusable, but not in the short-term.

Mickaël
