### ISSUE TITLE
View UboDeclaration in progress without specifying ID

### ISSUE THREAD

**Issue by leihog** [Mangopay/mangopay2-php-sdk#351]
Since we can only have one UboDeclaration in progress at once it would be convenient
if we didn't have to specify an ID in order to view the "active" one.

Another small fix that would make things easier is if the error reported by CreateUbo when you already have one in progress i.e. "You can not create a declaration because you already have a declaration in progress" contained the ID of the active UboDeclaration.

**Comment by mickaelpois** [comment]
Added on 2.13.0
