### ISSUE TITLE
Error code 009103 with IDEAL 

### ISSUE THREAD

**Issue by jomino** [Mangopay/mangopay2-php-sdk#356]
Hello,
as in 
https://docs.mangopay.com/endpoints/v2.01/payins#e269_create-a-card-web-payin

**when I try the iDeal card type, the return code is 009103.**

And the doc is not clear about

> You do not need a specific test account to use iDeal in sandbox – just choose "ING" from the two options on the RedirectURL ...

but the "RedirectURL" property is returned as NULL

{
"CreditedWalletId":"68360389",
"PaymentType":"CARD",
"PaymentDetails":
	{
		"CardType":"IDEAL",
		"CardId":null,
		"StatementDescriptor":"company_name"
	},
"ExecutionType":"WEB",
"ExecutionDetails":
	{
		"RedirectURL":null,
		"ReturnURL":"https:\/\/...my_web_site...\/redirect\/149cc7ba-7ce7-4e82-a5ed-b3220595761e?transactionId=68570257",
		"TemplateURL":"https:\/\/api.sandbox.mangopay.com\/Content\/PaylineTemplate?rp=78714f24de7b42c4&transactionId=68570257",
		"TemplateURLOptions":null,
		"Culture":"EN",
		"SecureMode":"DEFAULT"
	},
"AuthorId":"68360388",
"CreditedUserId":"68360388",
"DebitedFunds":{"Currency":"EUR","Amount":1200},
"CreditedFunds":{"Currency":"EUR","Amount":1200},
"Fees":{"Currency":"EUR","Amount":0},
"Status":"FAILED",
"ResultCode":"009103",
"ResultMessage":"PSP configuration error",
"ExecutionDate":null,
"Type":"PAYIN",
"Nature":"REGULAR",
"DebitedWalletId":null,
"Id":"68570257",
"Tag":"149cc7ba-7ce7-4e82-a5ed-b3220595761e",
"CreationDate":1568472012
}

Thank in advance
Olivier

**Comment by Riwak** [comment]
Hey @jomino,

It was a PSP configuration error on our side for your sandbox account. You did not have a iDeal configuration. It's fixed now. Can you retry ? 

Thanks,

**Comment by Riwak** [comment]
-

**Comment by jomino** [comment]
Thanks,

I tried and it is well working.

I suppose the ultimate transition page for payment confirmation, asking to
relay on your side, is a step only due to the fact that the call comes from
a test space ?

thanks again,
Jomino

**Comment by gionapaolini** [comment]
Hi, I have the same problem.
Where do I configure iDeal?

**Comment by jomino** [comment]
hello,

sorry for the delay.

this is the response from the help desk:

"It was a PSP configuration error on our side for your sandbox account."

let's try to contact the help desk.

Jomino

Le mer. 23 sept. 2020 à 17:04, gionapaolini <notifications@github.com> a
écrit :

**Comment by gionapaolini** [comment]
Yeah I did that and they fixed it thanks.
But I think it would make sense to give the users the option to enable it at least in sandbox mode.

**Comment by gionapaolini** [comment]
It happened again, but this time Ideal is activated, is it an option to add more information to the error?

**Comment by PeeyushAgrawalWebkul** [comment]
I'm also getting the same error on sandbox.
@Riwak Could you please let me know why we are getting this error and how i can fix it for my sandbox account and also for our client sandbox accounts in future

**Comment by fredericdelordm** [comment]
Hello @gionapaolini and @PeeyushAgrawalWebkul, we are looking into it

**Comment by phucduongzestif** [comment]
hi @fredericdelordm i got issue with sandbox mode, could you please share with me how to fix this

Thanks

**Comment by fredericdelordm** [comment]
@phucduongzestif Did you contact the support to activate IDEAL?

**Comment by narolalabs** [comment]
@Riwak I am also facing same issue for the iDeal Payment. Generated support ticket for the same. But, they are not providing proper answer. So, could you please help me for the same?
