### ISSUE TITLE
User Update endpoint is not working. 

### ISSUE THREAD

**Issue by ShooterArk** [Mangopay/mangopay2-php-sdk#357]
Hi,

I am trying to update user info on mangopay. But I keep getting this error:
**Method not allowed. The Requested resource does not support http method 'PUT'.**

I contacted MangoPay to check if I might be making some mistake but I double checked my code and its structure as directed in the MangoPay documentation. So they asked me to inform you guys to please look into this issue. 

Thank you

**Comment by ShooterArk** [comment]
No response for the past 20 days ? IS this repo even currently active or dormant ?

**Comment by mickaelpois** [comment]
Hello @ShooterArk ,

Could you provide some code sample ?

**Comment by ShooterArk** [comment]
Hi Mickael,

`$user = new MangoPay\UserNatural();`
`$user->FirstName = $this->request->firstname;`
`$user->LastName = $this->request->lastname;`
`$user->Email = $email;`
`$user->Birthday = strtotime($this->request->dob);`
`$user->Nationality = $this->request->nationality;`
`$user->CountryOfResidence = $this->request->countryofresidence;`
`$user->Id = $this->request->authorId;`
`$createdUser = $api->Users->Update($user);`

Here is my code my friend. Can you please let me know if I am making not setting it up properly ?

**Comment by Riwak** [comment]
Hello @ShooterArk,

In your code you are trying to update `$createdUser` without creating it first. 

You should do : 

```
$user = new \MangoPay\UserNatural();
$user->FirstName = "John";
$user->LastName = "Doe";
$user->Email = "john.doe@sample.org";
$user->Birthday = mktime(0, 0, 0, 12, 21, 1975);
$user->Nationality = "FR";
$user->CountryOfResidence = "FR";

$createdUser = $this->_api->Users->Create($user); // Creating the user
$userSaved = $this->_api->Users->Update($createdUser); // Updating
```

**Comment by ShooterArk** [comment]
Hi Riwak,
thank you for responding back. I would request you to please review my previous message again. I am not creating the user because its already created. I am using the existing record of the user and updating it. 

As you can see here:
`$user->Id = $this->request->authorId`

Please advise.

Best Regards,

**Comment by Riwak** [comment]
Hi @ShooterArk,

In your code `$this->request->authorId ` does not correspond to your existing user id. In fact `authorId` are used to identify a transaction author. It's never used to identify a user.

Let's say you have John user already created and you want to edit his last-name.

As already said 🙂 You should get the user first : 
`$userFetched = $this->_api->Users->Get($john->Id);`

Then you can do the edit :
`$userFetched->LastName .= " - CHANGED";`

When the edit is done you can save it : 
`$userSaved = $this->_api->Users->Update($userFetched);`

**Comment by ShooterArk** [comment]
Hi Riwak,

Thank you for responding back. Actually I followed the documentation of mangopay and the above code was copied from there. I am still facing the same issue which I mentioned before.

Here is the error:
"**MangoPay Error Method not allowed. The requested resource does not support http method 'PUT'**"

I have contacted mangopay Support and they told me that the required SDK is pointing to the wrong end point. Can you please confirm it. 
If you want I can share the support emails as well for reference. 

Thank you

**Comment by Riwak** [comment]
Yes please, Is it possible to have ?
- `case ID`
- `client-id`

 Thanks in advance, 

Audouin

**Comment by ShooterArk** [comment]
Hi Riwak,

I think this response message from mangopay support will be helpful to you:

This is your response regarding above issue.
"It seems you are trying to update/PUT user details on: /users/natural/
If you are updating an existing user, you should be doing PUT towards: /users/natural/userId/ "

Regards,

**Comment by ShooterArk** [comment]
> Yes please, Is it possible to have ?
> 
> * `case ID`
> * `client-id`
> 
> Thanks in advance,
> 
> Audouin

What is a Case ID ?

I can provide you the client-id: **2706**

Regards,

**Comment by Riwak** [comment]
Hello @ShooterArk,

> Actually I followed the documentation of mangopay and the above code was copied from there.

As already said, `$user->Id = $this->request->authorId` is not mentioned anywhere on the documentation 🙂 In fact `authorId` are used to identify a transaction author. It's never used to identify a user.

Can you please try this above code : 

$userFetched = $this->_api->Users->Get($john->Id);

Then you can do the edit :
$userFetched->LastName .= " - CHANGED";

When the edit is done you can save it :
$userSaved = $this->_api->Users->Update($userFetched);

**Comment by ShooterArk** [comment]
Hi Riwak,

Thank you so much for your assistance. Now I understood what you were trying to explain. Its working now. 

Regards,
