### ISSUE TITLE
Missing method/endpoint for getting UBO declaration

### ISSUE THREAD

**Issue by jns-dev** [Mangopay/mangopay2-php-sdk#361]
1. Missing method/endpoint for getting UBO declaration only with UBO declaration Id (without User Id) -> GET: .../ClientId/kyc/ubodeclarations/UboDeclarationId.
There aren't any method that give the functionality to execute this endpoint.
I found that in the \MangoPay\Libraries\ApiBase.php file no endpoint for this action.

2. Missing user id in UBO Declaration

**Comment by jns-dev** [comment]
Missing UboDeclaration userId field

**Comment by mickaelpois** [comment]
Release 2.13.0

**Comment by jns-dev** [comment]
Why in the ApiBase.php exists 2 equal endpoints to get ubo declaration (ver. 3.1) ???
line 189 and line 193 'ubo_declaration_get_by_id' => ......
