### ISSUE TITLE
Bug in demo payment direct

### ISSUE THREAD

**Issue by euskadi31** [MangoPay/mangopay2-php-sdk#37]
Hi,

I think there is a mistake in the demo and documentation!

The API return a CardType = CB_VISA_MASTERCARD while the code is verified if CardType is CB, VISA, MASTERCARD or AMEX !

see https://github.com/MangoPay/mangopay2-php-sdk/blob/master/demos/paymentDirect/payment.php#L52-L55 and https://docs.mangopay.com/api-references/card/#panel8352862622

**Comment by hobailey** [comment]
Hey @euskadi31, thanks for the heads up - you're absolutely right.. I've just corrected that in https://github.com/MangoPay/mangopay2-php-sdk/commit/9860d032706395d8f5bee29061dd8f3720b0ea99 :-)
