### ISSUE TITLE
PHP 7.4 Upgrade: Unparenthesized `a ? b : c ? d : e` is deprecated.

### ISSUE THREAD

**Issue by kusiu** [Mangopay/mangopay2-php-sdk#371]
Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` {"userId":1,"exception":"[object] (ErrorException(code: 0): Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` at /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php:354)

**Comment by kusiu** [comment]
Hey @Riwak, can we action this please?

**Comment by mickaelpois** [comment]
Hello @kusiu, I'll release a new minor version today with your fix AND add 7.4 version on our Travis build.
Thanks a lot for your contribution.

**Comment by mickaelpois** [comment]
Fixed on 2.13.1 version. 
Travis support for PHP 7.4 added.
