### ISSUE TITLE
Difference between Sandbox Dashboard and API result

### ISSUE THREAD

**Issue by fleflochN** [Mangopay/mangopay2-php-sdk#377]
Hello,

I am facing a strange behavior : I have pushed several KYC documents to user (with several different status). They all appear correctly on the Sandbox Dashboard (and correctly attached to the user, but when I call GetKycDocuments() from the PHP SDk I don't receive the whole list. In fact 3 validated documents are not listed.
Did I miss something or is there a problem somewhere?
Also when grabing the LegalUser object the values for LegalRepresentativeProofOfIdentity, ProofOfRegistration and ShareholderDeclaration are null even if I have provided and validated them.

Thank you.

**Comment by Riwak** [comment]
Hey @fleflochN,

How many documents are listed from your `GetKycDocuments()` ? It can be link to pagination. Indeed, All the list returned by the API are paginable. For more info --> https://docs.mangopay.com/guide/lists-pagination-management

About your issue with the LegalUser object could you provide some code sample ?

You can have a look at our tests here: https://github.com/Mangopay/mangopay2-php-sdk/blob/master/tests/cases/KycDocumentsTest.php which are currently passing.

**Comment by fleflochN** [comment]
Thank you for your answer.

Indeed my problem was related to pagination. Since I didn't receive any information indicating how many documents are attached I didn't thought about it.

Regarding my issue with LegaUser object maybe I misunderstood some parameters. 
I was able to push and validate my KYC files, but the informations listed in my LegalUser object (LegalRepresentativeProofOfIdentity, Statute, ProofOfRegistration and ShareholderDeclaration) are still at null. I thought that these parameters were supposed to be filled when the KYC are validated but maybe I understood incorrectly.

**Comment by mangomaxoasis** [comment]
Hi @fleflochN 
Indeed these parameters are inputs and not filled automatically.
Regards,
max
