### ISSUE TITLE
Getting error when create wallet

### ISSUE THREAD

**Issue by Premlimbachiya** [Mangopay/mangopay2-php-sdk#378]
i am getting error when create wallet by new user id

One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.

**Comment by Riwak** [comment]
Hey @Premlimbachiya,

Is the user already created ? Did a `get` work on his id ? 
By the way, here is the code sample to create a wallet 😉 


```

// Prepare the api request
$Wallet = new \MangoPay\Wallet();
$Wallet->Owners = array ("8494514"); // ID of who own's the wallet
$Wallet->Description = "A desciption of the wallet";
$Wallet->Currency = "EUR";
$Wallet->Tag = "Custom data that you can add to this item";

// do the request
$Result = $api->Wallets->Create($Wallet);
```
