### ISSUE TITLE
mangopay-go-sdk

### ISSUE THREAD

**Issue by ritoon** [Mangopay/mangopay2-php-sdk#379]
Hello there,

I am currently writing an SDK in Golang could  we create a repo @mangopay ?
Aslo I found some little things to adjust in the current API implementation :

- the Error Response that have a Date in Float64 instead of an int64.
- the currency code is in ISO3 not in ISO2 as it is sayed in the documentation.
- the limit rates in the header are values duplicated wich is a wrong usage of a header
- the body in the API call to get the oAuth token should be empty and this call should be a GET method.

I am sure, I can help your team for writing the Go SDK @mickaelpois

**Comment by ritoon** [comment]
Just to let you know that I start a week ago the project under this repo [mangopay-go-sdk](https://github.com/58-facettes/mangopay-go-sdk)

**Comment by Riwak** [comment]
Hello @ritoon. Thanks for this very clear, clean and work you're doing on our SDK ! 🎉 ❤️
I'll have a closer look at it, can't wait to merge it and release it for all the community! 👍

**Comment by ritoon** [comment]
There is a lot of questions that I add in comments into the source code, you will find them following this pattern of search

**Comment by ritoon** [comment]
I just finish yesterday all structs and endpoints but we have to add an idempotency key and a retry config

**Comment by ritoon** [comment]
@Riwak @mihaimoiseanu @mickaelpois @shakaran don't hesitate to send me your feedbacks, I am not sure I'll have a lot of time next month to add some features to this Go SDK. For the moment Mangopay reject our kind of business so we will move to another PSP.

**Comment by mangomaxoasis** [comment]
Bonjour @ritoon !
Thank you for this excellent contribution, 
Would it be possible for you to create the repo on your side, we'll look at it from there 
Thanks
