### ISSUE TITLE
Dummy API endpoint

### ISSUE THREAD

**Issue by ritoon** [Mangopay/mangopay2-php-sdk#380]
We need a dummy API that takes the request from the SDKs in order to test them and mock some responses. 

### Why

- The actual `sandbox` should be used just for learning purposes and not for testing the code.
- Several services providers (no mentions) have a client that you can run locally.
- This can be helpful also for a CI when you run your tests.

### How

- using all the structs from the go model of the mangopay SDK with a git module.
- genrerating some fake data with a local fuzzer and sotring the all in maps.
- we can add features with params like network latencies, no responses of services and so on.

**Comment by mangomaxoasis** [comment]
Hi @ritoon,
I understand your feedback, however, I would recommend using the sandbox account to do any testing, our sandbox is always identical to the prod environment and great place to develop SDK functionality. 
We have certain test envs, but these are protected for security reasons.  
Regards,
Max
