### ISSUE TITLE
Misswrited Mandate Eventype

### ISSUE THREAD

**Issue by davoinb** [Mangopay/mangopay2-php-sdk#381]
Be carefull on using the events of the hook for the Mandate object. 
For the mandate failed, the event is misswrited as follow: 
(EventType.php)
```
const MandateCreated = "MANDATE_CREATED";
const MandatedFailed = "MANDATE_FAILED";
const MandateActivated = "MANDATE_ACTIVATED";
const MandateSubmitted = "MANDATE_SUBMITTED";
```

**Comment by mickaelpois** [comment]
Typo will be deprecated, and new parameter with good typo has been added, not to be breaking.
