### ISSUE TITLE
3DS process

### ISSUE THREAD

**Issue by duykhanh1411** [Mangopay/mangopay2-php-sdk#386]
I dont understand one thing that is after redirecting to the
SecureModeRedirectURL what are the steps that need to be followed.
```
$payIn = new \MangoPay\PayIn();
$payIn->CreditedWalletId = $CreditedWalletId;//$createdWallet->Id;
$payIn->AuthorId = $updatedCardRegister->UserId;
$payIn->DebitedFunds = new \MangoPay\Money();
$payIn->DebitedFunds->Amount = $DebitedFunds*100;
$payIn->DebitedFunds->Currency = "GBP";
$payIn->Fees = new \MangoPay\Money();
$payIn->Fees->Amount = 0;
$payIn->Fees->Currency = "GBP";
// payment type as CARD
$payIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsCard();
$payIn->PaymentDetails->CardType = $card->CardType;
$payIn->PaymentDetails->CardId = $card->Id;
// execution type as DIRECT
$payIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
$payIn->ExecutionDetails->SecureModeReturnURL = base_url.'controllername/action';
// create Pay-In
$createdPayIn = $mangoPayApi->PayIns->Create($payIn);
```
How can i get result is success or fail, get transaction ?. In document, it don't talking about next step. Can you help me provider more info about this.
Many thanks

**Comment by Riwak** [comment]
Hey @duykhanh1411,

In fact, you have 2 options to get the result of your transaction.

Option 1 (the recommended one) : Using hooks on the PayIn success or fail event --> More info here :  https://docs.mangopay.com/endpoints/v2.01/hooks#e246_the-hook-object

Option 2 : Using the transaction ID of your transaction you can do a GET on it. You will have the status (/created/failed/success) in the json response --> More info here : https://docs.mangopay.com/endpoints/v2.01/payins#e265_view-a-payin

Have a nice day,

Audouin,

**Comment by duykhanh1411** [comment]
> Hey @duykhanh1411,
> 
> In fact, you have 2 options to get the result of your transaction.
> 
> **Option 1** **(the recommended one)** : Using hooks on the PayIn success or fail event --> More info here : ` https://docs.mangopay.com/endpoints/v2.01/hooks#e246_the-hook-object`
> 
> **Option 2** : Using the transaction ID of your transaction you can do a GET on it. You will have the status (/created/failed/success) in the json response --> More info here : `https://docs.mangopay.com/endpoints/v2.01/payins#e265_view-a-payin`
> 
> Have a nice day,
> 
> Audouin,

thanks @Riwak 
I think your answer is payin normal (not for 3DS process)
when create payin with 3DS process, we must redirect to mangopay page and validate 3DS, after that mangopay api will be return "SecureModeReturnURL"
In my question: how can we get result by "SecureModeReturnURL"? on current document i don't see anything about it
:(

**Comment by Riwak** [comment]
Hey @duykhanh1411,

Even if it's a 3DS transaction the hooks will still be active and will still give you the notification of failure or success 🙂 (After the 3Ds part)

**Here is the complete 3DS payment flow :** 

1. Create a Card PayIn
2. Get the response
3. Redirect the user to `SecureModeRedirectURL`
4. The user fill the 3DS info + click on submit
5. The user is redirected to `SecureModeReturnURL`
6. Hook is triggered (so you should receive the payIn notification) **[Option1]**
7. On the `SecureModeReturnURL`, mangopay will automatically add the transaction id 
Ex : https://MySecureModeReturnURL/?transactionId=78051642

You can use this ID to check the transaction status **[Option2]**

**Comment by duykhanh1411** [comment]
> Hey @duykhanh1411,
> 
> Even if it's a 3DS transaction the hooks will still be active and will still give you the notification of failure or success 🙂 (After the 3Ds part)
> 
> **Here is the complete 3DS payment flow :**
> 
> 1. Create a Card PayIn
> 2. Get the response
> 3. Redirect the user to `SecureModeRedirectURL`
> 4. The user fill the 3DS info + click on submit
> 5. The user is redirected to `SecureModeReturnURL`
> 6. Hook is triggered (so you should receive the payIn notification) **[Option1]**
> 7. On the `SecureModeReturnURL`, mangopay will automatically add the transaction id
>    Ex : https://MySecureModeReturnURL/?transactionId=78051642
> 
> You can use this ID to check the transaction status **[Option2]**

@Riwak Many thanks your support 👍 
I have question when i use option 2:
What can i do with transactionId=78051642 ?
I mean we must access dasboard of mangopay to check it or we can use another api to check it?

**Comment by Riwak** [comment]
Hey, 

Nope, no need to access the mangopay dashboard to check it.
You can do it directly through an API endpoint --> https://docs.mangopay.com/endpoints/v2.01/payins#e265_view-a-payin 

N.B : Our mangopay dashboard is just the API interface, it means that all actions done on this interface, you can do it also directly using the API 😉 (vice-versa)

All the best
Audouin,

**Comment by duykhanh1411** [comment]
> https://docs.mangopay.com/endpoints/v2.01/payins#e265_view-a-payin

thanks your support @Riwak.
