### ISSUE TITLE
MangoPay :What information require for RegistrationData : what should we need to pass in that feild to update the card.

### ISSUE THREAD

**Issue by ananarola** [MangoPay/mangopay2-php-sdk#39]

**Comment by ananarola** [comment]
WHAT ARE THE KEY-VALUES ARE PASS TO GET THE CARD TOKEN WHICH WILL BE USED TO CHEACK THAT GIVEN CARD DETAILS ARE VALID OR NOT. Please help me in this case.

**Comment by hobailey** [comment]
Hi there,
You can find the relevant info in this example: https://github.com/MangoPay/mangopay2-php-sdk/blob/master/demos/paymentDirect/non_js.php
Let me know if its not clear.

**Comment by ananarola** [comment]
Hi...thank for reply. I already see  the mention page and i pass data in that way but i get errorCode :errorCode=09101
https://homologation-webpayment.payline.com/webpayment/getToken:
{
  "data" : "preRegistrationData",
  "accessKeyRef" : "acesskey",
  "returnURL" :   "url"
  "cardNumber" : "4970100000000154",
  "cardExpirationDate" : "1014",
  "cardCvx" : "123"
  }

do u have any idea why this happen..is there any mistake in code

**Comment by hobailey** [comment]
OK, so you need to ue an expiry date in the future. 
And presumeably your "preRegistrationData" and "acesskey" are actual values you're getting back from the Mangopay API?
If that still doesnt work, please send your whole code piece. Thanks

**Comment by hobailey** [comment]
And also, please check you are posting your form as url-encoded

**Comment by ananarola** [comment]
hey one more big question arise over here. 
 On which base the mangopay_userId generate. I ask this question based on following senerio
 > Suppose i have three different store lets Say A,B,C threw which i purchase the different product. now suppose each has their own credentials : (Que. can we use one global credential or need to create separately client id and pass for three of store) : Now when i select Store B at that time i am not mangopay user : now from my backend it generate one mango-pay-natural-user so over here the "ID" i.e mangopay_id of user is based on Store Credentials or it is independed. if It is independed then can i use the same ID for other two store also or i need to create new one mangoID for each store...I am get confused could you please help me in this senerio.: thanks in advance

**Comment by hobailey** [comment]
*You should have one ClientId for your whole application.* 
You can then create users and wallets for each person/company if you wish. So each store in your example would be a user with a wallet (they'll need to be a "legal" user rather than a "natural" user if they're an official business or organisation). 
If you have a user "Peter" who buys 3 products, one from each Store A, B and C, I suggest your flow would be:
(You create a user and wallet for each Store when they register on your app)
* You create a user and wallet for Peter
* Peter pays into his wallet the amount for all 3 products
* You then do a transfer from his wallet to each store with the amount they are owed (so there would then be nothing left in his wallet after the 3 transfers). E.g. if Product 1 is sold by Store A and costs 10€, you'll transfer 10€ from Peter's wallet to Store A's wallet.

Is this more clear?

**Comment by ananarola** [comment]
Yes. Thankyou for reply

**Comment by ananarola** [comment]
MangoPay\ResponseException Code: 403
 Message: Prohibition to use the method. this ressource is forbidden for your credential
Details: MangoPay\Error Object
(
    [Message] => this ressource is forbidden for your credential
    [Errors] => 
)


what its actual means in mangopay terms

**Comment by hobailey** [comment]
It means the combination of ClientId and Passphrase you are using are incorrect. Please check these elements but note that a) do not post them here and b) we are unable to regenerate a passphrase if you have lost it - you must in that case create a totally new ClientId

**Comment by ignivahermenpreet** [comment]
I am using this data. it shown me error 
errorCode=09101.

when i use this process from server side. it's working fine. ClientId and Passphrase are correct and it's working fine. we do not need clientId and passphrase for tokenization server. 

var data = new FormData();
data.append('data', 'ctdPU2IGyKn3gQT0GVK0sbgB96l7QfMpEKJ1ffW8DB4JW--CUb2Jf0W4TC7BcqgPS4wCy-yiraxeE65tmxOe8A');
data.append('accessKeyRef', '1X0m87dmM2LiwFgxPLBJ');
data.append('cardNumber', '4706750000000009');
data.append('cardExpirationDate', '1023');
data.append('cardCvx', '102');
data.append('returnURL', 'http://localhost');

console.log(data);
var xhr = new XMLHttpRequest();
xhr.open('POST', 'https://homologation-webpayment.payline.com/webpayment/getToken', true);
xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
xhr.onload = function () {
    // do something to response
    console.log(this.responseText);
};
xhr.send(data);
