### ISSUE TITLE
OpenSSL error when adding a page to a KYC document

### ISSUE THREAD

**Issue by PeterDiadraw** [Mangopay/mangopay2-php-sdk#398]
I've encountered a problem during KYC submission. I create a document without any issues - the created documents appear in my sandbox. However, when I try do add a page to the document I get the following error : 

`cURL error: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104 #0 /var/www/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/HttpCurl.php(24): MangoPay\Libraries\HttpCurl->RunRequest()`

Here's a snippet of the relevant code. I've verified that the user id and document id are correct, as well as that base64 image data is being provided :

```
public function addPage(IKycPage $page) {

    $kycPage = new \MangoPay\KycPage();
    $kycPage->File = $page->getBase64();

    $pageAddResult = $this->mangoPayApi->Users->CreateKycPage(
        $this->mangoPayUserId,
        $this->documentId,
        $kycPage
    );
}
```

**Comment by catacraciun** [comment]
Hi @PeterDiadraw !
We are looking into this issue, we'll keep you posted on this.

**Comment by mangomaxoasis** [comment]
Hi @PeterDiadraw 
We can't as of now reproduce the issue, what kind of file was uploaded? What size?
Thanks
