### ISSUE TITLE
WHAT ARE THE KEY-VALUES ARE PASS TO GET THE CARD TOKEN WHICH WILL BE USED TO CHEACK THAT GIVEN CARD DETAILS ARE VALID OR NOT. Please help me in this case.

### ISSUE THREAD

**Issue by ananarola** [MangoPay/mangopay2-php-sdk#40]
Hi...i am using mangoopay interation for payment. here i can able to create card but i am unable to recive token which help me to update the registerCard with RegistrationData. here i pass six things;
1.creditcardNumber 
2.CVV 
3.ExpDate
4 AcessKEy
5. ReturnURL
6. PreRegistration data at : https://homologation-webpayment.payline.com/webpayment/getToken.
but i get : errorCode=09101

might happen that my key-value pair is wrong. What it will be if anyone know then please do reply

**Comment by hobailey** [comment]
Hello, please keep one thread for each issue - I will close this and reply to the other https://github.com/MangoPay/mangopay2-php-sdk/issues/39
