### ISSUE TITLE
Registration data : Invalid format

### ISSUE THREAD

**Issue by sohaieb** [Mangopay/mangopay2-php-sdk#403]
Hello,

I'm still having "Registration data : Invalid format" even if i added "data=" to my registration data, and here is the full object: 

![image](https://user-images.githubusercontent.com/32372764/87803698-2b266a00-c853-11ea-980b-772086042296.png)

**Comment by mangomaxoasis** [comment]
Hi @sohaieb 
We're looking into it 
Max

**Comment by sohaieb** [comment]
> Hi @sohaieb
> We're looking into it
> Max

Thank you, I'm waiting sir :)

**Comment by sohaieb** [comment]
Hello again 

Finally, I fixed it, 
it was a missing part in my code : 
```
$httpClient = new Client(); // use GuzzleHttp\Client;
        $stream = $httpClient->request('POST',
            $cardRegistration->CardRegistrationURL,
            [
                'form_params' => [
                    'data' => $cardRegistration->PreregistrationData,
                    'accessKeyRef' => $cardRegistration->AccessKey,
                    'cardNumber' => $cardNumber,
                    'cardExpirationDate' => $expiredDate,
                    'cardCvx' => $cvc
                ]
            ]);
        return $stream
            ->getBody()
            ->getContents();
```
I do not know why the mangopay documentation is missing these details .. 

by the way thank you a lot.

**Comment by mangomaxoasis** [comment]
Hey @sohaieb 
Good to hear, we're currently reworking to doc, we'll try to include this comment in the next version
cheers

**Comment by sohaieb** [comment]
Thank you sir :)
