### ISSUE TITLE
Update README Composer Installation => remove ^2.3 part

### ISSUE THREAD

**Issue by Nicolas-Bouteille** [Mangopay/mangopay2-php-sdk#404]
Hello,
I believe the documentation for composer installation 
composer require mangopay/php-sdk-v2:^2.3
should not mention ":^2.3" so that new projects can start using the latest version of the SDK. 
For example as of right now it is 3.1.0

**Comment by catacraciun** [comment]
Fixed. Thank you @Nicolas-Bouteille for your suggestion!
