### ISSUE TITLE
File for Payout is not Up to date to Version 2.0.1

### ISSUE THREAD

**Issue by Bjoern3003** [Mangopay/mangopay2-php-sdk#408]
The Payout in this SDK does not support Tag and BankwireRef.

**Comment by mangomaxoasis** [comment]
@Bjoern3003 looking into it, I'll keep you updated

**Comment by Bjoern3003** [comment]
Good Morning, thank you a lot.

**Comment by mangomaxoasis** [comment]
Hi @Bjoern3003  we've looked into the issue and wanted to double check where the payout is not supporting Tag and Bankwire
Do you have some kind of example?
Best,
Max

**Comment by Bjoern3003** [comment]
Hi, there is no variable for the Tag in your https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/PayOut.php

For the BankwireRef I have found the file https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/PayOutPaymentDetailsBankWire.php

**Comment by mangomaxoasis** [comment]
Hi @Bjoern3003 
The tag field is in EntityBase object 
and Payout is extending Transaction, which is extending EntityBase
Please look in EntityBase to find the relevant tag
Cheers
max
