### ISSUE TITLE
Erreur d'apel de l'API pour apiUsers::Update

### ISSUE THREAD

**Issue by M4E** [MangoPay/mangopay2-php-sdk#41]
Lors de la l'appel à la méthode "Update" de la class "apiUsers", vous appelez "users_createnaturals" et "users_createlegals" au lieu d'apeller "users_savenaturals" et "users_savelegals".

**Comment by hobailey** [comment]
Hello,
Est-ce que vous pouvez preciser la ligne ou vous voyez cette erreur? Pour le Create(), je vois bien user_create...: https://github.com/MangoPay/mangopay2-php-sdk/blob/master/MangoPaySDK/tools/apiUsers.inc#L18
Et pour le Update(), je vois bien user_save...: https://github.com/MangoPay/mangopay2-php-sdk/blob/master/MangoPaySDK/tools/apiUsers.inc#L88
