### ISSUE TITLE
Kyc documents internal server error.

### ISSUE THREAD

**Issue by ShooterArk** [Mangopay/mangopay2-php-sdk#410]
Hi there,
I am trying to upload a document for KYC. Document creation is working well but Page creation is not working at all, neither by using base64 encoding nor by uploading a file. 

`$KycDocumentId = $listDoc[0]->Id // Document ID was created previously.

						$new_name = "file" . rand() . '.' . $doc->getClientOriginalExtension();
      					$path = $doc->move(public_path('temp'), $new_name);  // new path to the document

						$result2 = $api->Users->CreateKycPageFromFile($authorId, $KycDocumentId, $path);

						$KycDocument = new MangoPay\KycDocument();
						$KycDocument->Id = $KycDocumentId;
						$KycDocument->Status = "VALIDATION_ASKED";
						$result3 = $api->Users->UpdateKycDocument($authorId, $KycDocument);
`

Also not working with CreateKycPage method as well,

`$KycDocumentId = $listDoc[0]->Id // Document Created previously;

						//add a page to this doc
						$kycPage = new \MangoPay\KycPage();
						$kycPage->File = base64_encode(file_get_contents($doc));

						$result2 = $api->Users->CreateKycPage($authorId, $KycDocumentId, $kycPage);

						$KycDocument = new MangoPay\KycDocument();
						$KycDocument->Id = $KycDocumentId;
						$KycDocument->Status = "VALIDATION_ASKED";
						$result3 = $api->Users->UpdateKycDocument($authorId, $KycDocument);
` 

Error: **MangoPay Error Internal server error. Internal Server Error**

Can you please advise on how to resolve this. thank you

**Comment by mangomaxoasis** [comment]
Hi @ShooterArk 
The issue is in treatment 
max

**Comment by SoloJr** [comment]
Hi @ShooterArk 

This issue is covered [here](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/tests/cases/UsersTest.php#L498)
