### ISSUE TITLE
Question about KYC and Compliance - Regular verification

### ISSUE THREAD

**Issue by duykhanh91** [Mangopay/mangopay2-php-sdk#418]
Hi you, 
Can you share me process of this:
![Screen Shot 2020-08-31 at 16 15 48](https://user-images.githubusercontent.com/39787610/91704059-49e38480-eba5-11ea-953b-fcbfa09707f5.png)
Base on the current document we need add new info : `CompanyNumber` and `UBO declaration`
  - For `CompanyNumber` i don't know how to get it
  - For `UBO declaration` we must only call api like on document or we must do anything else?
Can you share me full process of this
I want to apply this for new `Legal User` and old `Legal User`

**Comment by mangomaxoasis** [comment]
Hi @duykhanh91 
Company number info is here https://docs.mangopay.com/guide/company-number

For UBO there are three calls 
https://docs.mangopay.com/endpoints/v2.01/ubo-declarations#e1024_the-ubo-declaration-object

Create a UBO
Create a individual UBO declaration 
Submit the UBO

Please contact our support line https://support.mangopay.com/s/contactsupport?language=en_US for more information 
Regards,
Max
