### ISSUE TITLE
ErrorCode : 001012 : Transaction amount is lower than minimum permitted amount

### ISSUE THREAD

**Issue by ananarola** [MangoPay/mangopay2-php-sdk#42]
hi..while i give amount 25 then it raise this error : should i not able to pay 25 in sandbox environment or i used wrong testing card? how should i solve this issue. 
need help

**Comment by hobailey** [comment]
Hi there,
Could you show the code you're using please? And the card? I've just tested 25EUR payin web and direct and it works fine in sandbox :-)

**Comment by ananarola** [comment]
hey..sorry i am not post code over her. but the situation is that when i give amount of 100 rs. then it work perfect but i dont understand why it not work with amount 25?

**Comment by ananarola** [comment]
Getting new error : 
    [Status] => FAILED
    [ResultCode] => 009199
    [ResultMessage] => PSP technical error


Everything work fine : but suddeny i get this error : please do reply

**Comment by hobailey** [comment]
I'm afraid it is very difficult to help without any code. 
What currency are you using and which test card?

**Comment by sylvaindelezir** [comment]
You need to post some code here because without an example nobody can help you.
An idea perhaps : in your code, you have to multiply by 100 the amount : 25EUR => 2500

**Comment by khnarola** [comment]
Thanks,
i got solution from "An idea perhaps : in your code, you have to multiply by 100 the amount : 25EUR => 2500"
