### ISSUE TITLE
Read Header Information

### ISSUE THREAD

**Issue by janooosh** [Mangopay/mangopay2-php-sdk#424]
Hi, 

how can I read the header information? I need it to display pagination results and can not access GetRequestHeaders from an ApiBase object. 

#282  did not really answer the question.

Thanks!

**Comment by mangomaxoasis** [comment]
Hi @janooosh 
I think we're missing something in this issue, could we organise a a call? If so, please contact me at maxime.gavanon@leetchi.com

**Comment by mangomaxoasis** [comment]
Hi @janooosh 
At what point do you need to read the header info, and which fields in particular

**Comment by catacraciun** [comment]
Hi @janooosh 
What headers would you like to read from a Mangopay API response?

**Comment by mangomaxoasis** [comment]
hey @janooosh feel free to reopen this issue
