### ISSUE TITLE
Credentials error in production

### ISSUE THREAD

**Issue by hallesetgo** [Mangopay/mangopay2-php-sdk#430]
Après avoir développé toute ma solution en PHP en Sandbox, tout fonctionne, pas de problème, que ce soit sur ma machine en local ou en production.
Lorsque j'utilise les credentials de production, je ne peux rien faire, il y a une erreur de connexion, sur ma machine en local et sur mon serveur en production.
J'ai essayé de supprimer le fichier temporaire d'authentification, rien n'y fait, j'obtiens une erreur 401.

J'essaie de faire une opération la plus simple possible 

$mangoPayApi = new MangoPay\MangoPayApi();
// $mangoPayApi->Config->BaseUrl = MangoPay_BaseUrl;
$mangoPayApi->Config->ClientId = MangoPay_ClientId;
$mangoPayApi->Config->ClientPassword = MangoPay_ClientPassword;
$mangoPayApi->Config->TemporaryFolder = MangoPay_TemporaryFolder;

$Client = $mangoPayApi->Clients->Get();
MangoPay\Libraries\Logs::Debug('VIEW CLIENT', $Client);

En sandbox, aucun problème, j'ai bien mon retour.
En production, j'obteins immédiatement l'erreur suivante 
[06-Oct-2020 16:15:05 Europe/Paris] PHP Fatal error:  Uncaught exception 'MangoPay\Libraries\ResponseException' with message 'Unauthorized' in /home/halleset/public_html/MangoPay/Libraries/RestTool.php:362
Stack trace:
#0 /home/halleset/public_html/MangoPay/Libraries/RestTool.php(152): MangoPay\Libraries\RestTool->CheckResponseCode(401, Object(stdClass))
#1 /home/halleset/public_html/MangoPay/Libraries/ApiOAuth.php(28): MangoPay\Libraries\RestTool->Request('/oauth/token', 'POST', Array)
#2 /home/halleset/public_html/MangoPay/Libraries/AuthorizationTokenManager.php(33): MangoPay\Libraries\ApiOAuth->CreateToken()
#3 /home/halleset/public_html/MangoPay/Libraries/AuthenticationHelper.php(83): MangoPay\Libraries\AuthorizationTokenManager->GetToken('8be9d41eae7defa...')
#4 /home/halleset/public_html/MangoPay/Libraries/AuthenticationHelper.php(27): MangoPay\Libraries\AuthenticationHelper->GetHttpHeaderStrong()
#5 /home/halleset/public_html/MangoPay/Libraries/RestTool.php(332): MangoPay\Libraries\AuthenticationHelper->GetHttpHeaderKey()
#6 /home/halleset/public_html/Man in /home/halleset/public_html/MangoPay/Libraries/RestTool.php on line 362

**Comment by mangomaxoasis** [comment]
Bonjour @hallesetgo 
Vous avez bien configurer? 
$api->Config->BaseUrl = 'https://api.mangopay.com'

ainsi que la cflef de production poru

**Comment by mangomaxoasis** [comment]
Hi @hallesetgo 
I'm closing this issue, please contact me if problem persists
