### ISSUE TITLE
Tests failing ❌

### ISSUE THREAD

**Issue by lucasmichot** [Mangopay/mangopay2-php-sdk#432]
It seems that the tests are failing without any valid reason, locally and within the CI.

- Are there some missing testing instructions that the Mongopay team should provide?
- If not, how to ensure that this package is ready for production?

---

cf. 
PR: https://github.com/Mangopay/mangopay2-php-sdk/pull/431 
CI:  https://travis-ci.org/github/Mangopay/mangopay2-php-sdk/builds/734590012

**Comment by mangomaxoasis** [comment]
Hi @lucasmichot 
we're looking into testing, there are a few considerations in play,  
Would it be possible to speak about it, could you contact me maxime.gavanon@mangopay.com 
To discuss the issue

**Comment by mangomaxoasis** [comment]
Fix passed for this issue in last release, feel free to let us know if it persists
