### ISSUE TITLE
How to create payment form using custom desiging

### ISSUE THREAD

**Issue by kapil191** [Mangopay/mangopay2-php-sdk#433]
Hi, 

I want to create my own payment form and it contains (card number, exp month/year, cvv) with my own css. But I don't understand what should be the field name for card number etc and where this data get submitted I want my payment form should look like this https://prnt.sc/uzafjs
I am using the card web payin 
Please let me know how can I acheive this because there is no much information is given in API doc

Thank you

**Comment by mangomaxoasis** [comment]
Hi @kapil191,
For card web pay you https://docs.mangopay.com/endpoints/v2.01/payins#e269_create-a-card-web-payin
will be redirected to a hosted payment page 
You can customize use the following parameter TemplateURLOptions

![image](https://user-images.githubusercontent.com/66364935/96581358-fd314580-12d9-11eb-85cf-aa6245587a7d.png)

**Comment by mangomaxoasis** [comment]
To avoid this you can, 'register a card' and process a payment using this card 
https://docs.mangopay.com/endpoints/v2.01/cards#e178_create-a-card-registration
then
https://docs.mangopay.com/endpoints/v2.01/payins#e278_create-a-card-direct-payin

**Comment by mangomaxoasis** [comment]
Please refer to doc for more info 
Cheers,
Max
