### ISSUE TITLE
User Transactions API doesn't return transfers crediting one user's wallet

### ISSUE THREAD

**Issue by canaver** [Mangopay/mangopay2-php-sdk#439]
The user Transaction API :
.../v2.01/ClientId/users/UserId/transactions/

returns nearly all transactions:
- payin, 
- payout and 
- transfer debiting

but doesn't return the transfer crediting transactions.

To get currently the whole list of transactions for a user, it becomes very complicated...

Could you correct that?

**Comment by mangomaxoasis** [comment]
Hi @canaver 
Do you mean the PHP SDK or the API call? 
Are you looking to filter by specific type of transaction?

**Comment by canaver** [comment]
Hi,
i use the API call.
And i use it both with filter and without, but in any case, without filter, i still don't see the transfer crediting transactions.

**Comment by mangomaxoasis** [comment]
Hi @canaver 
Indeed the API user call only takes into account transactions that are at the user level, that is  

- payin,
- payout
- Transfer Debiting to another User 

To see transfer crediting transactions, please make a call to a specific wallet 
.../v2.01/ClientId/users/UserId/transactions/
