### ISSUE TITLE
Payout: Blocked due to the Bank Account User's KYC limitations - Development environment

### ISSUE THREAD

**Issue by sohaieb** [Mangopay/mangopay2-php-sdk#440]
Hello,

Iguess my payout code is working fine and it returned a "CREATED" status, but the problem that in the sandbox dashboard i get action "FAILED".

here is my payout code:
```
public function createPayOut($userId, $walletId, $bankAccountId, $amount = null, $fees = null, $currency = null)
    {
        $PayOut = new PayOut();
        $PayOut->AuthorId = $userId;
        $PayOut->DebitedWalletId = $walletId;
        $PayOut->DebitedFunds = new Money();
        $PayOut->DebitedFunds->Currency = $currency ?? $this->currency;
        $PayOut->DebitedFunds->Amount = $amount ?? $this->amount;
        if ($fees === null || $fees === 0.0) {
            $fees = $this->fees;
        }
        $this->setMoney($PayOut, $currency, $fees);
        $PayOut->PaymentType = "BANK_WIRE";
        $PayOut->MeanOfPaymentDetails = new PayOutPaymentDetailsBankWire();
        $PayOut->MeanOfPaymentDetails->BankAccountId = $bankAccountId;
        $payOut = $this->api->PayOuts->Create($PayOut);
        if ($payOut->Status === \ExceptionConstants::STATUS_FAILED) {
            throw new \Exception($payOut->ResultMessage, $payOut->ResultCode);
        }
        return $payOut;
    }
```

here is my postman payout action response:
![image](https://user-images.githubusercontent.com/32372764/99076994-567c5400-25bc-11eb-86f3-5a862a50c9af.png)

here is the status i got in sandbox dashboard:
![image](https://user-images.githubusercontent.com/32372764/99077186-a22efd80-25bc-11eb-8cee-851d7fee7b0b.png)

so what should i do please ? and is this related to KYC documentation config ? if yes, should i implement this KYC verification to proceed my payout test in development environment?

thanks in advance.

**Comment by H4wKs** [comment]
@sohaieb You can't make a Payout if your user is not KYC validated, no matter the environment, the logic still the same.
From the MangoPay Sandbox dashboard, you have a section called "Sandbox Operations". Click on it, then choose "Process a KYC document" and validated the user you try to make the cashout for. Once the user is KYC validated, try to make that payout again and it should work like a charm.

**Comment by mangomaxoasis** [comment]
thanks @H4wKs !
