### ISSUE TITLE
PSR-1 coding style

### ISSUE THREAD

**Issue by Hetarnam** [Mangopay/mangopay2-php-sdk#442]
Hello,

Is somebody working to refactor this library in order to follow PSR-1 coding style [(here)](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md)?

If not, are you opened for PR?

**Comment by mangomaxoasis** [comment]
Hi @Hetarnam 
This is not currently ongoing, but we'll keep the community updated 
max
