### ISSUE TITLE
Internal server error Ocuures while Changing Validated to Out Of Date

### ISSUE THREAD

**Issue by Saurabhpi** [Mangopay/mangopay2-php-sdk#444]
Hello,

We are facing an issue while changing the first name. During this we need to change already Validated document status to out_of_date. In downgrade process at the time of update kyc status we get internal server error occurs. Please help us to resolve this problem. we are using updated version of sdk.
We have attached the error screen with this.
Please find attachment.
Please provide solution as soon as possible.
![image_2020_12_09T07_11_59_650Z](https://user-images.githubusercontent.com/75731122/101625117-feacfd80-3a40-11eb-9431-5eda703814b7.png)

Regards,
Saurabh p.

**Comment by mangomaxoasis** [comment]
Hi @Saurabh
The 'out of date' status cannot be sent for a user, it is triggered automatically on our side, by changing a relevant variable.
More info => https://docs.mangopay.com/guide/kyc-downgrade
Cheers,
Max

**Comment by Saurabhpi** [comment]
Okay thank you for knowing us, it means we don't need to pass or update any KYC status While changing the name or birth date. its comes automatically from mango pay side. is it right?

**Comment by mangomaxoasis** [comment]
Yes, that's it
