### ISSUE TITLE
Php 8 support

### ISSUE THREAD

**Issue by parth391** [Mangopay/mangopay2-php-sdk#449]
Hello,

Getting bellow error in php 8

`Deprecated: Required parameter $root follows optional parameter $authRequired in /Applications/XAMPP/xamppfiles/htdocs/mangopay/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php on line 100`

**Comment by mangomaxoasis** [comment]
Hi @parth391 
We're looking into it 
Max
