### ISSUE TITLE
"Call to undefined method MangoPay\\ScopeBlocked::GetSubObjects()"

### ISSUE THREAD

**Issue by Ephillius** [Mangopay/mangopay2-php-sdk#450]
I'm currently trying to make use of the new "block status" functions and my sdk is at release 3.1.5.

`public function getUserRegulatoryStatus($mp_user_id)
    {
      if($mp_user_id)
      {
        return $this->mangoPayApi->Users->GetRegulatory($mp_user_id);
      } else 
      {
        \Log::warning('Error MangoPayService at getUserRegulatoryStatus: mp_user_id missing');
      }
    }`
    
It currently stops here: 
[...]/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php
"line": 426,
"function": "CastResponseToEntity",

**Comment by mangomaxoasis** [comment]
Hi @Ephillius 
We're looking into ti

**Comment by tsoko17** [comment]
Hi,
I have got the same error.
In debug mode : 
`++++++++++++++++++++++ New request ++++++++++++++++++++++: 
-------------------------------
FullUrl: https://api.mangopay.com/v2.01/xxxxxxxxxxxxxx/users/00000000000000/Regulatory
-------------------------------
RequestType: GET
-------------------------------
HTTP Headers: Array
(
    [0] => Content-Type: application/json
    [1] => User-Agent: MangoPay V2 SDK PHP 3.1.6
    [2] => Authorization: bearer xxxxxxxxxxxxxxxxxxxx
)

-------------------------------
Response JSON: {"ActionCode":"","ScopeBlocked":{"Inflows":false,"Outflows":false},"Id":"00000000000000"}
-------------------------------
Response object: stdClass Object
(
    [ActionCode] => 
    [ScopeBlocked] => stdClass Object
        (
            [Inflows] => 
            [Outflows] => 
        )

    [Id] => 00000000000000
)

-------------------------------`
The url and response are working fine but It's after :(

**Comment by tsoko17** [comment]
You know what ?!
I found out where that's come from !
You need to open /MangoPay/ScopeBlocked.php
I replace : 
`class ScopeBlocked`
By : 
`class ScopeBlocked extends Libraries\Dto`

And enjoy ! 👍

**Comment by dduwoyemgp** [comment]
Hello @tsoko17 
Thanks for the suggestion 👍

**Comment by dduwoyemgp** [comment]
Hello @Ephillius 
Could we close this issue a the last release of the SDK fixed the problem?

**Comment by Ephillius** [comment]
Yes, absolutely. Thanks for the help. :)
