### ISSUE TITLE
KYC for Creating Multiple page

### ISSUE THREAD

**Issue by Saurabhpi** [Mangopay/mangopay2-php-sdk#453]
Hello,

We have an occurred issue while uploading multiple files for KYC validation process. Please let us help on this.
is it possible to upload multiple images or file at same time during KYC validation process???
Please reply soon.

Thanks & Regards,
Saurabh P

**Comment by mangomaxoasis** [comment]
Hi @Saurabhpi 
We're looking into it

**Comment by mangomaxoasis** [comment]
Hi @Saurabhpi 
You can created several pages by making the same POST call. Note that for the SDK do not send an encoded file, you have to put a "raw" file and the SDK will encode it automatically.

**Comment by Saurabhpi** [comment]
Hi,

Okay Thank you..we can understand what you trying to say is. But i just want to know is their possibility to browse 3 images files at a same time selection? Please clear this. 
Thank you.

**Comment by mangomaxoasis** [comment]
Hi @Saurabhpi 
No, it's one file per page 
Max
