### ISSUE TITLE
Add userId in MangoPay\UboDeclaration

### ISSUE THREAD

**Issue by tdumalin** [Mangopay/mangopay2-php-sdk#454]
Hello,

It would be nice to add UserId in MangoPay\UboDeclaration class for convenience, actually i need to create a table on my database to retrieve an user Id from ubo declaration.
In my case i want to send an email to notify users when ubo decalration status has changed, when hook is triggered with something like this:

```php
$api = new \MangoPay\MangoPayApi();
$id = $_GET['RessourceId'];
$declaration = $api->UboDeclarations->GetById($id); 
$user = $api->Users->Get($declaration->UserId);
//notify $user->Email;
```

**Comment by mangomaxoasis** [comment]
Hi @tdumalin 
We're looking into it

**Comment by jns-dev** [comment]
I have already reported this problem in [#361](https://github.com/Mangopay/mangopay2-php-sdk/issues/361#issue-511138429), but the still "UserId" not added.
