### ISSUE TITLE
List of bank accounts

### ISSUE THREAD

**Issue by clicok** [Mangopay/mangopay2-php-sdk#456]
Hello,
How to extract a user's account list please?
The example code on the following page seems to not work: [https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e28_list-bank-accounts-for-a-user](url)
Thanks in advance

**Comment by mangomaxoasis** [comment]
Hi @clicok , 
If you run the example code in the doc with the default settings you get na example.
![image](https://user-images.githubusercontent.com/66364935/105828138-16295100-5fc3-11eb-9313-d7c34acc342a.png)
Let me know of further issues,
Max

**Comment by clicok** [comment]
The problem is the PHP code, is your example complete?
```
$UserId = 8494514;
$Page = 1;
$Per_Page = 25;
$Active = "true";
$Sort = "CreationDate:DESC";
$ = $Api->->($UserId, $Page, $Per_Page, $Active, $Sort);
```

**Comment by mangomaxoasis** [comment]
OK, to clarify you are making the 'list user's bank account' via the SDK?
