### ISSUE TITLE
View User Blocked Status > GetRegulatory() return null

### ISSUE THREAD

**Issue by tsoko17** [Mangopay/mangopay2-php-sdk#458]
Hi,
As explained in title, if I try to return informations about my userID, Mangopay's method will return NULL.
`$response = $this->mangoPayApi->Users->GetRegulatory($userID);`

Result :
`null`

When I called the support, he saw my request on logs.

**Comment by dduwoyemgp** [comment]
Hi @tsoko17 
We're looking into it

**Comment by fredericdelordm** [comment]
Hello @tsoko17,

Which kind of information are you trying to get ?
