### ISSUE TITLE
Name missing in Shipping and Billing Object => Missing Support for 3D-Secure 2.0

### ISSUE THREAD

**Issue by FranzWegener** [Mangopay/mangopay2-php-sdk#459]
According to the implementation document for 3D-Secure 2.0 
(https://mcusercontent.com/c117c88a1044269f57b201fbe/files/83288c60-83ad-4df3-816d-9620625099b6/3DS2_integration_guide_1_.pdf)
pages 18 to 21 the **Shipping and the Billing Object must contain a FirstName and a LastName** field.

The SDK currently does not support that.
This causes the Mangopay API to reject calls relating to taking credit card payments.

**Therefore the SDK will stop functioning on 1 April 2021, unless this is fixed.**
Please bear in mind that developers integrating the SDK will also need time to implement the changes once this is working.

**Comment by dduwoyemgp** [comment]
Hi @FranzWegener 
We'll look into it :)

**Comment by FranzWegener** [comment]
Thank you :)

**Comment by FranzWegener** [comment]
@dduwoyemgp Any news here?
I want to remind you that I will also have to do some work implementing it afterwards and **this may not be the last issue with 3d-secure 2.0**. 
If people using this SDK don't finish **their implementation** by 31.3.2021 they will no longer be able to make credit card payments using Mangopay.

**Comment by dduwoyemgp** [comment]
Hello @FranzWegener 
Sorry for the delay of my reply but we are hardly working on a new release to integrate 3DS V2. It normally will be deployed in a few days.

**Comment by laurent-bientz** [comment]
@FranzWegener , [last release](https://github.com/Mangopay/mangopay2-php-sdk/releases/tag/3.2.0) added `FirstName` and `LastName` properties.

**Comment by FranzWegener** [comment]
@laurent-bientz I've tested this against Mangopay Sandbox and it works :) Thank you
