### ISSUE TITLE
Bad request. One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error

### ISSUE THREAD

**Issue by ananarola** [MangoPay/mangopay2-php-sdk#46]
Hi ... i am getting this error while  create PayIn object and the reponse i am getting the below...
ResponseString --> MangoPay\PayIn Object
(
    [CreditedWalletId] => 16733904
    [PaymentType] => 
    [PaymentDetails] => MangoPay\PayInPaymentDetailsCard Object
        (
            [CardType] => 
            [CardId] => 
        )

    [ExecutionType] => 
    [ExecutionDetails] => MangoPay\PayInExecutionDetailsDirect Object
        (
            [SecureMode] => 
            [SecureModeReturnURL] => http://test.com
            [SecureModeRedirectURL] => 
            [CardId] => 6291053
        )

    [AuthorId] => 6286964
    [CreditedUserId] => 
    [DebitedFunds] => MangoPay\Money Object
        (
            [Currency] => EUR
            [Amount] => 100
        )

    [CreditedFunds] => 
    [Fees] => MangoPay\Money Object
        (
            [Currency] => EUR
            [Amount] => 0
        )

    [Status] => 
    [ResultCode] => 
    [ResultMessage] => 
    [ExecutionDate] => 
    [Type] => 
    [Nature] => 
    [Id] => 
    [Tag] => 
    [CreationDate] => 
    [CreditedUserIdÂ ] => 17337581
)

What is worng in that.?  the same respoce i get in my test server and everything works fine...
the test server responcs is
CreditedWalletId] => 5154858
    [PaymentType] => 
    [PaymentDetails] => MangoPay\PayInPaymentDetailsCard Object
        (
            [CardType] => 
            [CardId] => 
        )

    [ExecutionType] => 
    [ExecutionDetails] => MangoPay\PayInExecutionDetailsDirect Object
        (
            [SecureMode] => 
            [SecureModeReturnURL] => http://test.com
            [SecureModeRedirectURL] => 
            [SecureModeNeeded] => 
            [CardId] => 6291026
        )

    [AuthorId] => 6286964
    [CreditedUserId] => 
    [DebitedFunds] => MangoPay\Money Object
        (
            [Currency] => EUR
            [Amount] => 65
        )

    [CreditedFunds] => 
    [Fees] => MangoPay\Money Object
        (
            [Currency] => EUR
            [Amount] => 0
        )

    [Status] => 
    [ResultCode] => 
    [ResultMessage] => 
    [ExecutionDate] => 
    [Type] => 
    [Nature] => 
    [Id] => 
    [Tag] => 
    [CreationDate] => 
    [CreditedUserIdÂ ] => 5831904
    
    ..

**Comment by hobailey** [comment]
If you look at the returned error message, it will state which fields are incorrect. From this output you've given, it looks like your CardId and AuthorId are IDs from your sandbox ClientId, not production.
