### ISSUE TITLE
3D-Secure 2.0 - PayIn Missing Fields

### ISSUE THREAD

**Issue by laurent-bientz** [Mangopay/mangopay2-php-sdk#465]
Hello,

According to the implementation for [3D-Secure 2.0](https://mcusercontent.com/c117c88a1044269f57b201fbe/files/83288c60-83ad-4df3-816d-9620625099b6/3DS2_integration_guide_1_.pdf), we should add `BrowserInfo`, `IpAddress`, `Billing` & `Shipping` objects to:
* `CardPreAuthorization`
* `PayIn`

For [`CardPreAuthorization`](https://github.com/Mangopay/mangopay2-php-sdk/blob/51715624753a527d04ff53590a688feb7ca28f83/MangoPay/CardPreAuthorization.php#L145-L155) object, the SDK **almost** reflects  (see #459) the API call (based on the fact `Billing` & `Shipping` are optional, I'm suppose it should work without passing them to the API...)

For [`PayIn`](https://github.com/Mangopay/mangopay2-php-sdk/blob/51715624753a527d04ff53590a688feb7ca28f83/MangoPay/PayIn.php) object, I can't see any of the asked properties (`BrowserInfo`, `IpAddress`, `Billing` & `Shipping`) in the current SDK.

Even in sub `PaymentDetails` ([`PayInPaymentDetailsPreAuthorized`](https://github.com/Mangopay/mangopay2-php-sdk/blob/51715624753a527d04ff53590a688feb7ca28f83/MangoPay/PayInPaymentDetailsPreAuthorized.php) in my case), there is no possibility at all to pass the required informations.

How can we adapt the API calls without having a SDK up to date? Can we have a rlz date for a new version of the SDK? We need to have time to perform the changes and **testing them** before the end of March.

2nd question: if my `PayIn` is based on a `PreAuthorization` (on which I've attached `BrowserInfo` and `IpAddress`), do we have to pass **again** these informations during the API call or you're able to recover automatically them from the `PreAuth`?

Thanks in advance

**Comment by dduwoyemgp** [comment]
Hello @laurent-bientz 
Thank you for sharing this issue with us. We are working on a new release and I hope it could land this week. 
About your second question, we'll look into it.

**Comment by laurent-bientz** [comment]
Hello @dduwoyemgp 

Thanks for the [new release](https://github.com/Mangopay/mangopay2-php-sdk/releases/tag/3.2.0) that allows to pass the correct informations for `CardPreAuthorization` (including `FirstName` & `LastName`).

About [`PayIn`](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/PayIn.php) object or sub [`PayInPaymentDetailsPreAuthorized`](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/PayInPaymentDetailsPreAuthorized.php), I can't see any `Billing`, `Shipping`, `BrowserInfo` or `IpAddress`.

Do I assume **all these fields are not required to be passed** in the case of a `PayIn` triggered by a `PreAuth`?

I guess that because for a standard `PaymentDetails` (aka [`PayInPaymentDetailsCard`](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/PayInPaymentDetailsCard.php)) we get almost all the fields? (don't understand why `Billing` is missing but whatever).

**Comment by dduwoyemgp** [comment]
Hello @laurent-bientz 

You assumed well because as you said, all these fields are not mandatory  in the case of a `PayIn` triggered by a `PreAuth`

**Comment by laurent-bientz** [comment]
@dduwoyemgp great, thanks for your feedback! We can close.
