### ISSUE TITLE
Wallet Report Issue

### ISSUE THREAD

**Issue by ashok-kr** [Mangopay/mangopay2-php-sdk#467]
Hello,

We are using the mangopay SDK to communicate with the api and here is our code.

    $reportRequest = new \MangoPay\ReportRequest();
    $reportRequest->ReportType = \MangoPay\ReportType::Wallets;
    $reportRequest->CallbackURL = $adminurl."/MangopayUsersExportUpdate.php";
    $reportRequest->DownloadFormat = "CSV";
    $reportRequest->Sort = "CreationDate:DESC";
    $reportRequest->Preview = false;
    $reportRequest->Filters = new \MangoPay\FilterReports();
    $reportRequest->Filters->MinBalanceAmount = (int)$amount;

But it is fetching the empty resultset. And when we add afterDate filter, it is not giving some wallets which have balance. For example the wallet 500382824 has 808 euros but is not included in the wallets report. Please check and do the needful.

**Comment by dduwoyemgp** [comment]
Hello @ashok-kr 
Thank you, we'll look into it

**Comment by ashok-kr** [comment]
> Hello @ashok-kr
> Thank you, we'll look into it

Any update on this?

**Comment by fredericdelordm** [comment]
Hello @ashok-kr,

Do you still have the issue?
