### ISSUE TITLE
Payout confirmation

### ISSUE THREAD

**Issue by jamnarola** [MangoPay/mangopay2-php-sdk#47]
I just want to confirm that it's necessary to do payout on each transaction?
or can i do something like
all user make payment and this amount will  credit in my wallet, and after rich on some amount do payout.
 Please gives step to do transction.

**Comment by hobailey** [comment]
Hi there,
You can do payins, transfers and payouts whenever you want. Ie you can payin, transfer to another wallet and then payout, or you can payin to a wallet and payout etc etc etc. And there is no limit to how long the money can stay in a wallet (ie if you want to do 10 payins and then a year later to do a payout, thats no problem).
Is that clearer? If you want advice on a specific workflow, I suggest you email more details about it to support[.at.]mangopay.com and they can suggest accordingly :-)

**Comment by jamnarola** [comment]
Thank you @hobailey
