### ISSUE TITLE
3DS - How to get mangopay password on PRO? 

### ISSUE THREAD

**Issue by duykhanh1411** [Mangopay/mangopay2-php-sdk#474]
I have question about 3DS process:
On the Sanbox we can get password at
![image](https://user-images.githubusercontent.com/28528146/111981311-157fe780-8b3a-11eb-8c4f-6e080214d549.png)
(it is always "MANGOPAY123")
but on PROD how to user can find it ?

**Comment by dduwoyemgp** [comment]
Hello @duykhanh1411 
The MANGOPAY123 is just for your tests on sandbox environment 
When in PROD, the issuing bank will send you the proper password depending on the card used by your users.

**Comment by duykhanh1411** [comment]
> Hello @duykhanh1411
> The MANGOPAY123 is just for your tests on sandbox environment
> When in PROD, the issuing bank will send you the proper password depending on the card used by your users.

thanks @dduwoyemgp
