### ISSUE TITLE
Confusing naming and/or usage of Ratelimit->ResetTimeMillis 

### ISSUE THREAD

**Issue by leihog** [Mangopay/mangopay2-php-sdk#478]
The documentation for rate limiting states that the reset time is a timestamp.

RateLimit-ResetTimeMillis as well as the examples in this repository suggests that the returned value would be the number of milliseconds until a reset.

The actual value returned is a unix timestamp approximately $IntervalMinutes in the future.

Unix timestamps are in seconds not milliseconds. So to avoid confusion the property should be renamed or at least
the example in the README should be updated to reflect that the returned value is a timestamp and not milliseconds until reset as is stated.

:)

**Comment by fredericdelordm** [comment]
Hello @leihog,

Thank you for your suggestion. Our team is reviewing it.

Have a nice day,

**Comment by fredericdelordm** [comment]
Hello @leihog,

This has been added in our latest release : [3.4.0](https://github.com/Mangopay/mangopay2-php-sdk/releases/tag/3.4.0)

Have a nice day,
