### ISSUE TITLE
errorCode=09101 : getting this while checking with live server. (at production)

### ISSUE THREAD

**Issue by ananarola** [MangoPay/mangopay2-php-sdk#48]
Hi i am using my real card and try to check online payment but i am getting this error. 
Everything works fine in sandbox enviroment  but while i chnage to live an dtest with real server then i get this error. i go to this error code but where i was wrong i am not getting becouse the ClientID and Password is correct,

My output while card created is 
{
 AcessKey = 9gHbl11np1yjYhuKF51T;
    CardRegistrationURL = "https://webpayment.payline.com/webpayment/getToken";
    CreationDate = 1428129041;
    Currency = EUR;
    PreregistrationData = "I5-F6i4odDiWz3S0GQmyulSYND7gjZqEdIbNoaXh3zu-3OYM0vwsNKu7gM0Kx2KFUE6onk55MkkuWPry3Tn84w";
    Status = CREATED;
    UserId = 17431574;
    cardID = cardID;
    errorMsg = "";
    mangoPayUserId = mangopayUserID;
    status = 1;
}

and whle i update card at that time

    [UserId] => 17431574
    [AccessKey] => 9gHbl11np1yjYhuKF51T
    [PreregistrationData] => I5-F6i4odDiWz3S0GQmyulSYND7gjZqEdIbNoaXh3zu-3OYM0vwsNKu7gM0Kx2KFUE6onk55MkkuWPry3Tn84w
    [CardRegistrationURL] => https://webpayment.payline.com/webpayment/getToken
    [CardId] => 
    [RegistrationData] => errorCode=09101
    [ResultCode] => 105299
    [ResultMessage] => Token input Error
    [Currency] => EUR
    [Status] => ERROR
    [Id] => cardID
    [Tag] => 
    [CreationDate] => 1428129041

 some info here i  hide  as mangopayUserID and cardID for security.. what is incorrect an d where i am going wrong

**Comment by ananarola** [comment]
@hobailey : need ur help

**Comment by ananarola** [comment]
whle i test with sandbox env with my real card everything works but at live it not works

**Comment by hobailey** [comment]
Hi @ananarola,
When you POST the card info, are you definitly posting the data to the CardRegistrationURL given in the CardRegistration object, or are you using a fixed url (which is infact different between sandbox/production etc)?

**Comment by ananarola** [comment]
Thanks for reply. I am so awaited for your reply.
Yes i am using the same fix url. I have no idea about diffrent url which is uesd at production site.
Can you please pass me the production url while is used for get card token and for update card info. ?

**Comment by hobailey** [comment]
OK, so you should *not* be posting the card info to a *fixed URL*, but instead, you should always post it to the CardRegistrationURL that is found in the CardRegistration object for that particular card registration. In the example here (https://github.com/MangoPay/mangopay2-php-sdk/blob/master/demos/paymentDirect/non_js.php#L59), you can see that the action of form is not fixed, but dynamic for that card registration.
Hopefully that makes more sense.

**Comment by ananarola** [comment]
Thank you soo much for reply. Your answer always help me. Highly appriciated

**Comment by ananarola** [comment]
Now i am getting Invalid Card number.
[Status] => FAILED
    [ResultCode] => 105101
    [ResultMessage] => Invalid card number
    [ExecutionDate] => 1428408101

   I am doing 50 rs transaction

**Comment by ananarola** [comment]
Finally done.. Thanks you so much @hobailey....

**Comment by hobailey** [comment]
Great :-)

**Comment by uditkumawat** [comment]
I am getting the same error even in sandbox environment

**Comment by glomrun** [comment]
I am also getting this 09101 in sandbox environment, even if using dynamic CardRegistrationURL.

**Comment by hobailey** [comment]
Hey @anitalanet and @uditkumawat - could you post some code samples please?

**Comment by glomrun** [comment]
For me the problem is solved. These are the two errors I made : 
1 - I made a mistake putting "data=" twice in the url parameters. 
2- I forgot to add the Id of the CardRegistration when doing mangoPay.cardRegistration.init()

**Comment by MickaelLeven** [comment]
hi 
i am getting the same error even in sandbox environment.
my code : 


    // Buid data for registration
    var data_registration = {

        url : mangopay_api + 'cardregistrations',
        type : 'POST',
        headers : {

            'Content-Type' : 'application/json',
            'Authorization' : authorization_mangopay,
        },
        contentType: "application/json",
        dataType: 'json',
        data : JSON.stringify({

            'UserId' : ''+user.mangopay_id,
            'Currency' : 'EUR'
        })
    };

    // Call for request registration
    $.ajax(data_registration)
        .done(function(response) {

            mangoPay.cardRegistration.baseURL = "https://api.sandbox.mangopay.com";
            mangoPay.cardRegistration.clientId = "eden_123456";

            mangoPay.cardRegistration.init({

                cardRegistrationURL : response.CardRegistrationURL,
                preregistrationData : response.PreregistrationData,
                accessKey : response.accessKey,
                Id : response.Id
            });


            // Build card data
            var card_data = {

                cardNumber : number_card,
                cardExpirationDate : date_expired,
                cardCvx : cvx,
                cardType : 'CB_VISA_MASTERCARD'
            }

            // Register card
            mangoPay.cardRegistration.registerCard(
                card_data,
                function(response) {
                    console.log(response);
                    //calback
                    callback({

                        success : true,
                        message : 'Votre carte  a bien été ajouté'
                    });
                },
                function(response) {

                    // Build message
                    if(response.ResultCode == '105202') {

                        message = 'Le numéro de CB est éronné';
                    }
                    else if(response.ResultCode == '105203') {

                        message = 'La date de CB est érronée';
                    }
                    else if(response.ResultCode == '105204') {

                        message = 'Le code de sécurité de CB est érroné';
                    }
                    else {

                        message = 'Une erreur est survenue. Veuillez réssayer plus tard!';
                    }

                    //calback
                    callback({

                        success : false,
                        message : message,
                    });
                }
            )

        })
        .fail(function(response) {

            console.log(response);
            htmlClass.displayMessage('Une erreur est survenue. Veuillez reessayer plus tard')
        });

Help plz

**Comment by gabriellupu** [comment]
@MickaelLeven take a look over https://github.com/Mangopay/mangopay2-nodejs-sdk/issues/49 please
