### ISSUE TITLE
Fatal error : 3.4.1

### ISSUE THREAD

**Issue by tsoko17** [Mangopay/mangopay2-php-sdk#486]
Hi,
Fatal error on the latest version 3.4.1.
You must modify "/php-sdk-v2/MangoPay/Libraries/ApiBase.php" at line 198.
Before:
`  ];`
After
`  );`

**Comment by fredericdelordm** [comment]
Hello @tsoko17,

Thank you for your message. We are fixing this ASAP.

Have a nice day,
