### ISSUE TITLE
3- D secure payment

### ISSUE THREAD

**Issue by jamnarola** [MangoPay/mangopay2-php-sdk#49]
Hello, 

I have implement mangopay in my application, when i make payment larger then 100 i got "009199	PSP technical error".
I have set sandbox mangopay, that's why this error comes?

please give a way to make payment greater then 100.

thanks.

**Comment by hobailey** [comment]
Hi @jamnarola, you need to use different test cards when doing 3DS payments in the sandbox - have a look here: https://docs.mangopay.com/api-references/test-payment/
