### ISSUE TITLE
Call to undefined method stdClass::GetReadOnlyProperties

### ISSUE THREAD

**Issue by Fred-Guile** [Mangopay/mangopay2-php-sdk#501]
Hi,

i'm trying to create a Direct-Debit Direct PayIn :

`
	public function DirectDebit($params) {
		
		try {
      $payIn = new \MangoPay\PayIn();
      $payIn->CreditedWalletId = $params->CreditedUserId;
      $payIn->AuthorId = $params->AuthorId;

      $payIn->DebitedFunds = new \MangoPay\Money();
      $payIn->DebitedFunds->Amount = $params->Amount;
      $payIn->DebitedFunds->Currency = 'EUR';

			$PayIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsDirectDebitDirect();
			$PayIn->PaymentDetails->MandateId = $params->MandateId;

			$PayIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
			$PayIn->ExecutionDetails->Culture = "FR";

			$resultat = $this->Api->PayIns->Create($PayIn);
			$this->log($this->toArray($resultat), "DirectDebit($params->AuthorId, $params->CreditedUserId, $params->Amount, $params->MandateId)");
			return json_encode($this->toArray($resultat));
		} catch(MangoPay\Libraries\ResponseException $e) {
			$this->log($this->toArray($e), "DirectDebit($params->AuthorId, $params->CreditedUserId, $params->Amount, $params->MandateId)");
			return json_encode($this->toArray($e));
		} catch(MangoPay\Libraries\Exception $e) {
			$this->log($this->toArray($e), "DirectDebit($params->AuthorId, $params->CreditedUserId, $params->Amount, $params->MandateId)");
			return json_encode($this->toArray($e));
		} 		
	}
`

Here is the error
`<br />
<b>Notice</b>:  Undefined index: payins_directdebitdirect-direct_create in <b>/web/api/mangopay/mangopay/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php</b> on line <b>200</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined method stdClass::GetReadOnlyProperties() in /web/api/mangopay/mangopay/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php:447
Stack trace:
#0 /web/api/mangopay/mangopay/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php(233): MangoPay\Libraries\ApiBase-&gt;BuildRequestData(Object(stdClass))
#1 /web/api/mangopay/mangopay/vendor/mangopay/php-sdk-v2/MangoPay/ApiPayIns.php(18): MangoPay\Libraries\ApiBase-&gt;CreateObject('payins_directde...', Object(stdClass), '\\MangoPay\\PayIn', NULL, NULL, NULL)
#2 /web/api/mangopay/waster.php(310): MangoPay\ApiPayIns-&gt;Create(Object(stdClass))
#3 /web/api/mangopay/index.php(95): Waster-&gt;DirectDebit(Object(stdClass))
#4 {main}
  thrown in <b>/web/api/mangopay/mangopay/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php</b> on line <b>447</b><br />
`

What am i missing ?

Regards.

**Comment by H4wKs** [comment]
Hi @Fred-Guile ,

I would try to update / reinstall the SDK, look like some of your SDK files may be corrupted.

**Comment by Fred-Guile** [comment]
I've already tried with the latest version but always the same mistake.

Nevermind, our client has changed his mind. Thanx.
