### ISSUE TITLE
sandbox - php sdk sending errors on each call since yesterday (30/06)

### ISSUE THREAD

**Issue by johann-arias** [Mangopay/mangopay2-php-sdk#503]
Hello,

since yesterday afternoon, I'm having following error on every call to the mangopay api I make through de php sdk in sandbox : 

`Uncaught PHP Exception ErrorException: "Notice: unserialize(): Error at offset 0 of 544 bytes" at /Users/johann/Documents/kudurace/dev/kudurace/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/DefaultStorageStrategy.php line 36`

The same code works as expected in production 

Thanks for your help,
Johann

**Comment by H4wKs** [comment]
Hi @johann-arias,
Do you still have an issue ? I personally do not have any problem on Sanbox on my ApiCall.
