### ISSUE TITLE
CardPreAuthorizedPayIn not prensent in the PHP library !

### ISSUE THREAD

**Issue by Diallos** [Mangopay/mangopay2-php-sdk#504]
Seems the CardPreAuthorizedPayIn object is missed in the PHP library like described in the doc in the step 3 [here ](https://docs.mangopay.com/endpoints/v2.01/preauthorizations#e183_the-preauthorization-object), is it a mistake ?

Any plan to include this object in the PHP library ?

**Comment by H4wKs** [comment]
Hi @Diallos,

It's not missing. You just create a Payin, and use the PreAuthorized related ExecutionDetails
`$payIn->ExecutionDetails = new \MangoPay\PayInPaymentDetailsPreAuthorized();`
And then set the Pre Authorized Id for `$payIn->ExecutionDetails->PreauthorizationId`

Cheers,
