### ISSUE TITLE
How to create a new card ?

### ISSUE THREAD

**Issue by Geoffray-buhler** [Mangopay/mangopay2-php-sdk#506]
Hi so i want to create a card for make a payin but i don't understande how i supposed to do 

in first time i create a Cardregistration with this API like that 

Controller :
`if ($form->isSubmitted() && $form->isValid()) {
            $montant = $form->getData();
            $montant = $montant['Montant'];
            $formdata = $form->getData();
            $card = new CardRegistration;
            $card->UserId = $this->getUser()->getMangopayId();
            $card->CardType = $formdata['Cardtype'];
            $card->Currency = $formdata['currency'];
            $result = $mangoservices->CreateCard($card);
            $PreregistrationData = $result->PreregistrationData;
            $CardRegistrationURL = $result->CardRegistrationURL;
            $CardNumber = $formdata['Number'];
            $CardCVV = $formdata['CVV'];
            $CardDate = '';`

Services mangopay :
`    public function CreateCard($card)
    {
        $cardInfo = $this->mangoPayApi->CardRegistrations->Create($card);
        return $cardInfo;
    }`
            
after i create a form to send my data to tokanisation's server like this 

Twig :
`<form action="{{infos['URL']}}" method="post">
        <input type="hidden" name="data" value="{{infos['PreregistrationData']}}">
        <input type="hidden" name="accessKeyRef" value="{{infos['AccessKey']}}">
        <input type="hidden" name="cardNumber" value="{{infos['CardNumber']}}">
        <input type="hidden" name="cardExpirationDate" value="{{infos['CardDate']}}">
        <input type="hidden" name="cardCvx" value="{{infos['CardCVV']}}">
        <input type="hidden" name="returnURL" value="{{ url('app_paymentres') }}">
        <input type="submit" name="submit" value="Accepter">
    </form>`

and i get it to update my card 

Controller :
`
 $Token = $request->query->get('data');
        $data = $mangoservices->GetCard($card->getCardId());
        $data->RegistrationData = $Token;
        $data->ResultMessage = '';
        $data->Status = 'CREATED';
        $result = $mangoservices->UpdateCard($data);
`

Services mangopay :
`
public function GetCard($card_id)
    {
        $cardInfo = $this->mangoPayApi->CardRegistrations->Get($card_id);
        return $cardInfo;
    }
``
    public function UpdateCard($card)
    {
        $cardInfo = $this->mangoPayApi->CardRegistrations->Update($card);
        return $cardInfo;
    }
`

i know, something is wrong, but i really don't know how to do it

thank you

**Comment by fredericdelordm** [comment]
Hello @Geoffray-buhler,

I would suggest to use the following tests as an example : 

- [CardRegistrationsTest](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/tests/Cases/CardRegistrationsTest.php)
- [PayInsTest](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/tests/Cases/PayInsTest.php)

**Comment by H4wKs** [comment]
Hi @Geoffray-buhler ,

You have a working example in the demos directory. Checkout out:
https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/non_js.php
https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/payment.php
Cheers,

**Comment by Geoffray-buhler** [comment]
Thank you so much. 
That work now but i have a new error and i don't understand why but my card is register in mangopay Bdd ^^ 
👍 👍 👍 
![image](https://user-images.githubusercontent.com/55780756/124720743-c010f000-df08-11eb-8a9a-3cf318c57004.png)
But in my App 
![image](https://user-images.githubusercontent.com/55780756/124720849-db7bfb00-df08-11eb-8cc4-ab5c54470bb0.png)

**Comment by fredericdelordm** [comment]
@Geoffray-buhler the error does not say much. What are you trying to do? Could you share your code?

**Comment by Geoffray-buhler** [comment]
So i just follow this docs 

https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/non_js.php
https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/payment.php

After the creation of card i get it and 

Controller :
`    $user = $this->getUser();
        
        $cardRegister = $mangoservices->GetCardRegistrations($_SESSION['cardRegisterId']);
        $cardRegister->RegistrationData = isset($_GET['data']) ? 'data=' . $_GET['data'] : 'errorCode=' . $_GET['errorCode'];

        $updatedCardRegister = $mangoservices->UpdateCard($cardRegister);
`

ServiceMangopay : 
`    public function UpdateCard($card)
    {
        $cardInfo = $this->mangoPayApi->CardRegistrations->Update($card);
        return $cardInfo;
    }
`
i just want to update my card without error ^^

**Comment by H4wKs** [comment]
@Geoffray-buhler,
 
So it look like there may be an issue with the SDK parsing the error, but that's not the problem here anyway, something must be wrong with the data you submit.
 
 Can you provide a dump of $cardInfo just before you return it.
 Maybe you can add a try / catch when you calling CardRegistrations->Update and provide a dump of the exception itself. 
 
 Also, I wouldn't use $_GET and $_SESSION as you are using Symfony, I would rather go by 
 `$request->query->get('data')`
 and use the session interface to store / get the session info

**Comment by Geoffray-buhler** [comment]
i use $_GET and $_SESSION it's just for debug and understand ^^
so this is the data submitted

![image](https://user-images.githubusercontent.com/55780756/124744441-0c672a80-df1f-11eb-8059-8921c72055e7.png)

i can't dump $cardInfo because they is a error before that .

**Comment by H4wKs** [comment]
You need to dump the exception to really understand what is wrong
ServiceMangopay :
`
public function UpdateCard($card) { 
   try {
       $cardInfo = $this->mangoPayApi->CardRegistrations->Update($card); 
       } catch (Exception $e) {
          $cardInfo = null;
          dump($e);
       } 
       return $cardInfo;
   }`

**Comment by Geoffray-buhler** [comment]
i replaced my code with yours but i have the same thing 

![image](https://user-images.githubusercontent.com/55780756/124752036-a03cf480-df27-11eb-8792-fdc044fdd371.png)

result :
![image](https://user-images.githubusercontent.com/55780756/124751839-62d86700-df27-11eb-9b58-22c689f1753a.png)

i don't catch any Exeptions

**Comment by H4wKs** [comment]
I never had this issue with the SDK, but same problem as here https://github.com/Mangopay/mangopay2-php-sdk/issues/500
I would probably dump $error inside the SDK and / or comment out the foreach just to understand both why your ApiCall end up on a 400 instead of 200 code, and at the same time give feedback on what is wrong in the handling of the error at the SDK level.

**Comment by Geoffray-buhler** [comment]
Ok thank you i will try to get $error and dump it. So i'm beginner ^^

**Comment by Geoffray-buhler** [comment]
Ho 
i dump $error

Result:
![image](https://user-images.githubusercontent.com/55780756/124759392-e0a07080-df2f-11eb-92af-44c789a13750.png)

**Comment by H4wKs** [comment]
You're welcome @Geoffray-buhler 

What version of PHP are you running ?

**Comment by Geoffray-buhler** [comment]
I use php 7.4.2 actually.

**Comment by H4wKs** [comment]
I submitted a PR #508 to fix the warning issued in RestTools when the $error->Errors is null like in your case, that should help in the future :)

**Comment by Geoffray-buhler** [comment]
I saw your patch, i apply it but i have new error.

![image](https://user-images.githubusercontent.com/55780756/124889498-704d2a00-dfd7-11eb-9367-9a768f0d90cb.png)

**Comment by Geoffray-buhler** [comment]
No it's ok i don't know why but it's ok ^^ 
![image](https://user-images.githubusercontent.com/55780756/124891421-439a1200-dfd9-11eb-936d-2272b2498a26.png)
