### ISSUE TITLE
Wrong SecureModeReturnURL and SecureModeRedirectURL when apply 3DS

### ISSUE THREAD

**Issue by duykhanh91** [Mangopay/mangopay2-php-sdk#509]
hello guys,
I get two issue when apply 3DS. This is my code when call payin
```
$idCollect = DB::table('collects')->max('id') + 2501;
        $payInSender = new \MangoPay\PayIn();
        $payInSender->AuthorId = $authorId;
        $payInSender->Tag = 'CRAFTMAN PAYS COLLECT';
        $payInSender->CreditedUserId = $creditedUserId;
        $payInSender->DebitedFunds = new \MangoPay\Money();
        $payInSender->DebitedFunds->Currency = 'EUR';
        $payInSender->DebitedFunds->Amount = $money;
        $payInSender->Fees = new \MangoPay\Money();
        $payInSender->Fees->Currency = 'EUR';
        $payInSender->Fees->Amount = $fee;
        $payInSender->CreditedWalletId = $creditedWalletId;

        $payInSender->PaymentDetails = new \MangoPay\PayInPaymentDetailsCard();
        $payInSender->PaymentDetails->CardId = $cardId;
        $payInSender->PaymentDetails->StatementDescriptor = 'BDC' . str_pad($idCollect, 7, '0', STR_PAD_LEFT);
        $payInSender->PaymentDetails->IpAddress = $dataHeader->IpAddress;
        $payInSender->PaymentDetails->BrowserInfo = $dataHeader->BrowserInfo;

        $payInSender->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
        $payInSender->ExecutionDetails->SecureModeReturnURL = 'https://xxx/#/app/craftsmen/3ds-process';
        $payInSender->ExecutionDetails->Requested3DSVersion = "V2_1";
        return $this->mangopay->PayIns->Create($payInSender);
```
And get response
```
SecureModeRedirectURL: "https://api.sandbox.mangopay.com:443/Redirect/ACSWithValidation?token=1be7c2bbc941413c874548aaf83fc58c&mgpsecureid=1be7c2bbc941413c874548aaf83fc58c"
SecureModeReturnURL: "https://xxx?transactionId=113324094#/app/craftsmen/3ds-process"
```
- Issue 1 : SecureModeReturnURL is wrong, it must be https://xxx/#/app/craftsmen/3ds-process?transactionId=113324094
=> on the last checking it is good but now it is wrong format(?transactionId=113324094 must add to end of link)
- Issue 2: we can not access to SecureModeRedirectURL: https://api.sandbox.mangopay.com:443/Redirect/ACSWithValidation?token=1be7c2bbc941413c874548aaf83fc58c&mgpsecureid=1be7c2bbc941413c874548aaf83fc58c
Can you help me check it
thanks

**Comment by H4wKs** [comment]
Hi @duykhanh91,

I would make a quick test and replace 'https://xxx/#/app/craftsmen/3ds-process' by 'https://xxx/app/craftsmen/3ds-process' and see if that generate the URL correctly.
When I click your SecureModeRedirectURL, it works just fine on my side and I got redirected to your site https://ecodrop.apac.****.tech/uat/ecodrop/?transactionId=113324094#/app/craftsmen/deposite/create
So the problem is limited to the wrong formatting of the returnURL and I bet the '/#/' is what make it go wrong.

**Comment by duykhanh91** [comment]
> Hi @duykhanh91,
> 
> I would make a quick test and replace 'https://xxx/#/app/craftsmen/3ds-process' by 'https://xxx/app/craftsmen/3ds-process' and see if that generate the URL correctly.
> When I click your SecureModeRedirectURL, it works just fine on my side and I got redirected to your site https://eco****.apac.****.tech/uat/ecodrop/?transactionId=113324094#/app/craftsmen/deposite/create
> So the problem is limited to the wrong formatting of the returnURL and I bet the '/#/' is what make it go wrong.

Why we get this issue? because on the last checking it is ok but now it is wrong ?

**Comment by H4wKs** [comment]
@duykhanh91 I don't know, I am just another user of this SDK, trying to help you figure out what and where the problem is.
Once the problem is identified, either you did something wrong and you can fix it, either the SDK is broken and any contributor out here can help, either the API is broken and someone from Mango need to fix it.
My suggestion is only to help identify the problem, not a fix.

**Comment by duykhanh91** [comment]
> @duykhanh91 I don't know, I am just another user of this SDK, trying to help you figure out what and where the problem is.
> Once the problem is identified, either you did something wrong and you can fix it, either the SDK is broken and any contributor out here can help, either the API is broken and someone from Mango need to fix it.
> My suggestion is only to help identify the problem, not a fix.

thanks @H4wKs

**Comment by Thithip** [comment]
Hi @duykhanh91,

We have the same issue, with a different SDK language, and it's seems that the `#` in the URL was not properly interpreted by the MangoPay API.

Did you solve your issue?

**Comment by duykhanh91** [comment]
> Hi @duykhanh91,
> 
> We have the same issue, with a different SDK language, and it's seems that the `#` in the URL was not properly interpreted by the MangoPay API.
> 
> Did you solve your issue?

i change to use Hooks

**Comment by Thithip** [comment]
Ok thanks 👌
