### ISSUE TITLE
Payin creation error

### ISSUE THREAD

**Issue by Geoffray-buhler** [Mangopay/mangopay2-php-sdk#511]
After have register my Credit card i want to make a payin request so i have issue when i send it 

PayIn Object passed :
![image](https://user-images.githubusercontent.com/55780756/125750318-f133c6fe-9a2f-455d-98fc-fb7b6ad2b04c.png)

My Mangopayservices : 
![image](https://user-images.githubusercontent.com/55780756/125750373-301cb661-1923-4754-9ab8-f63a75ddd9ec.png)

My controller : 
![image](https://user-images.githubusercontent.com/55780756/125750466-4aae7d05-c986-46b1-bf0b-aabe0ac68018.png)

Error:
![image](https://user-images.githubusercontent.com/55780756/125750708-3e7f3947-3b4f-46d0-b9b5-1833712adc84.png)

I don't know why i have an error 
Thank you ^^

**Comment by H4wKs** [comment]
Hi @Geoffray-buhler,
The error is quite explicit, you're missing the ExecutionDetails for your PayIn, and that's not the only thing missing.
According to the Payin requirement in the MangoPay API documentation ( https://docs.mangopay.com/endpoints/v2.01/payins#e278_create-a-card-direct-payin ) you're missing:
`php
        $payIn->ExecutionDetails = new PayInExecutionDetailsDirect();
        $payIn->ExecutionDetails->SecureModeReturnURL = "https://your.return.url.com";

        $payIn->PaymentDetails->IpAddress = "";
        $payIn->PaymentDetails->BrowserInfo = new BrowserInfo();
        $payIn->PaymentDetails->BrowserInfo->AcceptHeader = "";
        $payIn->PaymentDetails->BrowserInfo->UserAgent = "";
        $payIn->PaymentDetails->BrowserInfo->Language = "";
        $payIn->PaymentDetails->BrowserInfo->ScreenWidth = "";
        $payIn->PaymentDetails->BrowserInfo->ScreenHeight = "";
        $payIn->PaymentDetails->BrowserInfo->ColorDepth = "";
        $payIn->PaymentDetails->BrowserInfo->TimeZoneOffset = "";
        $payIn->PaymentDetails->BrowserInfo->JavaEnabled = "";
        $payIn->PaymentDetails->BrowserInfo->JavascriptEnabled = "";
`

Of couse, you can't leave these fields empty, you need to set the correct values. If you search for BrowserInfo over the issue here, you will see some code example on how to achieve it if you need help with it.

Cheers

**Comment by Geoffray-buhler** [comment]
Ho thank you, i'm sorry but it's my first time to implemente a payment system in web site so i'm sorry if my questions is idiot.

**Comment by SoloJr** [comment]
Hi @Geoffray-buhler 

Mircea from the MangoPay SDKs team. We all started somewhere. There are no questions that should/could be labeled as idiot. 

Keep it up and all the best :)

**Comment by H4wKs** [comment]
@Geoffray-buhler don't worry, we have all been in that first time situation, we all learn new stuff everyday, that's half the fun :)
There are no idiot question, and I am very sorry if my answer made you think that. The idea was more that most of the time, the error message will point you in the right direction, and reading the documentation will also show you what the API is expecting.
