### ISSUE TITLE
PSP technical error: 009199 on Sandox

### ISSUE THREAD

**Issue by julien-jourde** [Mangopay/mangopay2-php-sdk#514]
Hello,

Today, I have an issue when I create a PayIn. SandBox return `PSP technical error: 009199`.
When I disable 3D Secure, it's work fine, but when I test with 3D secure (3DS2), it's happen this error.
Yesterday, all worked fine. The code has not been updated.

**Comment by julien-jourde** [comment]
Hum, at 10:18 GMT, it's works :sweat_smile:
It's little bit weird.

**Comment by dduwoyemgp** [comment]
Hello @julien-jourde 
Thank you for sharing your issue with us.

Are you still encountering the bug you've described?

**Comment by julien-jourde** [comment]
Hello @dduwoyemgp ,
Since my last comment, I no longer encounter this issue.
I think it's bug on sandbox environment but not directly the SDK itself.
