### ISSUE TITLE
Payin Card Direct SecureModeRedirectURL Issue Production Environment

### ISSUE THREAD

**Issue by lieferbaer** [Mangopay/mangopay2-php-sdk#515]
Hello mangopay team, 
there is a secureModeNeeded issue at PRODUCTION environment. Sometimes we are getting from payin card direct secureModeNeeded = true but there is NO SecureModeRedirectURL in the response! 

At 3DS2-Integration-Documentation stays: 
4. When SecureModeNeeded=TRUE, you redirect the user to the SecureModeRedirectUrl. This redirection is mandatory for the payment to succeed.

We were not able to redirect the user to SecureModeRedirectURL, which means the user was not able to authorize the payment. Curiously the status of payment is SUCCEEDED! We are very confused.

So that we dont want to have problems, we are not creating the order at our platform and refunding the payin. We contacted last week the service@mangopay.com and had a call last week but there is no concrete response.
 
Please get in contact with us ASAP. 
lbproduction

**Comment by fredericdelordm** [comment]
Hello @lieferbaer,

I am looking into it

**Comment by lieferbaer** [comment]
hello, we are still waiting and having same issue.
