### ISSUE TITLE
Card registration

### ISSUE THREAD

**Issue by SonicxPrime** [Mangopay/mangopay2-php-sdk#519]
Hello everyone,

I'm new in Mangopay api and i would like to ask if we have to register card in every operation or we can just get id of an existing card.

Thanks in advance,
SonicxPrime

**Comment by fredericdelordm** [comment]
Hello @SonicxPrime,

You can just the ID of the card for payin or pre auth after registration.

**Comment by SonicxPrime** [comment]
Hello Frédéric,

Thank you fro you help.
