### ISSUE TITLE
register a card during web payin

### ISSUE THREAD

**Issue by saiqiong** [Mangopay/mangopay2-php-sdk#523]
Hi,

I would like to know if there is a way that I can register a card during a web payin?
I am currently using my own template for web payin, the difficulty is that there is no way to get the detailed card info(card number, cvv etc) during(or even after )the web payin. 

Thanks a lot

**Comment by fredericdelordm** [comment]
Hi @saiqiong,

Unfortunately, it's not possible to register a card during a web payin.

If you want to customize your payment page, please look [here](https://docs.mangopay.com/guide/customising-the-design)

**Comment by saiqiong** [comment]
Hi @fredericdelordm 
Thanks for response, right now our business logic is letting the user have the option to choose if he/she want to register the card during web payin(no problem for customising the page payment for that part), we don't want a separate interface for user to register the card ,  are you saying that mangopay is not possible to achieve that?

**Comment by fredericdelordm** [comment]
Hello @saiqiong,

For web payin, the payment page is a MANGOPAY page. You can't create a card registration object. You cannot also customize the page.

If you want to customize the page, you have to use other types of payin and card registration. You can deactivate the card and delete the token after the payin.

Is that clear for you ? Don't hesitate to contact our team (you can ask for Eva), they will guide you regarding your business case and workflow

**Comment by saiqiong** [comment]
@fredericdelordm 
Thanks very much for your answer, for web payin, the page is a MANGOPAY page(we can do some sort of customisation css text change etc, but yes, it's MANGOPAY who is taking control of the page) , would you mind sharing me the contact of Eva? 
Thanks a lot.
Have a nice day.

**Comment by fredericdelordm** [comment]
@saiqiong just use the [hub](https://hub.mangopay.com/support) to contact the MANGOPAY team :).

**Comment by saiqiong** [comment]
@fredericdelordm Thanks a lot:)
