### ISSUE TITLE
WebpayIn issue in Sandbox

### ISSUE THREAD

**Issue by jpthecreator** [Mangopay/mangopay2-php-sdk#525]
Hi guys

There is an issue when attempting to process WebpayIn within sandbox, the form shows the amount to pay in and an error underneath that states 'an error occured when initialising the payment'. This is coming from the MangoPay hosted servers via iFrame.

Thanks
JP

**Comment by fredericdelordm** [comment]
Hello @jpthecreator,

We are investigating.

Have a nice day,

**Comment by jpthecreator** [comment]
Hi @fredericdelordm 

Actually this was resolved by removing TemplateURL and using RedirectURL

Thanks
JP
