### ISSUE TITLE
URGENT!!! PayIns fail in Mangopay production sporadically

### ISSUE THREAD

**Issue by Dekari** [Mangopay/mangopay2-php-sdk#528]
From 30/09 I am getting such errors for PayIns:

    [_errorInfo:MangoPay\Libraries\ResponseException:private] => MangoPay\Libraries\Error Object
        (
            [Message] => Sequence contains no elements
            [Errors] => 
            [Id] => 72a830c5-4f28-4ee1-9de9-6a386a81bb86#1633157785
            [Date] => 1633157786
            [Type] => invalid_action
        )

What is happening? Is it related to the 30/09 CA certificate issue maybe? Anyone else experiencing this?

Full request:
 [0] => /payins/card/direct/
                            [1] => POST
                            [2] => Array
                                (
                                    [CreditedWalletId] => 32989133
                                    [IpAddress] => 46.12.224.10
                                    [BrowserInfo] => stdClass Object
                                        (
                                            [AcceptHeader] => application/json, text/javascript, */*; q=0.01
                                            [ColorDepth] => 24
                                            [JavaEnabled] => false
                                            [JavascriptEnabled] => true
                                            [Language] => el-GR
                                            [ScreenHeight] => 768
                                            [ScreenWidth] => 1366
                                            [TimeZoneOffset] => -180
                                            [UserAgent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0
                                        )

                                    [CardId] => 1870190741
                                    [AuthorId] => 1868966700
                                    [CreditedUserId] => 32989132
                                    [DebitedFunds] => MangoPay\Money Object
                                        (
                                            [Currency] => EUR
                                            [Amount] => 5600
                                        )

                                    [Fees] => MangoPay\Money Object
                                        (
                                            [Currency] => EUR
                                            [Amount] => 0
                                        )

                                    [tag] => Book ID:54429
                                    [SecureModeReturnURL] => https://www.keeppet.gr/index.php?option=com_keeppet&task=book.mangoPreApprovePayWebhook

**Comment by fredericdelordm** [comment]
Hello @Dekari,

I'll share your issue with the appropriate team.

I'll keep you updated.
