### ISSUE TITLE
Authentification with first CreateRecurringPayInRegistrationCIT requires to not have NO DebitedFunds nor fees

### ISSUE THREAD

**Issue by Hmastery** [Mangopay/mangopay2-php-sdk#537]
While the documentation specifies that Fees and DebitedFunds are optional (https://docs.mangopay.com/endpoints/v2.01/payins#e1053_create-a-recurring-payin-cit), for the first CIT that will auth your RecurringRegistration (and only for this one) it is forbidden to use these two parameters.

If you use these params it generates a generic Fatal Error, I had to call MangoPay Technical support to deep dive into their logs in order to understand this issue.

**Comment by fredericdelordm** [comment]
Hello @Hmastery, we are looking into it

**Comment by SoloJr** [comment]
Hi @Hmastery 

Actually, that's the behaviour and there's nothing that can be changed in the SDK. 
Please take a look at [this test](https://github.com/Mangopay/mangopay2-php-sdk/commit/4486ea204daaa35e8fa3c7c6b5ea865b468e313e#diff-2dbc0d72122601a01ba9a82c9c8dac334abd375210c3ff5a41f200308059c42eR567), that shows how you can use DebitedFunds and Fees in a CIT.

**Comment by Hmastery** [comment]
Alright :) 
Yeah I integrated it taking into account that behaviour. It’s just that it was not documented properly in the API doc. And there is/was no specific error message to help us understand what went wrong.

**Comment by SoloJr** [comment]
I get you, but the intended behaviour from our side is that we throw the API error. Basically each SDK calls an .NET API and we just parse their error.. :)
