### ISSUE TITLE
Problem with recurring payin registration 

### ISSUE THREAD

**Issue by pulsarf0x** [Mangopay/mangopay2-php-sdk#539]
Hello there,

I've a problem that I can't deal with. 
Could you check this screenshot ? My problem is about that I've filled every required params with the good values but still getting the following error :
![image](https://user-images.githubusercontent.com/19839464/147692081-6c98f682-e5c9-40e4-a5c9-62f940f1ac45.png)

![image](https://user-images.githubusercontent.com/19839464/147692244-6e949b18-5794-4461-a665-b690a150a7e9.png)

`Bad request. One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.`

Thank you so much team, this thing is making me mad. I can't count times I checked it and checked it again. 😂
Have a nice evening.

**Comment by fredericdelordm** [comment]
Hello @pulsarf0x,

Your error is due to : 

- "FixedNextAmount"
- "FractionedPayment"
- "Migration"

They are boolean and you have set them to "null".

Regards and Happy new year !

**Comment by fredericdelordm** [comment]
@pulsarf0x Don't hesitate to look at the field "errors" in the response to debug faster.

**Comment by pulsarf0x** [comment]
Hello, 

Happy new year too.
It works now. Thank you. :) But it means those properties aren't really optionnal, right ?
