### ISSUE TITLE
There should be a function to get all ubo of a ubo declaration.

### ISSUE THREAD

**Issue by PeeyushAgrawalWebkul** [Mangopay/mangopay2-php-sdk#541]
As mentioned - https://github.com/Mangopay/mangopay2-php-sdk/blob/3.10.0/MangoPay/ApiUboDeclarations.php#L80
this is a function which is using ubo id, user id and ubo declaration id to get the ubo details. Here ubo_get is used.

There is no function which can return the list of ubo by using ubo declaration id and user id (like https://github.com/Mangopay/mangopay2-php-sdk/blob/3.10.0/MangoPay/ApiUboDeclarations.php#L20 here all ubo declaration is getting return using user id only).

**Comment by fredericdelordm** [comment]
Hello @PeeyushAgrawalWebkul , this is currently not available in the API. I'll keep your feedback and share it to the API team.
