### ISSUE TITLE
List a User's Transactions limit

### ISSUE THREAD

**Issue by jeromebsr** [Mangopay/mangopay2-php-sdk#542]
Hi there, 

I try to get all user transactions but I only can get 10. Is there a limit ?

```php
    /**
     * @return array
     */
    public function getUserTransactions(): array
    {
        return $this->loadApi()->Users->GetTransactions($this->getMangoPayUser()->Id);
    }
```

![Capture d’écran 2022-02-07 145247](https://user-images.githubusercontent.com/49365926/152800929-cab8a832-686f-429c-a469-f62befbd861e.png)

Thanks,

**Comment by H4wKs** [comment]
Hi @jeromebsr,

The MangoPay API return by default up to 10 results, you can read about this limitation here : 
https://docs.mangopay.com/guide/lists-pagination-management

If you give a look to the GetTransactions function you can see this : 
```php
<?php
public function GetTransactions($userId, & $pagination = null, $filter = null, $sorting = null)
```

So to get for example the first 100 transactions, you can do : 
```php
$pagination = new \MangoPay\Pagination(1, 100);
$transaction = $mangoPayApi->Users->GetTransactions($mangoPayUserId, $pagination);
```
100 is the maximum item per page you can set, then you need to use the pagination per page.

Better late then never, I hope this help, if not it may help someone else :)

Cheers

**Comment by jeromebsr** [comment]
Hi ! Thanks for that :)

Can you help me on another issue ?

I would like to make the buyer pay the fees and not the seller, and by default it is the seller who will pay them, I can't charge the buyer's wallet.

Do you have an idea ? I've been around the doc and called mangopay but no one can help me with this.

**Comment by H4wKs** [comment]
I would just add the fee to the selling price / debited funds.

Exemple:
Your seller sell a product for an amount of 20€ and you want to charge 10% fee for the platform.
Fee are here equal to 2€
So debited fund = amount + fee = 22€
Buyer pay 22€, you get 2€ fee and seller get the 20€ which is the initial selling price so all the fee are supported by the buyer.

**Comment by jeromebsr** [comment]
Thanks,

Agree with that but when I call $PayIn->Fees->Amount, the value passed will automaticly debited on the seller's wallet. It's on this point I can't change the wallet debited. 

If I don't use $PayIn->Fees, the platform will never receive the fee.

Here is my current code :

```
public function payIn(): string
    {
        // update register card with registration data from Payline service
        $cardRegister = $this->getCardRegistration();
        $cardRegister->RegistrationData = isset($_GET['data']) ? 'data=' . $_GET['data'] : 'errorCode=' . $_GET['errorCode'];
        $updatedCardRegister = $this->loadApi()->CardRegistrations->Update($cardRegister);
        $fees = $_SESSION['checkout']['fees']*100;

        if($updatedCardRegister->Status != CardRegistrationStatus::Validated || !isset($updatedCardRegister->CardId))
        {
            die('<div style="color:red;">Cannot create card. Payment has not been created.<div>');
        }

        // get created virtual card object
        $card = $this->loadApi()->Cards->Get($updatedCardRegister->CardId);

        // check if a wallet already exists
        if($this->getUserWallet() !== null)
        {
            $wallet = $this->getUserWallet();
        }else {
            $wallet = $this->createUserWallet($this->getMangoPayUser()->Id);
        }

        // check if it's a credit wallet or payin from announce
        $walletId = $_SESSION['checkout']['seller_wallet_id'] ?? $wallet->Id;

        $payIn = new PayIn();
        $payIn->CreditedWalletId = $walletId;
        $payIn->AuthorId = $updatedCardRegister->UserId;
        $payIn->DebitedFunds = new Money();
        $payIn->DebitedFunds->Amount = $_SESSION['checkout']['amount']*100;
        $payIn->DebitedFunds->Currency = "EUR";
        $payIn->Fees = new Money();
        $payIn->Fees->Currency = "EUR";
        if(isset($fees) && $fees > 0)
        {
            $payIn->Fees->Amount = $fees;
        }else {
            $payIn->Fees->Amount = 0;
        }

        // payment type as CARD
        $payIn->PaymentDetails = new PayInPaymentDetailsCard();
        $payIn->PaymentDetails->CardType = $card->CardType;
        $payIn->PaymentDetails->CardId = $card->Id;

        // execution type as DIRECT
        $payIn->ExecutionDetails = new PayInExecutionDetailsDirect();
        $payIn->ExecutionDetails->SecureModeReturnURL = 'http://test.com';

        $createdPayIn = $this->loadApi()->PayIns->Create($payIn);

        // if created Pay-in object has status SUCCEEDED it's mean that all is fine
        if ($createdPayIn->Status == PayInStatus::Succeeded) {
            return true;
        } else {
            // if created Pay-in object has status different than SUCCEEDED
            // that occurred error and display error message
            return false;
        }
    }
```

**Comment by H4wKs** [comment]
> EDIT : Solved ! Thank you for your help !

I was about to answer your message but I guess you figured it out :)

**Comment by jeromebsr** [comment]
> > EDIT : Solved ! Thank you for your help !
> 
> I was about to answer your message but I guess you figured it out :)

Yes indeed ! Just add the fee to the amount and that's it ! I was too focused on Fees object ^^

**Comment by H4wKs** [comment]
> Yes indeed ! Just add the fee to the amount and that's it !

Exactly. 

> I was too focused on Fees object ^^

Sometime, we struggle more with the most easiest things, it's so simple that we just don't see it, happen to me all the time.
