### ISSUE TITLE
psr/log 2 not compatible

### ISSUE THREAD

**Issue by Gonzalo1987** [Mangopay/mangopay2-php-sdk#543]
It would be possible to add compatibility with psr/log ^2 to the composer.json or this repository has any constraint or limitation?

"psr/log": "^1.0|^2.0"
"psr/log": ">1.0"

It would be really appreciated.

Thanks!

**Comment by fredericdelordm** [comment]
Hello @Gonzalo1987,

Let me look into that.

Have a nice day,

**Comment by Gonzalo1987** [comment]
Hello @fredericdelordm , 
Could you take a look at it? 

Thank you!

**Comment by Gonzalo1987** [comment]
Thanks, closed!
