### ISSUE TITLE
Payconiq Mobile issue

### ISSUE THREAD

**Issue by mariusconstantin2503** [Mangopay/mangopay2-php-sdk#545]
Hi,
I am trying to implement the Payconiq method for payin using your package but I have a issue on mobile. The link received on DeepLinkUrl property from PaymentDetails is not opening the app on the mobile if the app has been already installed. I contacted mangopay support and they say to use the link from checkout property from below image.
![image](https://user-images.githubusercontent.com/4282568/157280202-b3f233e7-48e6-48ef-a2e7-0086f4071e3d.png)

How can I access it?

Thanks

**Comment by fredericdelordm** [comment]
Hello @mariusconstantin2503,

Could you share with me the ID of your support ticket please?
