### ISSUE TITLE
cURL error: Could not resolve host: api.mangopay.com

### ISSUE THREAD

**Issue by lieferbaer** [Mangopay/mangopay2-php-sdk#548]
Hello Mangopay-Team,

since yesterday we are receiving some times "cURL error: Could not resolve host: api.mangopay.com" error at production. We have the latest sdk version. Could you please check that.

Thanks

**Comment by H4wKs** [comment]
Hi @lieferbaer,

I don't think this is SDK related, and I would rather contact the support by email or phone about this.

**Comment by fredericdelordm** [comment]
Hello @lieferbaer,

Do you still have the issue? Did you contact the support team?

**Comment by lieferbaer** [comment]
Hello Mangopay-Team,
we dont have this issue any more, since we changed our DNS-Server to 8.8.8.8. The Issue was most probably on DNS of our server provider.
