### ISSUE TITLE
Docs misleading for Rate Limiting

### ISSUE THREAD

**Issue by chrs-myrs** [Mangopay/mangopay2-php-sdk#549]
The main readme suggests that $rateLimit->ResetTimeTimestamp contains the number of milliseconds until the limit reset.  This is evidently wrong and contradicts the information in the API and PHPDoc documentation.  My code is currently waiting 19 days between each call :laughing:

**Comment by fredericdelordm** [comment]
Hello @chrs-myrs,

Thanks for the feedback, we are going to fix this readme.

**Comment by iulian03** [comment]
Hi @chrs-myrs,

I'm not sure I understand your issue. The current Readme and docs state that **$ResetTimeTimestamp** represents the _time in unix timestamp **WHEN** the number of allowed calls in this time interval will be reset_ , and NOT _the number of milliseconds **until** the limit reset_.

Could you please clarify?

Thanks!
