### ISSUE TITLE
Call to undefined method MangoPay\MangoPayApi::getLogger()

### ISSUE THREAD

**Issue by lalainarahajason** [Mangopay/mangopay2-php-sdk#550]
Hello,

Anyone had this issue ? and why this happening ? i installed last version through composer, worked fine and suddenly i get this error message : 
`Call to undefined method MangoPay\MangoPayApi::getLogger()` 

Thank you

**Comment by H4wKs** [comment]
Hi @lalainarahajason 

Could you give more context about when this happen ? You have an example of what trigger this error ?

**Comment by fredericdelordm** [comment]
Hello @lalainarahajason, we are looking into it.

As suggested by @H4wKs, could you provide more context please ?
