### ISSUE TITLE
Problem recurring payment

### ISSUE THREAD

**Issue by Maximus697** [Mangopay/mangopay2-php-sdk#553]
Hi,

I'm trying to set up recurring payment on my site except I have the SDK returning to me: Bad request. One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.

$PayIn 							= new \MangoPay\PayInRecurringRegistration();
$PayIn->CreditedWalletId			= $mp_wallet_id;
$PayIn->AuthorId 					= $mp_client_id;
$PayIn->FirstTransactionDebitedFunds 				= new \MangoPay\Money();
$PayIn->FirstTransactionDebitedFunds->Currency	= $currency;
$PayIn->FirstTransactionDebitedFunds->Amount		= $amount;
$PayIn->FirstTransactionFees 					= new \MangoPay\Money();
$PayIn->FirstTransactionFees->Currency 			= $currency;
$PayIn->FirstTransactionFees->Amount 			= $fees;
$PayIn->EndDate 				= $endDate;
$PayIn->Frequency 			= $frequency;
$PayIn->CardId 				= $card_id;

$result = $this->mangoPayApi->PayIns->CreateRecurringRegistration($PayIn);

What is bad?

Thank you

**Comment by H4wKs** [comment]
Hi @Maximus697,

It's hard to say without knowing the value set in your PayIn object.
Can you provide a dump of $PayIn just before calling the MangoPayApi ?

Also, getting the API detailed error message would help you understand the exact problem.

I would suggest you to do the following : 
```php 
try {
   $result = $this->mangoPayApi->PayIns->CreateRecurringRegistration($PayIn);
} catch (Exception $e) {
   //dump or log the value of 
   // $e->GetErrorDetails()->Message and get_object_vars($e->GetErrorDetails()->Errors)
}
```
