### ISSUE TITLE
Error : This endpoint is not available for your account

### ISSUE THREAD

**Issue by lalainarahajason** [Mangopay/mangopay2-php-sdk#557]
Hello, 
When i want to make an INSTANT_PAYMENT from Postman i receive following error (Mangopay has already activated instant payounts) , below is my request : 

`{
"AuthorId": "xxxxxx", 
"DebitedFunds": {
    "Currency": "EUR",
    "Amount": 20
},
"Fees": {
    "Currency": "EUR",
    "Amount": 0
},
"BankAccountId": "xxxx",
"DebitedWalletId": "xxxxx",
"BankWireRef": "invoice 7282",
"PayoutModeRequested": "INSTANT_PAYMENT"
}`

And the response i receive : 

`{
    "Message": "This endpoint is not available for your account",
    "Type": "forbidden_ressource",
    "Id": "5e2ad6b9-1960-430c-a928-e6e96be8ccbb#1652631413",
    "Date": 1652631414.0,
    "errors": null
}`

Someone can explain me why please ?

Thank you

**Comment by fredericdelordm** [comment]
Hello @lalainarahajason,

You need to contact MANGOPAY support through the hub. They will activate the feature for you.

Have a nice day,

**Comment by lalainarahajason** [comment]
Hi, as you see on my post "Mangopay already activated the feature" but the API response remains the same

Thank you
