### ISSUE TITLE
Allow to include TermsAndConditionsAccepted (set to true) in request when it has already been accepted

### ISSUE THREAD

**Issue by QuentinGab** [Mangopay/mangopay2-php-sdk#560]
### Problem:
After that the value of `TermsAndConditionsAccepted` has been set the first time, the api will always throw an error if a new request include `TermsAndConditionsAccepted` in its body:
> The user already accepted our terms and conditions

### Suggestion:
In order to be able to update manopay user without remembering if the user accepted or not mangopay terms (which means store this info in our db), you could ignore true value of `TermsAndConditionsAccepted` if already accepted (i.e not throw an error)

**Comment by fredericdelordm** [comment]
Hello @QuentinGab,

Great feedback. We are reviewing this with the API team
