### ISSUE TITLE
Can not create a new user

### ISSUE THREAD

**Issue by d4rk0snet** [Mangopay/mangopay2-php-sdk#562]
Hi there,

I just  upgraded from 3.6 to 3.15 and i can't create a new natural user in mango pay sandbox.
Here is my object : 

object(MangoPay\UserNatural)#1687 (20) {
  ["FirstName"]=>
  string(6) "hello"
  ["LastName"]=>
  string(6) "you"
  ["Address"]=>
  NULL
  ["Birthday"]=>
  int(1656672943)
  ["Nationality"]=>
  string(2) "FR"
  ["CountryOfResidence"]=>
  string(2) "FR"
  ["Occupation"]=>
  string(14) "Administrateur"
  ["IncomeRange"]=>
  int(3)
  ["ProofOfIdentity"]=>
  NULL
  ["ProofOfAddress"]=>
  NULL
  ["Capacity"]=>
  NULL
  ["PersonType"]=>
  string(7) "NATURAL"
  ["Email"]=>
  string(24) "michael@gmail.com"
  ["KYCLevel"]=>
  NULL
  ["TermsAndConditionsAccepted"]=>
  NULL
  ["TermsAndConditionsAcceptedDate"]=>
  NULL
  ["UserCategory"]=>
  NULL
  ["Id"]=>
  NULL
  ["Tag"]=>
  string(17) "Utilisateur #3161"
  ["CreationDate"]=>
  NULL
}

I checked again sdk documentation, and i don't see anything invalid or missing.
When i try to create it, i get a 400 exception.

Any clues ?

**Comment by fredericdelordm** [comment]
Hello @d4rk0snet,

Do you still have the issue?
