### ISSUE TITLE
Autofill Payment Details

### ISSUE THREAD

**Issue by LENAshopde** [Mangopay/mangopay2-php-sdk#566]
I have a question regarding autofill functions. Currently, customers in our online shop [https://shop.lena.de/](url) have to fill in their payment details every time they perform a new purchase. 

Does Mangopay offer a service of presenting already used payment methods (such as credit card details) in the process of payment to a returning customer, similar to Amazon? This way it should be possible to store payment details in the customer's account in the LENA marketplace. 

Unfortunately, Mangopay could not give me a complete solution to this problem. 

Thanks for your help!

**Comment by H4wKs** [comment]
Hi @LENAshopde 

You can register a user credit card, and next time he want to pay, he can just choose that registered card to pay with, just like on Amazon. 
You can read more about this feature here : https://docs.mangopay.com/endpoints/v2.01/cards#e177_the-card-registration-object.

Cheers,

Marc

**Comment by LENAshopde** [comment]
Hi Marc,

Thank you very much for your feedback. This requires, however, that the payment process is configured as direct payin, correct? We implemented it as web payin. Do we have to switch to direct payin? Or is there also an option for our current setup?

Cheers
Tilman
________________________________
Von: Marc ***@***.***>
Gesendet: Montag, 12. September 2022 18:21
An: Mangopay/mangopay2-php-sdk ***@***.***>
Cc: ***@***.*** ***@***.***>; Mention ***@***.***>
Betreff: Re: [Mangopay/mangopay2-php-sdk] Autofill Payment Details (Issue #566)


Hi @LENAshopde<https://github.com/LENAshopde>

You can register a user credit card, and next time he want to pay, he can just choose that registered card to pay with, just like on Amazon.
You can read more about this feature here : https://docs.mangopay.com/endpoints/v2.01/cards#e177_the-card-registration-object.

Cheers,

Marc

**Comment by H4wKs** [comment]
Hi Tilman,

> This requires, however, that the payment process is configured as direct payin, correct?

Yes.

> We implemented it as web payin. Do we have to switch to direct payin? Or is there also an option for our current setup? 

I am afraid you have to switch to direct payin here.

Cheers,

Marc

**Comment by ataldev** [comment]
> You can register a user credit card, and next time he want to pay, he can just choose that registered card to pay with, just like on Amazon.

But we have to ask for the CVV, and I don't know how to confirm the CVV, I couldn't find anything about this in the documentation.

**Comment by H4wKs** [comment]
So, I did this a long time ago, and since MangoPay decided to terminate our contract with them, I am not using their solution anymore, and I am not updated with the latest changes, so my answer may not be accurate, but at least you get an answer from someone :)

Unless things have changed, you don't need to check the CVV, MangoPay will do it for you.
Once a user add a card, you need to make a payment with it to validate it. You won't be able to make an MIT (merchant initiated transaction) until you first do a CIT (customer initiated transaction).
