### ISSUE TITLE
Log with LoggerInterface

### ISSUE THREAD

**Issue by garak** [Mangopay/mangopay2-php-sdk#57]
It would be nice if ``MangoPay\Libraries\Log`` implement [LoggerInterface](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md)

**Comment by hobailey** [comment]
Ok, we'll look into the feasibility of this - in the meantime, don't hesitate to send a pull request if you get the chance to work on this yourself :-)

**Comment by iammichiel** [comment]
Any news on this? Debugging interaction with MangoPay is a horrible experiment at the moment...

**Comment by garak** [comment]
I'm afraid that this issue is just a symptom of a general bad architecture of this project.
It should be re-projected from scratch, allowing more decoupling between objects, using inversion of dependency.

**Comment by iammichiel** [comment]
I'm working on it. ;)

**Comment by hobailey** [comment]
This has now been implemented via #69 - thanks very much @iammichiel :-)
