### ISSUE TITLE
Giropay doesn't redirect to returnURL at Production

### ISSUE THREAD

**Issue by lieferbaer** [Mangopay/mangopay2-php-sdk#570]
Hello Mangopay-Team,
since 5 days there is a issue at giropay payments on production, in sandbox it still working. I tried it myself and can describe the issue:

everything works as expected, except redirection to our page. 
On this step, the page is showing for 30 seconds: “the return Url will determined. You will redirected as son as possible…”.
After 30 seconds: it shows a technical error: “Unfortunately, due to a technical problem we could not redirect you back to the online store. However, Leetchi Corp. SA has been informed…”
Now the payer can do nothing (no cancel or retry button) and the money is debited from bank account.
(My Bank was Sparkasse)
I did payinView to see the ReturnURL, it was correct.

2. issue:
If I check the payin status: it is failed. 
I informed the mangopay-support team, to refund this payments.

Thanks

**Comment by H4wKs** [comment]
@lieferbaer,

This doesn't sound to be a problem related to the MangoPay PHP SDK, therefore I would suggest you to contact MangoPay Support team by email or phone to have a follow up with them on this.

**Comment by fredericdelordm** [comment]
Hello @lieferbaer ,

Indeed it's an issue with the partner.

I'm closing the issue since Giropay has been deactivated in production. You will receive a message if the situation evolves.
