### ISSUE TITLE
ClientId in authentication url

### ISSUE THREAD

**Issue by qdequippe** [Mangopay/mangopay2-php-sdk#576]
| Q           | A         |
| -------  | ------ |
| Version | 3.16.2 |

Hi,

With the [addition](https://github.com/Mangopay/mangopay2-php-sdk/commit/8bd9e527a47aecf43aff7a4bfcdbc0bea14ed7a6#diff-bb87b9d05608ffadf921aecafc1ac85048090d7a8f61bc156bd072a7560ad3ba) of `$clientIdRequired` to `GetObject` and to `RestTool` all authentication requests are prefixed the clientId.

This cause authentication errors and all requests failed.

```
http://localhost/v2.01/test/oauth/token
```

---

**Steps to reproduce**

1. Clone this repository
2. Add `var_dump($this->_requestUrl)` in `MangoPay\Libraries\RestTool.php` line 182 (see example below)
3. Run tests

```
# MangoPay\Libraries\RestTool.php line 182

private function BuildRequest($urlMethod, $pagination, $additionalUrlParams = null, $idempotencyKey = null)
{
    $urlTool = new UrlTool($this->_root);
    $restUrl = $urlTool->GetRestUrl($urlMethod, $this->_clientIdRequired, $pagination, $additionalUrlParams);
    $this->_requestUrl = $urlTool->GetFullUrl($restUrl);
    var_dump($this->_requestUrl);
    ....
```

**Actual result**

```
$ ./vendor/bin/phpunit

PHPUnit 9.5.26 by Sebastian Bergmann and contributors.

.string(67) "https://api.sandbox.mangopay.com/v2.01/sdk-unit-tests/users/natural"
string(66) "https://api.sandbox.mangopay.com/v2.01/sdk-unit-tests/oauth/token/"
string(87) "https://api.sandbox.mangopay.com/v2.01/sdk-unit-tests/users/155912793/bankaccounts/iban"
...
```

**Comment by qdequippe** [comment]
A workaround is to use version `3.14.1`

**Comment by fredericdelordm** [comment]
Hello @qdequippe, we are looking into it
