### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by garak** [Mangopay/mangopay2-php-sdk#58]
My implementation of Mangopay is working on my local machine, but not on my remote server, where I get an "Unauthorized error" (without further information), using the same credentials on api sandbox.
The main difference I can see is curl version (being 7.35.0 on my local machine and 7.26.0 on remote server).
I don't see any specific curl requirements here, could be curl version a problem?
Is there anything else I could check?

**Comment by garak** [comment]
This is a stack trace, maybe it could be useful
```
  [MangoPay\Libraries\ResponseException]  
  Unauthorized   

Exception trace:
 () at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php:289
 MangoPay\Libraries\RestTool->CheckResponseCode() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php:131
 MangoPay\Libraries\RestTool->RunRequest() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php:98
 MangoPay\Libraries\RestTool->Request() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiOAuth.php:27
 MangoPay\Libraries\ApiOAuth->CreateToken() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthorizationTokenManager.php:31
 MangoPay\Libraries\AuthorizationTokenManager->GetToken() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthenticationHelper.php:62
 MangoPay\Libraries\AuthenticationHelper->GetHttpHeaderStrong() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthenticationHelper.php:25
 MangoPay\Libraries\AuthenticationHelper->GetHttpHeaderKey() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php:264
 MangoPay\Libraries\RestTool->GetHttpHeaders() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php:186
 MangoPay\Libraries\RestTool->BuildRequest() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php:97
 MangoPay\Libraries\RestTool->Request() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php:204
 MangoPay\Libraries\ApiBase->GetList() at mydocroot/vendor/mangopay/php-sdk-v2/MangoPay/ApiUsers.php:35
```

**Comment by hobailey** [comment]
Hi @garak, have you recently updated the SDK version? If so, you'll need to delete your temporary oauth file so that it's recreated.

**Comment by garak** [comment]
If you talking about ``MangoPaySdkStorage.tmp.php`` file, there is no such file on my remote server, I guess it's still not created, since the error is occurring before.
I tried to delete such file on my local machine, it's re-created and everything is working fine. I also tried to copy my local file to remote server and put in the correct path, and I get a slightly different error ("Unauthorized. Your authorization do not allow you to access to this information"), but I guess it's just a bad try

**Comment by garak** [comment]
My bad, the production server was using the non-sandbox api. Sorry :disappointed:

**Comment by hobailey** [comment]
Ah ok, great stuff - thanks for the update :-)

**Comment by AJ-20** [comment]
Hello we have this error, can someone help us thx a lot

An uncaught Exception was encountered
Type: MangoPay\Libraries\ResponseException

Message: Unauthorized

**Comment by chintan12** [comment]
Same error getting.

**Comment by XemaA** [comment]
Hello! I am getting this error Uncaught PHP Exception MangoPay\Libraries\Exception: "cURL error !

**Comment by ashylen** [comment]
Same error here, it happened when I was trying to create OAuth v2 token on my new sandbox account. Old sandbox account works great.

**Comment by XemaA** [comment]
@ashylen  I fixed this error by clearing the cache and restarting my server !

**Comment by BigWenceslas** [comment]
J'ai eu le meme soucis, j'ai vide le cache, supprime le fichier temporaire mangopay et redemarre le serveur
