### ISSUE TITLE
 Allowed memory size in masons/vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php on line 200

### ISSUE THREAD

**Issue by malyadev** [Mangopay/mangopay2-php-sdk#587]
Hi, 

I have the error in the title when i try this line :

`$payOut->MeanOfPaymentDetails = new \MangoPay\PayOutPaymentDetailsBankWire();`

Did you guys know where this can came from ?

**Comment by fredericdelordm** [comment]
Hello @malyadev, we are looking into it

**Comment by iulian03** [comment]
Hi @malyadev ,

This doesn't seem to be a problem with our SDK, I cannot reproduce it. You most probably have to increase your app's memory_limit
