### ISSUE TITLE
Folder vendor doesn't exist

### ISSUE THREAD

**Issue by laurentexo** [Mangopay/mangopay2-php-sdk#589]
Hi,
demos/users_create.php
line 3 : require_once '../vendor/autoload.php'
Folder vendor doesn't exist

If replace this line by : require_once '../MangoPay/Autoloader.php';
Then :
Fatal error: Uncaught Error: Class "Psr\Log\NullLogger" not found

**Comment by fredericdelordm** [comment]
Hi @laurentexo, 

This demo is quite old and will be removed. In the meantime you can use the [Mangopay demo](https://demo-marketplace.mangopay.com/).
