### ISSUE TITLE
Invalid examples

### ISSUE THREAD

**Issue by psociety** [Mangopay/mangopay2-php-sdk#590]
If you copy examples like
```php
$mangoUser = new \MangoPay\UserNatural();
        $mangoUser->PersonType = "NATURAL";
        $mangoUser->FirstName = 'John';
        $mangoUser->LastName = 'Doe';
        $mangoUser->Birthday = 1409735187;
        $mangoUser->Nationality = "FR";
        $mangoUser->CountryOfResidence = "FR";
        $mangoUser->Email = 'john.doe@mail.com';

        //Send the request
        $mangoUser = $api->Users->Create($mangoUser);
```

It will throw an exception because it misses "UserCategory".

**Comment by ataldev** [comment]
I wish they hire some developers to update the SDKs and examples. Very hard to get setup and running like this.

**Comment by fredericdelordm** [comment]
Hello @psociety,

You have examples for these calls inside the Mangopay documentation.

**Comment by ataldev** [comment]
I have already created a [https://github.com/Mangopay/mangopay2-php-sdk/pull/602](pull request)  that adds missing data to the workflow.
