### ISSUE TITLE
Issue with php8.2

### ISSUE THREAD

**Issue by ghost** [Mangopay/mangopay2-php-sdk#592]
Sdk Version :- v3.8.0
Line number
https://github.com/Mangopay/mangopay2-php-sdk/blob/v3.8.0/MangoPay/Libraries/HttpBase.php#L23

Deprecated issue 
Issue with php8.2

SS attached of the issue

https://imgur.com/a/rN9gHZZ

**Comment by lucaspouchot** [comment]
the log file is quite polluted by this depreciation's call stack.

The rfc that Deprecate dynamic properties : [https://wiki.php.net/rfc/deprecate_dynamic_properties](https://wiki.php.net/rfc/deprecate_dynamic_properties)
