### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by ataldev** [Mangopay/mangopay2-php-sdk#593]
This package is designed in such a way, that if someone needs to use it they should read through the MangoPay documentation once, and the READ THIS PACKAGE. This makes things 10X slower than they should be.
For example for creating a PayIn, in the MangoPay documentation, there is no such thing as `ExecutionDetails`. But when creating a PayIn with this package you have to use the `ExecutionDetails`. 
Either documentation is needed for this package, or a new release is needed that does not require the package to be read from A to Z, or at least the examples to be fixed!

**Comment by fredericdelordm** [comment]
Hello @ataldev,

Thanks for the feedback. We are currently publishing examples in Mangopay documentation
