### ISSUE TITLE
PayInDirectCard - Error 400 Bad Request

### ISSUE THREAD

**Issue by laurent-bientz** [Mangopay/mangopay2-php-sdk#60]
Hi,

I try to implement a PayInDirectCard (https://docs.mangopay.com/api-references/payins/payindirectcard/)

## A. The 1st step (Create CardRegistration) is ok, I get AccessKey, PreregistrationData, CardRegistrationURL and CardRegistrationId

POST /CardRegistrations
```php
		["UserId"]= string(7) "7959571"
		["Currency"]= string(3) "EUR" 
		["CardType"]= string(18) "CB_VISA_MASTERCARD" 
```
RESPONSE
```php
		["Id"]= string(7) "8082525" 
		["Tag"]= NULL 
		["CreationDate"]= int(1439458468) 
		["UserId"]= string(7) "7959571" 
		["AccessKey"]= string(20) "1X0m87dmM2LiwFgxPLBJ" 
		["PreregistrationData"]= string(86) "XBDYiG8w9PrylPS01KmupQFG9GVaIA5cMBynS5pmG2ZEnWzds_vbQeD1VuUtUossS4wCy-yiraxeE65tmxOe8A" 
		["RegistrationData"]= NULL 
		["CardId"]= NULL 
		["CardType"]= string(18) "CB_VISA_MASTERCARD" 
		["CardRegistrationURL"]= string(63) "https://homologation-webpayment.payline.com/webpayment/getToken" 
		["ResultCode"]= NULL 
		["ResultMessage"]= NULL 
		["Currency"]= string(3) "EUR" 
		["Status"]= string(7) "CREATED"
```

## B. The 2nb step (PreRegistrationData through the form) is ok, I get back data.

> ?data=6GC916dHZPpYrs_zfN6X5JPC2RVgv6611Ff2N88cQLQ_phl4kw1SQMdY024x8x8siIzmOpGy8gxBegF13bkmwlXSGIVoX7WbZ_AulE9KQ98ZFHOBn4JQHdFdQA8F7m_b_uh-M22NjZ6dU5YsJBBYuA

## C. The 3rd step (Edit CardRegistration) is ok, I get CardId

PUT /CardRegistrations/8082525
```php
["RegistrationData"]= string(155) "data=6GC916dHZPpYrs_zfN6X5JPC2RVgv6611Ff2N88cQLQ_phl4kw1SQMdY024x8x8siIzmOpGy8gxBegF13bkmwlXSGIVoX7WbZ_AulE9KQ98ZFHOBn4JQHdFdQA8F7m_b_uh-M22NjZ6dU5YsJBBYuA"
```
RESPONSE
```php
		["Id"]= string(7) "8082525"
		["Tag"]= NULL
		["CreationDate"]= int(1439458468)
		["UserId"]= string(7) "7959571"
		["AccessKey"]=  string(20) "1X0m87dmM2LiwFgxPLBJ"
		["PreregistrationData"]= string(86) "XBDYiG8w9PrylPS01KmupQFG9GVaIA5cMBynS5pmG2ZEnWzds_vbQeD1VuUtUossS4wCy-yiraxeE65tmxOe8A"
		["RegistrationData"]= string(155) "data=6GC916dHZPpYrs_zfN6X5JPC2RVgv6611Ff2N88cQLQ_phl4kw1SQMdY024x8x8siIzmOpGy8gxBegF13bkmwlXSGIVoX7WbZ_AulE9KQ98ZFHOBn4JQHdFdQA8F7m_b_uh-M22NjZ6dU5YsJBBYuA"
		["CardId"]= string(7) "8082593"
		["CardType"]= string(18) "CB_VISA_MASTERCARD"
		["CardRegistrationURL"]= string(63) "https://homologation-webpayment.payline.com/webpayment/getToken"
		["ResultCode"]= string(6) "000000"
		["ResultMessage"]= string(7) "Success"
		["Currency"]= string(3) "EUR"
		["Status"]= string(9) "VALIDATED"
```

## D. The final step (PayInDirectCard) is not ok, I can't call it

POST /payins/card/direct
```php
		["CreditedWalletId"]= string(7) "8060822"
		["AuthorId"]= string(7) "7959571"
		["CardId"]= string(7) "8082593"
		["DebitedFunds"]= {
								["Currency"]= "EUR"
								["Amount"]= int(10000)
							}
		["Fees"]= {
						["Currency"]= "EUR"
						["Amount"]= int(0)
					}
		["SecureMode"]= "DEFAULT"
		["SecureModeUrl"]= "https://xxx..."
```

RESPONSE
> Exception > failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

I followed the doc but don't know what I'm doing wrong.

Besides, I don't understand why the parameters of the doc (https://docs.mangopay.com/api-references/payins/payindirectcard/) are not the same than the parameters of the example (https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/payment.php).
(in the doc CardId is a direct parameter - in example, he is a part of ExecutionDetails sub object, etc.)

Any help would be appreciated, thanks.

**Comment by hobailey** [comment]
Hi @laurent-bientz, could you include the error response you're getting, and also the PHP code for the payin direct you're using - the above payin code is the HTTP request (I believe), not the PHP SDK version.
Thanks :-)

**Comment by laurent-bientz** [comment]
Hi,

I'm not using the php-sdk cause our server run always PHP5.3, so we just implemented a wrapper to call the EndPoint in native PHP.

At the call moment we got an Exception with the error 400.

Here are the details (I just did a new test):
```php
try {
	$opts = array(
		''.$protocol => array(
			'method' => "".$method,
			'header' => "Authorization: Basic ".$this->_api_key."\r\n"."Content-Type: application/json; charset=utf-8"."\r\n",
			'content' => $data = json_encode($data),
			'content_length' => strlen($data)
		)
	);
	$context = stream_context_create($opts);
	$response = json_decode(file_get_contents($this->_api_url.$query, false, $context));
}
catch (Exception $e)
{
	$response = array(
		"error" => array(
			"message" => $e->getMessage(),
			"object" => "Url:"."\n".(string)print_r(
					$this->_api_url.$query,
					true
				)."\n"."Headers:"."\n".(string)print_r($opts, true)
		)
	);
}
```

And the Exception give:
```php
["error"]=>
  array(2) {
	["message"]=>
	string(156) "file_get_contents(https://api.sandbox.mangopay.com/v2/jacquesndl/payins/card/direct): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request"
	["object"]=>
	string(741) "Url: https://api.sandbox.mangopay.com/v2/jacquesndl/payins/card/direct
				Headers:
				Array
				(
					[http] => Array
						(
							[method] => POST
							[header] => Authorization: Basic amFjcXVlc25kbDp1O[........]WloVnRiTVBSMVdrZGRvZnB1RERheERpSnNTcnZWV2J6M0NZUw==
				Content-Type: application/json; charset=utf-8

							[content] => {
								"CreditedWalletId":"8060822",
								"AuthorId":"7959571",
								"CreditedUserId":"7959571",
								"CardId":"8083904",
								"DebitedFunds":{
									"Currency":"EUR",
									"Amount":1000
								},
								"Fees":{
									"Currency":"EUR",
									"Amount":0
								},
								"SecureMode":"DEFAULT",
								"SecureModeUrl":"https:\/\/...mydomain..."}
							[content_length] => 340
						)
				)
```

**Comment by hobailey** [comment]
OK, thanks. FYI, it's useful to get hold of the body of the Mangopay API response - from the file_get_contents line we can see you're getting an error 400, but if you can somehow get the body of this call, you'll see more info about what is wrong with you call.
I've just checked the logs from our end, and infact it's just the "SecureModeReturnURL" field which is missing - you're using "SecureModeUrl" I guess, but it's just the wrong naming.
Does that make sense?

**Comment by laurent-bientz** [comment]
Yup, I misspelled this param, my bad...

Btw, you made my day, thanks a lot for support, its works now.

**Comment by hobailey** [comment]
Great stuff, thanks for the follow up :-)
