### ISSUE TITLE
OAuth2 authentication

### ISSUE THREAD

**Issue by glegarand** [Mangopay/mangopay2-php-sdk#617]
As Mangopay will deprecate the Basic Auth on January 1st 2024, has someone already integrated OAuth2 with a Bearer token ?

**Comment by AntoineLemaire** [comment]
Hello, I'm interested also on that question. 
That means that this code won't work after January 1st 2024? @fredericdelordm 
```
$api = new MangoPay\MangoPayApi();

// configuration
$api->Config->ClientId = 'your-client-id';
$api->Config->ClientPassword = 'your-client-password';
$api->Config->TemporaryFolder = '/some/path/';
```

**Comment by fredericdelordm** [comment]
Hello @glegarand and @AntoineLemaire ,

You have nothing to do. The SDK supports OAuth2 and does not use Basic auth.
