### ISSUE TITLE
Fetch refunds from a payin transaction

### ISSUE THREAD

**Issue by Nakira** [Mangopay/mangopay2-php-sdk#63]
Hello,

I'm working with sdk 1.4.1 : 

I need to fetch refunds linked to a payin : 

```php
$payinId=15643643143;

$payin=$mangopay->PayIns->Get($payinId); 

echo 'this works :  '. $payin->Id.PHP_EOL;

try{
    $refund=$mangopay->PayIns->GetRefund(payinId);
}catch (\MangoPay\ResponseException $e){
    /**
obtaining : exception 'MangoPay\ResponseException' with message 'Method not allowed. The requested resource does not support http method 'GET'.' in /home/jeanch/www/.../vendor/MangoPay/mangopay2-php-sdk/MangoPaySDK/tools/restTool.inc:272
Stack trace:
#0 /home/jeanch/www/.../vendor/MangoPay/mangopay2-php-sdk/MangoPaySDK/tools/restTool.inc(126): MangoPay\RestTool->CheckResponseCode(Object(stdClass))
#1 /home/jeanch/www/.../vendor/MangoPay/mangopay2-php-sdk/MangoPaySDK/tools/restTool.inc(93): MangoPay\RestTool->RunRequest()
#2 /home/jeanch/www/.../vendor/MangoPay/mangopay2-php-sdk/MangoPaySDK/tools/apiBase.inc(178): MangoPay\RestTool->Request('/payins/2043263...', 'GET')
#3 /home/jeanch/www/.../vendor/MangoPay/mangopay2-php-sdk/MangoPaySDK/tools/apiPayIns.inc(45): MangoPay\ApiBase->GetObject('payins_getrefun...', '20432632', '\\MangoPay\\Refun...')
**/
 echo 'this happens';

}
```

GetRefund (that should actually be named geteRefunds) not working, I'm looking for an efficient way to this;
The only way i can think of is  : 
1. fetch the payin
2. fetch the author of the payin
3. fetch transactions linked to the author
4. check each transaction to see if InitialTransactionId match my initial payin

Is there a better way?

note: i cannot upgrade sdk...

**Comment by hobailey** [comment]
Hi @Nakira, thanks for your queries.
Firstly, I do not see why GetRefund should be named "geteRefunds" - could you ellaborate on this? It is only possible to get one refund ID with this function, so the singular terms seems as expected.
As for getting the refunds for a payin - there is currently no easier way to do this - although, not that you can filter your transaction list for "Nature=REFUND&Type=PAYOUT&Status=SUCCEEDED" to really narrow down the possible refund transactions for this user. Then you'll need to check the InitialTransactionId field as you suggest.

**Comment by Nakira** [comment]
Ok so my solution is not as bad as i thought.

to elaborate on getRefunds, I'm refering to https://docs.mangopay.com/api-references/refund/%E2%80%A2-refund-a-pay-in/

Partial refunds are possible on a payin, so one payin can result on many refunds.

Thansk for your previous answer

**Comment by hobailey** [comment]
You can indeed do several refunds for the same payin, however GetRefund() will only ever return one. However in later versions of the SDK, its Refunds->Get() anyway.
