### ISSUE TITLE
DebugMode is true by default ⚠️

### ISSUE THREAD

**Issue by emnbdx** [Mangopay/mangopay2-php-sdk#636]
Since commit [fe49ef57d3f0c948a2a5bbd53db1aab367c89b45](https://github.com/Mangopay/mangopay2-php-sdk/commit/fe49ef57d3f0c948a2a5bbd53db1aab367c89b45#diff-e816a1981939e0487dba3303333b9905364777a8e0dffa7c629264a3f0221e7d) DebugMode is now true by default.

**This could be problematic because it allows anyone to access the API client and secret if deployed in a production environment.**

Here is a sample of what i get display directly on browser on my test environment

<img width="772" alt="Screenshot 2024-03-11 at 23 54 29" src="https://github.com/Mangopay/mangopay2-php-sdk/assets/3239701/56fe2ad5-9393-4a84-ae21-1587ab8353ae">

@mihaimoiseanu this one is for you I think you forget to remove it after testing

For everybody looking for a workaround you have to set DebugMode manually to false
```
$mangoPayApi = new MangoPay\MangoPayApi();
...
$mangoPayApi->Config->DebugMode = false;
```

**Comment by impronta48** [comment]
Really severe! A lot of secret info exposed and payment system broken. I've downgraded to .26

**Comment by victorberson99** [comment]
Same issue here ! Had to downgrade to 0.26 too

**Comment by emnbdx** [comment]
You can just set debugmode to false instead of downgrade, as I said.
But i understand downgrade when you are not satisfied by a version ;)

**Comment by antoinep-origami** [comment]
Same here. It sure can be fixed easily by setting debug mode to false, but I am not sure to understand why the debug mode is now enabled by default, seems like an error-prone behaviour to me.

**Comment by emnbdx** [comment]
@antoinep-origami when you examine the code, you'll notice that DebugMode is annotated with the comment [INTERNAL USAGE ONLY]. This leads me to believe that its inclusion was likely an oversight by a developer.

**Comment by emnbdx** [comment]
I create a PR to fix this !
https://github.com/Mangopay/mangopay2-php-sdk/pull/637

**Comment by florentdestremau** [comment]
same issue here wtf, discovered on live user accounts !

**Comment by OpJePl44tsm4n** [comment]
same, please merge the fix!

**Comment by launay12u** [comment]
Really weird, and without any information about this change 👎🏼 
This can cause huge security problems.
