### ISSUE TITLE
Can't understand the problem

### ISSUE THREAD

**Issue by suhaboncukcu** [Mangopay/mangopay2-php-sdk#64]
When I try to use this : $mangoPayApi->Users->CreateBankAccount($UserId, $BankAccount);

I get "Bad request. One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error."

But I used the exact codes from the demo scripts on sandbox. And my mangopay user id is correct ( I can check it on dashboard) Also I can create a bank account for that user on mangopay dashboard. I can't figure out what is the problem. Are you planning to implement more detailed error responses? It is really hard to get what's wrong.

**Comment by hobailey** [comment]
Hi @suhaboncukcu, you should use try/catch to view the specific error details (as in this example: https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/users_create.php).
But I suspect you're using v2.01 of the API and the demo script was designed for v2 and hence you have a problem with the OwnerAddress field - more info: https://docs.mangopay.com/api-v2-01-overview/

**Comment by suhaboncukcu** [comment]
Ok, thanks or the reply.
