### ISSUE TITLE
Update property data types and API parameter types

### ISSUE THREAD

**Issue by mralaminahamed** [Mangopay/mangopay2-php-sdk#645]
Currently, some properties and API parameter types in the mangopay2-php-sdk library may not align with the latest version of the Mangopay API. This can lead to compatibility issues, data type mismatches, or incorrect data being passed to the API.

I propose updating the property data types and API parameter types in the library to ensure they accurately reflect the latest Mangopay API specifications. This will improve compatibility, prevent potential bugs, and ensure the library remains up-to-date with the API changes.

Proposed Changes:

1. **Review API Documentation**: Thoroughly review the latest Mangopay API documentation to identify any changes in data types or parameter types for various API endpoints.

2. **Update Property Data Types**: Update the data types of relevant properties in the library's model classes to match the API specifications.

3. **Update API Parameter Types**: Update the parameter types in the library's API client classes to match the API specifications.

4. **Update Examples and Documentation**: Update any examples or documentation within the library to reflect the changes in data types and parameter types.

5. **Add Test Cases**: Add or update test cases to ensure the changes in data types and parameter types are thoroughly tested and validated.

Potential Challenges:

- Ensuring all relevant data types and parameter types are identified and updated correctly.
- Maintaining backward compatibility, if necessary, for existing applications using the library.
- Updating any external dependencies or related libraries that may be affected by the changes.

Benefits:

- Improved compatibility with the latest Mangopay API.
- Reduced chances of data type mismatches or incorrect data being passed to the API.
- Better maintainability and extensibility of the library as it remains aligned with the API specifications.
- Increased confidence in the library's functionality and reliability.

I'm willing to work on this update and would appreciate any feedback or suggestions from the project maintainers and community members.

**Comment by mralaminahamed** [comment]
@williamdes, @florentdestremau, I kindly request your attention and cooperation regarding the following proposed update for the mangopay2-php-sdk library.

**Comment by williamdes** [comment]
I am not a MangoPay team here, only a contributor :)
Ping me on code reviews please

**Comment by mralaminahamed** [comment]
Thanks you and i will proceed with making a pull request (PR).

But any MangoPay team member here?

**Comment by mralaminahamed** [comment]
@iulian03 are you a MangoPay Team member?

**Comment by florentdestremau** [comment]
I'm not a mangopay member either (and they are not very active here anyway)

**Comment by mralaminahamed** [comment]
how can merge my pr to main branch?

**Comment by williamdes** [comment]
> how can merge my pr to main branch?

Please stop such a behavior, people need time to review
Ping for review after less than a week is quite rude

**Comment by mralaminahamed** [comment]
> Please stop such a behavior, people need time to review
> Ping for review after less than a week is quite rude

I apologize for my inquiry. I'm asking out of curiosity as I work with a product utilizing the MangoPay PHP SDK. My responsibilities include maintaining the MangoPay integration.

**Comment by williamdes** [comment]
Keep this in mind for all open source projects ;) 


Same, waiting on #642
Let's wait and see
If no news in some weeks I will contact them by email
