### ISSUE TITLE
SDK different than the official documentation

### ISSUE THREAD

**Issue by PAFsec** [Mangopay/mangopay2-php-sdk#71]
Hi,

Thank you for your work on the SDK of the MangoPay API.

Under the [API official documentation of the PayIn feature](https://docs.mangopay.com/api-references/payins/payins-card-web/) in the CREATE (POST) tab, it "says" through the response that the `RedirectURL` parameter is directly accessible from the JSON result Object.

But it actually requires to dereference the `ExecutionDetails` field of the PayIns object `ExecutionDetails->RedirectURL` and not `RedirectURL` directly

Is the documentation wrong, or the SDK?

Thank you.

Regards

**Comment by hobailey** [comment]
Hi @PAFsec,
Thanks for your message and support. Like many fields, RedirectURL is grouped within the ExecutionDetails array - in the same way PaymentDetails contains the CardType field. The documentation site refers purely to the raw JSON data returned, and doesn't (yet!) accurately represent the SDKs from this point of view.
Hugo
