### ISSUE TITLE
Overriding StorageStrategy

### ISSUE THREAD

**Issue by leihog** [Mangopay/mangopay2-php-sdk#72]
If you want to override the SDKs StorageStrategy(**IStorageStrategy**) you will run in to a problem unless you stick with php serializing the **OAuthToken**. The reason is that the property **create_time** is private and thus not accessible to outside code. Now I know this can be worked around using PHP quirks(*cast to array*) or reflection, but I'd rather not have to rely on hacks.

The better solution would be to make create_time public or add a **toArray()** function to **OAuthToken**
that simply returns a copy of the internal state. 

That would only solve the reading part however. We would also need to be able to
set the **creation_time** either by a public property or by a constructor param.

In my opinion all values should be readonly and setable only through the constructor.
It makes more sense for an OAuthToken to be immutable anyway.

**Comment by hobailey** [comment]
Hi @leihog - thanks for this feedback. We'd need to be careful of any breaking changes here of course, but we'll look into the options and get back to you :-)

**Comment by lukasz-puslecki** [comment]
Hi @leihog. 
Yes, you are right - in some cases a access is required to the property create_time. I changed it as public.
