### ISSUE TITLE
Direct payIn for big amount

### ISSUE THREAD

**Issue by onusgit** [Mangopay/mangopay2-php-sdk#74]
Hello,

I have implement mangopay in my site, i did payment of 120 EURO, status PayIn Created not success.

What i need to do next?
Payment less then 100 works fine,

I have set SecureModeReturnURL as below,
$payIn->ExecutionDetails->SecureModeReturnURL = "http".(isset($_SERVER['HTTPS']) ? "s" : null)."://".$_SERVER["HTTP_HOST"]."/customers/secure_mode";

What I need to handle in this return URL?

Any help would be appreciated, thanks.

**Comment by hobailey** [comment]
Hi @onusgit,
The `SecureModeReturnURL` works in the same way to the `ReturnURL` for a web payin, except that it is only used when `SecureModeNeeded` is `true` (which normally happens for payments over 100€). If `SecureModeNeeded` is `true`, you will need the user to be present, and to redirect them to the `SecureModeRedirectURL` so that they can enter their 3DS password (in the same way as for web payins where the amount is more than 100€, the user is required to enter their 3DS password after entering their card information).
Hopefully that makes more sense.

**Comment by onusgit** [comment]
Thanks @hobailey  for you reply,
Just for confirmation, here is code for direct payin

$data['action'] = $createdCardRegister->CardRegistrationURL;
$data['mangodata'] = $createdCardRegister->PreregistrationData;
$data['accessKeyRef'] = $createdCardRegister->AccessKey;
$data['createdCardRegister'] = $createdCardRegister->Id;
$data['returnUrl'] = FULL_BASE_URL . '/admin/customers/payment/' . $cardRegisterId . '/' . $user['User']['id']. '/' . $offer_id . '/' . $offer_type . '/' . $store_id;

So For the 3DS i need to send same payin data to mangopay with updated returnUrl right?

can you please suggest some reference link or code in php?

thanks

**Comment by hobailey** [comment]
Hi @onusgit, I do not understand the relevance of this code compared to the direct payin - this code is to register a card. I'd suggest this code for the payin direct:
```
$PayIn = new \MangoPay\PayIn();
$PayIn->CreditedWalletId = $WalletId;#TODO
$PayIn->AuthorId = $UserId;#TODO
$PayIn->PaymentType = "CARD";
$PayIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsCard();
$PayIn->DebitedFunds = new \MangoPay\Money();
$PayIn->DebitedFunds->Currency = $Currency;#TODO
$PayIn->DebitedFunds->Amount = $DebitedFunds;#TODO
$PayIn->Fees = new \MangoPay\Money();
$PayIn->Fees->Currency = $Currency;#TODO
$PayIn->Fees->Amount = $Fees;#TODO
$PayIn->ExecutionType = "DIRECT";
$PayIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
$PayIn->ExecutionDetails->SecureModeReturnURL = "http://your-return-url.com/returnurl";#TODO
$PayIn->ExecutionDetails->CardId = $CardId;#TODO
$PayIn->ExecutionDetails->SecureMode = "DEFAULT";

$result = $mangoPayApi->PayIns->Create($PayIn);

if ($result->Status=="FAILED") {//something went wrong
	//handle error by reading ResultCode #TODO
}elseif ($result->ExecutionDetails->SecureModeNeeded) {//need 3DS, so redirect approriately
	header("Location: ".$result->ExecutionDetails->SecureModeRedirectURL);
	die();
}elseif ($result->Status=="SUCCEEDED"){
	//everything ok #TODO
}else{//something weird happened
	//handle the error (probably an error 500 due to bad code above) #TODO
}
```

**Comment by onusgit** [comment]
I have did same, my query is what is form action to post 3DS password?

I see in dashboard payIn created..

please suggest some reference for the mangopay 3DS

![manngopay](https://cloud.githubusercontent.com/assets/15248145/11470408/5fd3e328-9783-11e5-92da-a0dca72abdfd.png)

**Comment by sweetyvj** [comment]
Hi,
I am facing almost same issue.I dont understand one thing that is after redirecting to the
SecureModeRedirectURL what are the steps that need to be followed.
(I guess have to post password for that card, but where to submit,what function need to be called)

<?php


$payIn = new \MangoPay\PayIn();
$payIn->CreditedWalletId = $CreditedWalletId;//$createdWallet->Id;
$payIn->AuthorId = $updatedCardRegister->UserId;
$payIn->DebitedFunds = new \MangoPay\Money();
$payIn->DebitedFunds->Amount = $DebitedFunds*100;
$payIn->DebitedFunds->Currency = "GBP";
$payIn->Fees = new \MangoPay\Money();
$payIn->Fees->Amount = 0;
$payIn->Fees->Currency = "GBP";

// payment type as CARD
$payIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsCard();
$payIn->PaymentDetails->CardType = $card->CardType;
$payIn->PaymentDetails->CardId = $card->Id;

// execution type as DIRECT
$payIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
$payIn->ExecutionDetails->SecureModeReturnURL = base_url.'controllername/action';

// create Pay-In
$createdPayIn = $mangoPayApi->PayIns->Create($payIn);

**Comment by hobailey** [comment]
Hi, you will need to redirect the user to the URL you receive in the API response (`SecureModeRedirectURL`) and on this web page, the end user can enter their 3DS information - they will then be redirected to the the  `SecureModeReturnURL` after this (whether successful or not). If you have any complications or further questions with this, I suggest you contact our technical support team (since it's not a bug with the SDK): mangopay.com/contact

**Comment by duykhanh1411** [comment]
> Hi @hobailey ,
> I am facing almost same issue.I dont understand one thing that is after redirecting to the
> SecureModeRedirectURL what are the steps that need to be followed.
> (I guess have to post password for that card, but where to submit,what function need to be called)
> 
> $payIn = new \MangoPay\PayIn();
> $payIn->CreditedWalletId = $CreditedWalletId;//$createdWallet->Id;
> $payIn->AuthorId = $updatedCardRegister->UserId;
> $payIn->DebitedFunds = new \MangoPay\Money();
> $payIn->DebitedFunds->Amount = $DebitedFunds*100;
> $payIn->DebitedFunds->Currency = "GBP";
> $payIn->Fees = new \MangoPay\Money();
> $payIn->Fees->Amount = 0;
> $payIn->Fees->Currency = "GBP";
> // payment type as CARD
> $payIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsCard();
> $payIn->PaymentDetails->CardType = $card->CardType;
> $payIn->PaymentDetails->CardId = $card->Id;
> // execution type as DIRECT
> $payIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
> $payIn->ExecutionDetails->SecureModeReturnURL = base_url.'controllername/action';
> // create Pay-In
> $createdPayIn = $mangoPayApi->PayIns->Create($payIn);

@sweetyvj Can you share me your solution after redirect to SecureModeRedirectURL
thanks
