### ISSUE TITLE
Set up a recurring payment

### ISSUE THREAD

**Issue by umbecanessa** [Mangopay/mangopay2-php-sdk#82]
Hey there, 

I'm here again :smile: 

I'm trying to create a recurring payment system with Mangopay api.

The process is : 

1) Signup, preauthorise the payin and make the first payin (and this is works perfectly)
2) save the authorisationid and all the others id on the DB 
3) call a function each month for the next payment

Now the strange issue, everything is going great 'till point 3 - there i'm calling the function with this code 

```
$PayIn = new \MangoPay\PayIn();
    $PayIn->CreditedWalletId = $walletid;
    $PayIn->AuthorId = $authorid;
    $PayIn->PaymentType = "PREAUTHORIZED";
    $PayIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsPreAuthorized();
    $PayIn->PaymentDetails->PreauthorizationId = $auth;
    $PayIn->DebitedFunds = new \MangoPay\Money();
    $PayIn->DebitedFunds->Currency = "EUR";
    $PayIn->DebitedFunds->Amount = $value*100;
    $PayIn->Fees = new \MangoPay\Money();
    $PayIn->Fees->Currency = "EUR";
    $PayIn->Fees->Amount = 0;
    // execution type as DIRECT
    $PayIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
    $PayIn->ExecutionDetails->CardId = $cardid;
    $PayIn->ExecutionDetails->SecureModeReturnURL = 'http://test.com';
      
     
   $createdPayIn = $mangoPayApi->PayIns->Create($PayIn);//Send the request
```
And this is what i get

Fatal error: Uncaught exception 'MangoPay\Libraries\ResponseException' with message 'Bad request. One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.' in /home/wasnaga/public_html/beta/mangopay2-php-sdk-2.3/MangoPay/Libraries/RestTool.php:328

It's strange since all the variable are populated and the code is the same I'm using for make the first PayIn, any suggest ?

**Comment by hobailey** [comment]
Hi @umbecanessa, are you using the same PreAuthorizationId for each payment by any chance? If so, that's your problem, since a preauth can only be used once, and afterwards you'll need to do another preauth (and by the way, you should know that a preauth expires after 7 days if it's not used).

Also, you should wrap your code in a try/catch so that you can better analyse such errors/exceptions:
```
try {
    $PayIn = new \MangoPay\PayIn();
    $PayIn->CreditedWalletId = $walletid;
    $PayIn->AuthorId = $authorid;
    $PayIn->PaymentType = "PREAUTHORIZED";
    $PayIn->PaymentDetails = new \MangoPay\PayInPaymentDetailsPreAuthorized();
    $PayIn->PaymentDetails->PreauthorizationId = $auth;
    $PayIn->DebitedFunds = new \MangoPay\Money();
    $PayIn->DebitedFunds->Currency = "EUR";
    $PayIn->DebitedFunds->Amount = $value*100;
    $PayIn->Fees = new \MangoPay\Money();
    $PayIn->Fees->Currency = "EUR";
    $PayIn->Fees->Amount = 0;
    // execution type as DIRECT
    $PayIn->ExecutionDetails = new \MangoPay\PayInExecutionDetailsDirect();
    $PayIn->ExecutionDetails->CardId = $cardid;
    $PayIn->ExecutionDetails->SecureModeReturnURL = 'http://test.com';

   $createdPayIn = $mangoPayApi->PayIns->Create($PayIn);//Send the request

} catch (MangoPay\Libraries\ResponseException $e) {
    echo $e->GetCode();//gives you the response code ("400" in this case)
    echo $e->GetMessage();//gives you the error message ("Bad request. One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error." in this case)
    print_r($e->GetErrorDetails());//an array explaining all the parameters with an error, and what that error is (the most important bit in your case - I think it will be "PreAuthorizationId" and saying it can only be used once, but with proper debugging, we don't know)
    
} catch (MangoPay\Libraries\Exception $e) {
    echo $e->GetMessage();//gives you more info about the exception

}
```

**Comment by Azim-pix** [comment]
Hi 

Currently, we are trying to develop a system where the money is deducted from the client's 3D secured card. We don't have any issue with the 1st cycle of the payment.

For the subsequent cycles, we have the issue as long as client provides the valid 3D secure path ,how can i do recurring payment with 3D card

Thanks

**Comment by umbecanessa** [comment]
What I did, was generating the 3DS path via backend, and send an email or a push to the user asking for his confirmation, in the push / email we pass the url -> the user open the url, proceed with the code and done

**Comment by Azim-pix** [comment]
Ya we can achieve like this @umbecanessa ,is it possible like how amazon and Netflix do monthly subscription plan,

**Comment by umbecanessa** [comment]
I don't think so, the 3D will always require the user input

**Comment by Azim-pix** [comment]
@umbecanessa Thanks for the response,will look others suggestion on it.........
