### ISSUE TITLE
transfer money from User wallet to Client Wallet

### ISSUE THREAD

**Issue by GibsonSG76** [Mangopay/mangopay2-php-sdk#91]
Hi,
I use mangopay on my marketplace. I would like to add some "Bonus" into this marketplace. These bonus allows users to improve their visibility on my website.
To have an access to this Bonus, Users have to pay.

Let's take an example:
Bonus 1 = 4.99€

When a User choose the Bonus 1, my App create a Pay-IN with:
amount = 4.99€
fees = 0€
and it works

In this case, I get the whole amount, not fees, but I didn't find how to create a "transfer" from the User's Wallet to my Client Wallet.

Is there a solution ? Thx.

**Comment by PhentomPT** [comment]
Hey, hope this helps

```php
//Transfer between wallets
$transfer = new MangoPay\Transfer();
$transfer->AuthorId = $author_id;
$transfer->CreditedUserId = $credited_user_id;
$transfer->DebitedFunds->Amount = "1234";
$transfer->DebitedFunds->Currency = "EUR";
$transfer->Fees->Amount = 0;
$transfer->Fees->Currency = "EUR";
$transfer->DebitedWalletID = $debited_wallet_id; //losses the money
$transfer->CreditedWalletID = $credited_wallet_id; //gets the money
$transfer->Tag = "Custom Tag";

try {
    $mangoPay->Transfers->Create($transfer);
} 
catch (Exception $e) {
    echo "<pre>";
    var_dump($e);
    echo "</pre>";
}
```

**Comment by GibsonSG76** [comment]
Hi @PhentomPT, thanks for the help but it's not solve my problem.
I know how to make a transfer between two user's wallet. But I don't know how to make a transfer between a user's wallet and my **Client** wallet. I don't know where the **Client** wallet ID is.

Client Wallet = the portfolio of the owner of the application.

**Comment by PhentomPT** [comment]
"a transfer between a user's wallet and my Client wallet" is the same as a normal transfer between wallets.

Do you have the client id?
From that you can get his wallet(s) and then make the transfer. 
```php
$mangoPay->Users->GetWallets($userId);
```

**Comment by GibsonSG76** [comment]
Ok, I have to get the wallet linked to the ClientID. The same as the "$clientid" below ?
```php
$this->mangoPayApi = new MangoPay\MangoPayApi();
$this->mangoPayApi->Config->ClientId = $clientId;
$this->mangoPayApi->Config->ClientPassword = $clientPassword;
$this->mangoPayApi->Config->TemporaryFolder = '/tmp/';
```
So, the code looks like below:
```php
$clientWallet= $mangoPay->Users->GetWallets($clientId);
```

And THEN, make a transfer between user wallet and client the client ?
```php
//Transfer between wallets
$transfer = new MangoPay\Transfer();
$transfer->AuthorId = $author_id;
$transfer->CreditedUserId = $credited_user_id;
$transfer->DebitedFunds->Amount = "1234";
$transfer->DebitedFunds->Currency = "EUR";
$transfer->Fees->Amount = 0;
$transfer->Fees->Currency = "EUR";
$transfer->DebitedWalletID = $debited_wallet_id; //losses the money
$transfer->CreditedWalletID = $clientWallet->Id; //gets the money
$transfer->Tag = "Custom Tag";

try {
    $mangoPay->Transfers->Create($transfer);
} 
catch (Exception $e) {
    echo "<pre>";
    var_dump($e);
    echo "</pre>";
}
```

**Comment by PhentomPT** [comment]
Depending on the wallet you want to obtain you need to know the MangoPay User Id (ex: 11543411)

**Comment by GibsonSG76** [comment]
I know. I try to be as clear as possible.

On my marketplace, there are two possible case :
- First: Users do their stuff and then make a payment.
In this case, my app create a PayIN to fill the buyer's wallet and then make a transfer between the buyer's wallet and seller's wallet ( minus fees ).
- Second: Users makes payment to get "advantages". In this case, my app must to make a transfer between User's wallet and I. But I don't know how to make direct payment ( not fees ) between users and I.

Do I have to create a User and a Wallet as if I was a simple user ? Or is there a default Wallet created for client ( app owner ) ?

**Comment by PhentomPT** [comment]
Oh, i got it now.
I tough you already had a User.
As you said you need to create a User and a Wallet for your self, since there is no default Wallet or User for the Owner (that i know of).

**Comment by GibsonSG76** [comment]
Okey :) thx for the help !

**Comment by PhentomPT** [comment]
Sure, no problem!
