### ISSUE TITLE
Fatale error on wrong class name

### ISSUE THREAD

**Issue by julestex** [Mangopay/mangopay2-php-sdk#98]
Running the test trigger a fatal error.
`PHP Fatal error:  Class 'MangoPay\Libraries\Upload' not found in /home/jules/v3/mangopay2-php-sdk/MangoPay/ClientLogoUpload.php on line 8`

It's because the class https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/Libraries/Upload.php is named `Page` and the file is named `Upload`.

I'm not sure if we should rename the file or the class. 
It was introduce in the commit https://github.com/Mangopay/mangopay2-php-sdk/commit/fb533d89e1a6e5aa61948a02bb9cbb4e2ddc5068.

**Comment by hobailey** [comment]
Absolutely, thanks very much for bringing this to our attention :-)

**Comment by trompette** [comment]
@hobailey, the fix you made for this issue is very much needed.

When do you think it will be part of a tagged release?

Thanks!

**Comment by hobailey** [comment]
Done: https://github.com/Mangopay/mangopay2-php-sdk/releases/tag/v2.4.1
Sorry for the delay - should have done it sooner :-/

**Comment by trompette** [comment]
@hobailey, thanks a lot!

I do not find thee new version on [packagist](https://packagist.org/packages/mangopay/php-sdk-v2). Can you help?

**Comment by hobailey** [comment]
Hmm, it's supposed to pull though automatically, but I've just done it manually :-)

**Comment by trompette** [comment]
Thanks a lot!
